<p id="user-statics-header">Thống kê thành viên</p>
<hr  />
<ul>
	<li>UITStock có <span class="blue">4</span> thành viên</li>
	<li>Tính từ 0 giờ hôm nay có <span class="blue">1</span> thành viên mới</li>
	<li class="indent">nghiepth</li>
	<li>Số người đang xem: <span class="blue">100</span></li>
	<li>Trong đó có: <span class="blue">2</span> thành viên</li>
	<li class="indent">linhnn, phuongtp</li>
</ul>             