	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item menuItem">
				<h4>Quản lý Menu Items</h4>
				<div class="float-right">																									
					<a class="minibutton btn add" path="admin/menuItem/add-item">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="menuItem" path="admin/menu/edit-item" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>
					<a class="minibutton btn publish" name="menuItem" path="admin/menu/publish-item" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon publish"></span>Published</span>
					</a>
					<a class="minibutton btn unpublish" name="menuItem" path="admin/menu/unpublish-item" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon unpublish"></span>Unpublished</span>
					</a>
					<a class="minibutton btn deleteall" name="menuItem" path="admin/menu/delete-item" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon delete"></span>Xóa</span>
					</a>					
				</div>				
			</div>
			
			<div class="portlet-content">				 							                             
                														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/menu/auto-suggestion-menuItem" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" value="Tìm kiếm" class="btnSearchS" name="alias" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   							
						</tr>
							
						<tr>
							<th width="10">#</th>
							<th width="10"><input type="checkbox" id="select_all"></th>	
							<th width="300">Menu Item</th>
							<th width="300" class="left">Default</th>							
							<th width="100" class="center">Published</th>
							<th width="200" class="center">Order</th>																																								
							<th width="100" class="right">ID</th>					
						</tr>
					</thead>
										
					<tbody class="rows">																											
						<tr class="odd gradeX" >							
							<td class="left"></td>
							<td class="center"><input type="checkbox" name="select" /></td> 
							<td class="left"></td>
							<td class="left"></td>								
							<td class="center"><img name="menuItem" path="admin/menu/set-publish" /></td>																													
							<td class="center">
								<img class="click order" path="admin/menu/change-order"  type="up" title="Click vào để đưa menuItem lên" />
								<img class="click order" path="admin/menu/change-order" type="down" title="Click vào để đưa menuItem xuống" />
				 				<input type="text" size="1" style="text-align: center" />
				 			</td>
							<td class="center"></td>																															
							<td class="right"></td>
						</tr>																			
					</tbody>
				</table>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->