	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item menuItem">
				<h4>Quản lý Menu Items</h4>
				<div class="float-right">	
				    <div class="global" catId="<?php echo $this->catId; ?>" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>"></div>																								
					<a class="minibutton btn add2" path="admin/menu/add-item/">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="Menu Item" path="admin/menu/edit-item" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>
					<a class="minibutton btn publish" name="Menu Item" mapper="menuItemMapper" path="admin/menu/publish-item">
						<span><span class="icon publish"></span>Published</span>
					</a>
					<a class="minibutton btn unpublish" name="Menu Item" mapper="menuItemMapper" path="admin/menu/unpublish-item">
						<span><span class="icon unpublish"></span>Unpublished</span>
					</a>
					<a class="minibutton btn delete" name="Menu Item" path="admin/menu/delete-item">
						<span><span class="icon delete"></span>Xóa</span>
					</a>					
				</div>				
			</div>
			
			<div class="portlet-content">				 							                             
                														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>													
						<tr>
							<th width="10">#</th>
							<th width="10"></th>	
							<th width="150">Menu Item</th>
							<th width="250">Link</th>
							<th width="10" class="center">Home</th>							
							<th width="10" class="center">Published</th>
							<th width="50" class="center">Order</th>																																								
							<th width="10" class="right">ID</th>					
						</tr>
					</thead>
										
					<tbody class="rows">																											
						<?php $i = 0; foreach ($this->parents as $parent): $i++; $parentId = $parent->id; ?>
								<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="left"><input type="radio" name="select" id="<?php echo $parentId ?>" value="<?php echo $parentId ?>"  /></td> 
									<td class="left"><?php echo $this->escape($parent->name) ?></td>
									<td class="left"><?php echo $this->escape($parent->link) ?></td>
									<td class="center"><img src="<?php if ($parent->is_home == 1) echo $this->dirImg; ?>/default.png" title="Home" /></td>								
									<?php 
										if ($parent->published == 1) {
											$title = "Click vào để ẩn menu item";
											$img =  $this->dirImg . '/AnHien_1.png'; 
										} else {
											$title = "Click vào để hiện menu item";	
											$img = $this->dirImg . '/AnHien_0.png';
										}
										
										$minOrder = $this->menuItem->getMinOrder($this->catId);
										$maxOrder = $this->menuItem->getMaxOrder($this->catId);
								
										$order = $parent->ordering;
								
										$upImg = $this->dirImg . '/up.png';
										$downImg = $this->dirImg . '/down.png';
								
										if ($order == $minOrder) $upImg = '';																			
										if ($order == $maxOrder) $downImg = '';
										if ($maxOrder == $minOrder) {$downImg = '';$upImg = '';} 
									?>
									<td class="center">
										<img name="menuItem" mapper="menuItemMapper" path="admin/menu/set-publish-item" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $parentId ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>
									<td class="center">
										<img class="click order2" path="admin/menu/change-order"  type="up" title="Click vào để đưa menu item lên" src="<?php echo $upImg; ?>" ordering="<?php echo $this->escape($parent->ordering) ?>" id="<?php echo $parentId; ?>" catId="<?php echo $this->catId; ?>" currentpath="<?php echo $_SESSION['temp']; ?>" />
										<img class="click order2" path="admin/menu/change-order" type="down" title="Click vào để đưa menu item xuống" src="<?php echo $downImg; ?>" ordering="<?php echo $this->escape($parent->ordering) ?>" id="<?php echo $parentId; ?>" catId="<?php echo $this->catId; ?>" currentpath="<?php echo $_SESSION['temp']; ?>" />
						 				<input type="text" size="1" style="text-align: center" value="<?php echo $order ?>" />
						 			</td>																															
									<td class="right"><?php echo $parentId ?></td>
								</tr>		
								<?php 
									if (null != $this->subs) {
										foreach ($this->subs as $sub): $i++; if ($sub->parent_id == $parentId) {									
								?>
									<tr class="odd gradeX" >							
										<td class="left"><?php echo $i ?></td>
										<td class="left"><input type="radio" name="select" id="<?php echo $sub->id ?>" value="<?php echo $sub->id ?>"  /></td> 
										<td class="left inside"><?php echo $this->escape($sub->name) ?></td>
										<td class="left"><?php echo $this->escape($sub->link) ?></td>
										<td class="center"></td>	
										<td class="center">
											<?php 
												if ($parent->published == 1) {
													$title = "Click vào để ẩn menu item";
													$img =  $this->dirImg . '/AnHien_1.png'; 
												} else {
													$title = "Click vào để hiện menu item";	
													$img = $this->dirImg . '/AnHien_0.png';
												}																						 
											?>		
											<img name="menuItem" mapper="menuItemMapper" path="admin/menu/set-publish-item" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $sub->id ?>" pathDirImg="<?php echo $this->dirImg; ?>" />					
										</td>																															
										<td class="center"></td>
										<td class="right"><?php echo $sub->id ?></td>																																																	
								</tr>							
								<?php } endforeach; } ?>									
							<?php endforeach ?>														
					</tbody>
				</table>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->