	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item menuCategory">
				<h4>Quản lý Menu Category</h4>
				<div class="float-right">		
					<div class="global" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>"></div>																																								
					<a class="minibutton btn add" path="admin/menu/add-cat">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="Menu Category" path="admin/menu/edit-cat" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>					
					<a class="minibutton btn delete" name="Menu Category" path="admin/menu/delete-cat">
						<span><span class="icon delete"></span>Xóa</span>
					</a>					
				</div>				
			</div>
			
			<div class="portlet-content">				 							                														
				<table width="100%" cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>						
						<tr>
							<th width="10">#</th>
							<th width="10"></th>
							<th class="left">Name</th>
							<th class="left">Description</th>
							<th>Menu Item(s)</th>												
							<th width="10" class="center">ID</th>						
						</tr>
					</thead>
					<tbody class="rows">		
							<?php $i = 0; foreach ($this->categories as $category): $i++; if ($i % 2 != 0) {?>					
							<tr class="odd gradeX" >							
								<td class="left"><?php echo $i ?></td>
								<td class="center"><input type="radio" name="select" id="<?php echo $category->id; ?>" /></td> 
								<td class="left"><?php echo $category->name; ?></td>	
								<td class="left"><?php echo $category->description; ?></td>
								<td class="center"><a href="admin/menu/list-item/catId/<?php echo $category->id; ?>/"><img src="<?php echo $this->dirImg; ?>/view.png" /></a></td>																																					
								<td class="center"><?php echo $category->id; ?></td>
							</tr>						
							<?php } else { ?>	
							<tr class="even gradeC" >							
								<td class="left"><?php echo $i ?></td>
								<td class="center"><input type="radio" name="select" id="<?php echo $category->id; ?>" /></td> 
								<td class="left"><?php echo $category->name; ?></td>	
								<td class="left"><?php echo $category->description; ?></td>
								<td class="center"><a href="admin/menu/list-item/catId/<?php echo $category->id; ?>/"><img src="<?php echo $this->dirImg; ?>/view.png" /></a></td>																																					
								<td class="center"><?php echo $category->id; ?></td>
							</tr>
							<?php } ?>	
							<?php endforeach ?>		
					</tbody>
				</table>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->