<section class="news-box">
	<ul class="tab">
		<li class="first"><a href="news/index/category">Tin tức</a></li>
		<li><a href="news/index/category">Tin vắn chứng khoán</a></li>
		<li><a href="news/index/category">Tin HOSE</a></li>
		<li><a href="news/index/category">Tin từ công ty niêm yết</a></li>
	</ul>           
	<div class="newcontent">
		<article class="main left">
			<a href="news/index/detail"><img src="files/news/30102010/chungkhoan_xvongcrp911468777small.jpg" class="left" width="130" height="100"/></a>
			<hgroup>
				<h2><a href="news/index/detail">SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a></h2>
				<p>Sở Giao dịch Chứng khoán Hà Nội (HNX) thông báo 8/11 là ngày giao dịch không hưởng quyền, ngày 10/11 là thời hạn đăng ký cuối cùng để tạm ứng cổ tức năm 2010 bằng tiền Ngân hàng Thương mại Cổ phần Á châu (mã ACB-HNX).</p>
			</hgroup>
			<div class="clear"></div>
		</article>
		<article class="right">
		   <ul class="list">
				<li><a href="news/index/detail">SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a></li>
				<li><a href="news/index/detail">Dược Hà Tây kiến nghị truy tiếp DVD “tội làm giá” </a></li>
				<li><a href="news/index/detail">HBC: đầu tư dự án tại Nhà Bè và triển khai ép cọc khu chung cư Bình An</a></li>
		   </ul> 
		</article>
		<div class="clear"></div>
	</div>
</section>

<section class="news-box">
	<ul class="tab">
		<li class="first"><a>Nhận định thị trường</a></li>
		<li><a>Công ty chứng khoán nhận định</a></li>
		<li><a>Thị trường</a></li>
		<li><a>Công ty</a></li>
	</ul>           
	<div class="newcontent">
		<article class="main left">
			<img src="files/news/30102010/chungkhoan_xvongcrp911468777small.jpg" class="left" width="130" height="100"/>
			<hgroup>
				<h2>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</h2>
				<p>Sở Giao dịch Chứng khoán Hà Nội (HNX) thông báo 8/11 là ngày giao dịch không hưởng quyền, ngày 10/11 là thời hạn đăng ký cuối cùng để tạm ứng cổ tức năm 2010 bằng tiền Ngân hàng Thương mại Cổ phần Á châu (mã ACB-HNX).</p>
			</hgroup>
			<div class="clear"></div>
		</article>
		<article class="right">
		   <ul class="list">
				<li><a>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a></li>
				<li><a>Dược Hà Tây kiến nghị truy tiếp DVD “tội làm giá” </a></li>
				<li><a>HBC: đầu tư dự án tại Nhà Bè và triển khai ép cọc khu chung cư Bình An</a></li>
		   </ul> 
		</article>
		<div class="clear"></div>
	</div>
</section>

<section class="news-box">
	<ul class="tab">
		<li class="first"><a>Kinh tế Việt Nam</a></li>
		<li><a>Tài chính - Ngân hàng</a></li>
		<li><a>Bất động sản</a></li>                
	</ul>           
	<div class="newcontent">
		<article class="main left">
			<img src="files/news/30102010/chungkhoan_xvongcrp911468777small.jpg" class="left" width="130" height="100"/>
			<hgroup>
				<h2>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</h2>
				<p>Sở Giao dịch Chứng khoán Hà Nội (HNX) thông báo 8/11 là ngày giao dịch không hưởng quyền, ngày 10/11 là thời hạn đăng ký cuối cùng để tạm ứng cổ tức năm 2010 bằng tiền Ngân hàng Thương mại Cổ phần Á châu (mã ACB-HNX).</p>
			</hgroup>
			<div class="clear"></div>
		</article>
		<article class="right">
		   <ul class="list">
				<li><a>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a></li>
				<li><a>Dược Hà Tây kiến nghị truy tiếp DVD “tội làm giá” </a></li>
				<li><a>HBC: đầu tư dự án tại Nhà Bè và triển khai ép cọc khu chung cư Bình An</a></li>
		   </ul> 
		</article>
		<div class="clear"></div>
	</div>
</section>

<section class="news-box">
	<ul class="tab">
		<li class="first"><a>Kinh tế thế giới</a></li>
		<li><a>Chứng khoán</a></li>
		<li><a>Thị trường</a></li>                
	</ul>           
	<div class="newcontent">
		<article class="main left">
			<img src="files/news/30102010/chungkhoan_xvongcrp911468777small.jpg" class="left" width="130" height="100"/>
			<hgroup>
				<h2>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</h2>
				<p>Sở Giao dịch Chứng khoán Hà Nội (HNX) thông báo 8/11 là ngày giao dịch không hưởng quyền, ngày 10/11 là thời hạn đăng ký cuối cùng để tạm ứng cổ tức năm 2010 bằng tiền Ngân hàng Thương mại Cổ phần Á châu (mã ACB-HNX).</p>
			</hgroup>
			<div class="clear"></div>
		</article>
		<article class="right">
		   <ul class="list">
				<li><a>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a></li>
				<li><a>Dược Hà Tây kiến nghị truy tiếp DVD “tội làm giá” </a></li>
				<li><a>HBC: đầu tư dự án tại Nhà Bè và triển khai ép cọc khu chung cư Bình An</a></li>
		   </ul> 
		</article>
		<div class="clear"></div>
	</div>
</section>

<section class="news-box">
	<ul class="tab">
		<li class="first"><a>Kiến thức cơ bản</a></li>
		<li><a>Kiến thức đầu tư</a></li>            
	</ul>           
	<div class="newcontent">
		<article class="main left">
			<img src="files/news/30102010/chungkhoan_xvongcrp911468777small.jpg" class="left" width="130" height="100"/>
			<hgroup>
				<h2>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</h2>
				<p>Sở Giao dịch Chứng khoán Hà Nội (HNX) thông báo 8/11 là ngày giao dịch không hưởng quyền, ngày 10/11 là thời hạn đăng ký cuối cùng để tạm ứng cổ tức năm 2010 bằng tiền Ngân hàng Thương mại Cổ phần Á châu (mã ACB-HNX).</p>
			</hgroup>
			<div class="clear"></div>
		</article>
		<article class="right">
		   <ul class="list">
				<li><a>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a></li>
				<li><a>Dược Hà Tây kiến nghị truy tiếp DVD “tội làm giá” </a></li>
				<li><a>HBC: đầu tư dự án tại Nhà Bè và triển khai ép cọc khu chung cư Bình An</a></li>
		   </ul> 
		</article>
		<div class="clear"></div>
	</div>
</section>