<?php 
	foreach ($categories as $category) {
?>
	<section class="news-box">
		<ul class="tab">
			<li class="first"><a href=""><?php echo $category->name; ?></a></li>
			<?php 				
				$subs = $this->categoryMapper->getNewsSub($category->id);
				foreach ($subs as $sub) {					
			?>
				<li><a href=""><?php echo $sub->name; ?></a></li>
			<?php } ?>
		</ul>
		<div class="newcontent">
			<?php 				
				$articles = $this->newsMapper->getArticleByParent($category->id, 4);				
				$i = 0;
				foreach ($articles as $article) {					
				$i++;
				if ($i == 1) {					
			?>
			<article class="main left">
				<a href=""><img src="<?php echo $article['image']; ?>" class="left" width="130" height="100"/></a>
				<hgroup>
					<h2><a href=""><?php echo $article['title']; ?></a></h2>
					<p><?php echo $article['summarize'];?></p>
				</hgroup>
				<div class="clear"></div>
			</article>
			<?php } else {?>
			<article class="right">
			   <ul class="list">
					<li><a href=""><?php echo $article['title']; ?></a></li>										
			   </ul> 
			</article>			
			<?php } } ?>
			<div class="clear"></div>
		</div>
	</section>
<?php } ?>