<section id="nav-user">
			<hgroup class="left">
				<form method="get" action="news/index/search">
					<input type="text" value="Tìm kiếm" class="SearchTextBox" name="key" size="30" /><input type="button" id="btnSearch" />
				</form>					
			</hgroup>
			
			<div class="right">
				<span class="Timer"></span>				
				<img class="theme-icon" val="4" title="Theme mặc định" src="<?php echo $this->dirImg ?>/icon/theme-default.png" />
				<img class="theme-icon" val="11" title="Thêm Noel" src="<?php echo $this->dirImg ?>/icon/theme-noel.png" />					
			</div>			
			
			<div class="clear"></div><!-- end .clear -->
			
			
		</section> 