<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item module">
			<h4>Xem module</h4>
			<div class="float-right">											
				<div class="global" id="<?php echo $this->module->id; ?>" path1="admin/module/edit-module/id/<?php echo $this->module->id ?>" path2="admin/module/delete-module" back="<?php echo $_SESSION['temp']; ?>"></div>																																																																
				<a class="minibutton btn edit2">
					<span><span class="icon edit" ></span>Sửa</span>
				</a>
				<a class="minibutton btn delete2" name="module">
						<span><span class="icon delete"></span>Xóa</span>
				</a>
				<a class="minibutton btn close" name="module">
						<span><span class="icon close"></span>Đóng</span>
				</a>								
			</div>				
		</div>
		
		<div class="portlet-content">									 							                													
			<table cellpadding="0" cellspacing="0" border="0" class="display">
				<tr>
					<td width="90"><b>Module name:</b></td>
					<td><?php echo $this->module->name; ?></td>
				</tr>
				<tr>
					<td><b>Description:</b></td>
					<td><?php echo $this->module->description; ?></td>
				</tr>								
				<tr>
					<td><b>Published:</b></td>
					<?php $published = ($this->module->published == 1) ? "Yes" : "No"; ?>
					<td><?php echo $published; ?></td>
				</tr>
			</table>
																																				
		</div>
	</div>			
	
</div><!--  end #content -->