<section id="stock-index">
	<h2 class="panel-header">VN-INDEX</h2>
		
	<hgroup class="panel-content">
	<p>Chỉ số VN-Index</p>
		<img src="<?php echo $this->dirImg; ?>/stock-index.png" width="380px" />
	</hgroup>                        
</section>

<section id="stock-vertical">
	<h2 class="panel-header">Chỉ số chứng khoán</h2>
												
	<table width="100%">
		<thead>
			<tr>
				<td align="center" width="60">Mã CK</td>
				<td align="center" width="70">Giá</td>
				<td align="center" width="71">KL</td>
				<td align="center" width="80">+/-</td>
			</tr>
		</thead>
	</table>
	
	<hgroup class="panel-content-data">   
		<table width="100%">
			<tbody>
				<tr>
					<td align="center" width="70">AAM</td>
					<td align="center" width="80">25.000</td>
					<td align="center" width="80">14.800</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/up.gif" />200</td>
				</tr>
				<tr>
					<td align="center" width="70">ABT</td>
					<td align="center" width="80">54.000</td>
					<td align="center" width="80">5.000</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/down.gif" />1.000</td>
				</tr>
				<tr>
					<td align="center" width="70">AAM</td>
					<td align="center" width="80">25.000</td>
					<td align="center" width="80">14.800</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/up.gif" />200</td>
				</tr>
				<tr>
					<td align="center" width="70">ABT</td>
					<td align="center" width="80">54.000</td>
					<td align="center" width="80">5.000</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/down.gif" />1.000</td>
				</tr>
				<tr>
					<td align="center" width="70">AAM</td>
					<td align="center" width="80">25.000</td>
					<td align="center" width="80">14.800</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/up.gif" />200</td>
				</tr>
				<tr>
					<td align="center" width="70">ABT</td>
					<td align="center" width="80">54.000</td>
					<td align="center" width="80">5.000</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/down.gif" />1.000</td>
				</tr>
				<tr>
					<td align="center" width="70">AAM</td>
					<td align="center" width="80">25.000</td>
					<td align="center" width="80">14.800</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/up.gif" />200</td>
				</tr>
				<tr>
					<td align="center" width="70">ABT</td>
					<td align="center" width="80">54.000</td>
					<td align="center" width="80">5.000</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/down.gif" />1.000</td>
				</tr>
				<tr>
					<td align="center" width="70">AAM</td>
					<td align="center" width="80">25.000</td>
					<td align="center" width="80">14.800</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/up.gif" />200</td>
				</tr>
				<tr>
					<td align="center" width="70">ABT</td>
					<td align="center" width="80">54.000</td>
					<td align="center" width="80">5.000</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/down.gif" />1.000</td>
				</tr>
				<tr>
					<td align="center" width="70">AAM</td>
					<td align="center" width="80">25.000</td>
					<td align="center" width="80">14.800</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/up.gif" />200</td>
				</tr>
				<tr>
					<td align="center" width="70">ABT</td>
					<td align="center" width="80">54.000</td>
					<td align="center" width="80">5.000</td>
					<td align="center" width="70"><img src="<?php echo $this->dirImg; ?>/down.gif" />1.000</td>
				</tr>
			</tbody>                                
		</table>                              
</hgroup>
				   
	<p class="stock-time">Kết quả GD ngày <b>20/10/2010</b></p>                    
</section>

<div class="clear"></div><!-- end .clear -->