	<div id="content" class="xfluid">
		
		<div class="portlet x3 infor" >
			
			<div class="portlet-header">
				<h4>Thống kê hôm nay</h4>
			</div> <!-- .portlet-header -->
			
			<div class="portlet-content">
				<table cellspacing="0" class="info_table">
					<tbody>
						<tr>
							<td class="value">50</td>
							<td class="full">lượt truy cập</td>
						</tr>
						<tr>					
							<td class="value">100</td>
							<td class="full">chứng khoán bán ra</td>
						</tr>
						<tr>					
							<td class="value">300</td>
							<td class="full">chứng khoán mua vào</td>
						</tr>
						<tr>					
							<td class="value">100</td>
							<td class="full">tin tức</td>
						</tr>										
						<tr>
							<td class="value">10</td>
							<td class="full">yêu cầu hỗ trợ</td>
						</tr>
						<tr>
							<td class="value">10</td>
							<td class="full">việc cần làm</td>
						</tr>
					</tbody>
				</table>
			</div> <!-- .portlet-content -->			
		</div> <!-- .portlet -->
		
		<div id="dash_chart" class="portlet x9 dashboard">
			
			<div class="portlet-header">
				<h4>Công cụ</h4>							
			</div> <!-- .portlet-header -->
			
			<div class="portlet-content">					
					<ul>
					   <li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/stock.png">
								<span>Chứng khoán</span>
							</a>
						</li>
						
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/analyze.png">
								<span>Biểu đồ phân tích</span>
							</a>
						</li>
						
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/exchange.png">
								<span>Giao dịch</span>
							</a>
						</li>
						
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/write.png">
								<span>Viết tin tức</span>
							</a>
						</li>
						
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/news.png">
								<span>Danh sách tin</span>
							</a>
						</li>
						
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/comments.png">
								<span>Bình luận tin</span>
							</a>
						</li>	
											
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/users.png">
								<span>Thành viên</span>
							</a>
						</li>
						
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/file-manager.png">
								<span>File manager</span>
							</a>
						</li>
						
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/statistic.png">
								<span>Visit Statics</span>
							</a>
						</li>
																								
						<li>
							<a>
								<img alt="" src="<?php echo $this->dirImg;?>/Dashboard/security.png">
								<span>Configuration</span>
							</a>
						</li>
																		
										
					</ul>										
			</div> <!-- .portlet-content -->			
		</div> <!-- .portlet -->		
		
		<div class="xbreak"></div> <!-- .xbreak -->
		
		<div id="ticket" class="portlet x6">			
			<div class="portlet-header">
				<h4>Yêu cầu hỗ trợ</h4>
				
				<ul class="portlet-tab-nav">
					<li class="portlet-tab-nav-active"><a href="#allreq" rel="tooltip" title="All support requests.">Tất cả</a></li>						
					<li class=""><a href="#openreq" rel="tooltip" title="Recently opened to request.">Chờ</a></li>
					<li class=""><a href="#respreq" rel="tooltip" title="Recently responded to request.">Đã trả lời</a></li>
				</ul>
			</div> <!-- .portlet-header -->
			
			<div id="ticket" class="portlet-content">
				
				<div id="openreq" class="portlet-tab-content">
					<table class="support_table" cellspacing="0">
						<tbody>
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Lorem ipsum dolor sit amet</a></td>
							<td class="who">Gửi bởi phucdd</td>
						</tr>
	
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Consectetur adipiscing</a></td>
							
							<td class="who">Gửi bởi nghiepth</td>
						</tr>
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Sed in porta lectus maecenas</a></td>
							<td class="who">Gửi bởi phuongtp</td>
						</tr>
						<tr>
							<td><span class="ticket open">Chờ</span></td>
	
							<td class="full"><a href="#">Dignissim enim</a></td>
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Duis nec rutrum lorem</a></td>
							
	
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Maecenas id velit et elit</a></td>
	
							
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Duis nec rutrum lorem</a></td>
							
	
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						</tbody>
					</table>
				</div> <!-- .portlet-tab-content -->
				
				<div id="allreq" class="portlet-tab-content">
					<table class="support_table" cellspacing="0">
						<tbody>
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Lorem ipsum dolor sit amet</a></td>
							<td class="who">Gửi bởi phucdd</td>
						</tr>
	
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Consectetur adipiscing</a></td>
							<td class="who">Gửi bởi nghiepth</td>
						</tr>
						<tr>
							<td><span class="ticket open">Chờ</span></td>
							<td class="full"><a href="#">Sed in porta lectus maecenas</a></td>
							
							<td class="who">Gửi bởi phuongtp</td>
						</tr>
						<tr>
							<td><span class="ticket closed">Đóng</span></td>
	
							<td class="full"><a href="#">Dignissim enim</a></td>
							
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
							<td class="full"><a href="#">Duis nec rutrum lorem</a></td>

	
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket closed">Đóng</span></td>
							<td class="full"><a href="#">Maecenas id velit et elit</a></td>
	
							
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
							<td class="full"><a href="#">Duis nec rutrum lorem</a></td>

	
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						</tbody>
					</table>
				</div> <!-- .portlet-tab-content -->
				
				<div id="respreq" class="portlet-tab-content">
					<table class="support_table" cellspacing="0">
						<tbody>
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
							<td class="full"><a href="#">Lorem ipsum dolor sit amet</a></td>
							
							<td class="who">Gửi bởi phucdd</td>
						</tr>
	
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
							<td class="full"><a href="#">Consectetur adipiscing</a></td>

							<td class="who">Gửi bởi nghiepth</td>
						</tr>
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
							<td class="full"><a href="#">Sed in porta lectus maecenas</a></td>
							
							<td class="who">Gửi bởi phuongtp</td>
						</tr>
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
	
							<td class="full"><a href="#">Dignissim enim</a></td>
							
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
							<td class="full"><a href="#">Duis nec rutrum lorem</a></td>
							
	
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
							<td class="full"><a href="#">Maecenas id velit et elit</a></td>
	
							
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						<tr>
							<td><span class="ticket responded">Đã trả lời</span></td>
							<td class="full"><a href="#">Duis nec rutrum lorem</a></td>
							
	
							<td class="who">Gửi bởi linhnn</td>
						</tr>
						</tbody>
					</table>
				</div> <!-- .portlet-tab-content -->

			</div> <!-- .portlet-content -->			
		</div>  <!-- .portlet -->
				
		<div id="todo" class="portlet x6">	
			<div class="portlet-header">
				<h4>Việc cần làm</h4>							
			</div> <!-- .portlet-header -->		
			
			<div class="portlet-content">								
					<table class="support_table" cellspacing="0">
						<tbody>
							<tr>								
								<td class="full"><a href="#">Lorem ipsum dolor sit amet</a></td>								
							</tr>
							<tr>								
								<td class="full"><a href="#">Lorem ipsum dolor sit amet</a></td>								
							</tr>
							<tr>								
								<td class="full"><a href="#">Lorem ipsum dolor sit amet</a></td>								
							</tr>
							<tr>								
								<td class="full"><a href="#">Lorem ipsum dolor sit amet</a></td>								
							</tr>						
						</tbody>
					</table>							
			</div> <!-- .portlet -->
		</div> <!-- .portlet -->
		
	</div> <!-- #content -->