<style>
body { background: #263849; font: 12px/1.7em arial, sans-serif; }
</style>
<div id="login">
	
	<h1 id="title"><a href="#">Slate Admin</a></h1>
	
<div id="login-body" class="clearfix"> 

	 <?php if (isset($this->message)) {?>
		<div class="warning">
			<?php echo $this->message; ?>
		</div>					
	<?php } ?>    
	<form action="" name="login" id="login_form" method="post">
		
		
	                    <div class="content_front">

	        <div class="pad">
	        	
	        	<div class="field">
					<label>Email:</label>
					
					<div class=""><span class="input"><input name="email" id="email" class="text" type="text" value="" /></span></div>
				</div> <!-- .field -->
				
				<div class="field">
					<label>Mật khẩu:</label>
					
					<div class=""><span class="input"><input name="password"  class="text" type="password" value="" /></span></div>
				</div> <!-- .field -->				
				
				<div class="field">
					<span class="label">&nbsp;</span>
					
					<div class=""><button name="btnSubmit" type="submit" class="btn">Đăng nhập</button></div>
				</div> <!-- .field -->
		

	        </div>
	    </div>

		
	</form>

</div>

</div> <!-- #login -->
