<section id="stock-statics">
	<h2 class="sidebar-header">Thông tin</h2>
	
	<?php	 	   	      	
 		foreach ($parentItem as $parent): 		
 		 
 		$idP = ($parent->name == 'Bảng giá trực tuyến') ? "stock-online" :
 													"stock-tool";	
 		
 		$idS = ($parent->name == 'Bảng giá trực tuyến') ? "submenu-stock-online" :
 													"submenu-stock-tool";
	?>
		<p id="<?php echo $idP ?>" class="statics"><?php echo $parent->name ?></p>
		<ul id="<?php echo $idS ?>">
		<?php	 	   	      	
	 		foreach ($subItem as $sub): 	 			 		 
		 		if ($sub->parent_id == $parent->id) {	
		?>
			<li><a href="<?php echo $sub->link ?>"><?php echo $sub->name ?></a></li>						
		<?php } endforeach ?>					                        
		</ul>	
	<?php endforeach ?>                                               
</section> 