<section id="stock-statics">
	<h2 class="sidebar-header">Thông tin</h2>
	
	<p id="stock-online" class="statics">Bảng giá trực tuyến</p>
	<ul id="submenu-stock-online">
		<li><a href="#">Sàn HOSE</a></li>	                          
	</ul>
	
	<p id="stock-tool" class="statics">UITStock</p>
	<ul id="submenu-stock-tool">
		<li><a href="#">CP nóng tại UITStock</a></li>
		<li><a href="#">Top CP UITStock</a></li>
		<li><a href="#">Top CP niêm yết</a></li>                        
		<li><a href="#">Tìm CP theo giá</a></li>								
		<li><a href="#">Thống kê sàn niêm yết</a></li>    
		<li><a href="#">Dữ liệu ngành</a></li>                            
	</ul>                                                  
</section> 