<section id="top-news">
	<div class="left">
		<a href="news/index/detail"><img src="files/news/30102010/chungkhoan_ylqynpne940903327large.jpg" width="200" height="200"/></a>
	</div>
	<div class="right">
		<h2><a href="news/index/detail">Huy động và cho vay vốn bằng vàng: Vì sao phải siết?</a></h2>
		<p>
			Chiều 28/10, Ngân hàng Nhà nước bất ngờ công bố Thông tư 22/TT-NHNN về quản lý huy động và cho vay bằng vàng đối với tổ chức tín dụng, theo hướng thu hẹp đối tượng và hoạt động kinh doanh. Vì sao cần có thông tư này?<br />
			&gt; <a href="news/index/detail">SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a>
		</p>              
	</div>
	<div class="clear"></div>
</section>