<section id="top-news">
	<div class="left">
		<a href=""><img src="<?php echo $new[0]->image;?>" width="200" height="200"/></a>
	</div>
	<div class="right">
		<h2><a href=""><?php echo $new[0]->title;?></a></h2>
		<p>
			<?php echo $new[0]->summarize;?><br />
			&gt; <a href="news/index/detail">SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a>
		</p>              
	</div>
	<div class="clear"></div>
</section>
