<?php echo $this->doctype(); ?>

<html>
<head>	
	<!--[if IE]><base href="http://<?php echo $_SERVER['SERVER_NAME']; ?>"></base><![endif]-->
    <!--[if !IE]>--><base href="http://<?php echo $_SERVER['SERVER_NAME']; ?>" /><!--<![endif]-->  
    <?php 
	    echo $this->headMeta()->setIndent(' ')."\n"; 
	    echo $this->headTitle()->setIndent(' ')."\n"; 
	    echo $this->headLink()->setIndent(' ')."\n";
	    echo $this->headScript()->setIndent(' ')."\n"; 
	?>    	
</head>
<body>
    <div id="wrapper" class="clearfix">
        <?php 
            if (isset($_SESSION['log']))
            	echo $this->render('header.phtml');	        		          			
		    echo $this->layout()->content; 	                                                                          
            if (isset($_SESSION['log']))
		    	echo $this->render('footer.phtml'); 
        ?>                             			    
   </div><!-- End #wrapper -->	
</body>
</html>