<section id="nav-user">
	<?php if (!$_SESSION['player_log']) {?>
	<hgroup class="left">
		<span><a href="auth/login/">Đăng nhập |</a></span>
		<span><a href="auth/register/">Đăng ký</a></span>
	</hgroup>
	<?php } else { ?>
	<hgroup class="left">
		<span>Chào <span class="green"><?php echo $_SESSION['username']?></span> |</span>
		<span>Hạng: <span class="green">3678</span> | </span>
		<span>Tổng số tài sản: <span class="green">1,004,040,690</span> | </span>
		<span>Số dư tiền mặt: <span class="green">975,310,690</span> | </span>
		<span><a class="blue" href="player/infor/" >Thông tin tài khoản |</a></span>
		<span><a class="blue" href="auth/log-out/" >Thoát</a></span>
	</hgroup>
	<?php } ?>
		
	<span class="Timer right"></span>
	
	<div class="clear"></div><!-- end .clear -->
</section>