<?php 
	if ($this->users != null) {
		$i = 0;
		foreach ($this->users as $user) :
			$i++;			
			$time = date('H:i:s', $user['last_visit']);	
			$browserInfo = Cloud_Model_Utli_CloudUtli::getBrowser($user['browser']);
			$browser = $browserInfo['Browser'] . ' ' . $browserInfo['Version'];				
			$os = Cloud_Model_Utli_CloudUtli::getOs($user['browser']);
?>				
<tr>
	<td><?php echo $i ?></td>										
	<td><a href="admin/player/view/id/<?php echo $user['id'] ?>"><?php echo $user['full_name'] ?></a></td>
	<td><?php echo  $time ?></td>
	<td><?php echo $user['ip'] ?></td>
	<td><?php echo $browser ?></td>
	<td><?php echo $os ?></td>
	<td class="right"><?php echo $user['id'] ?></td>
</tr>		
<?php endforeach ?>
<?php } ?>