<section class="news-other">
	<p>
		<span>Các tin khác</span>
	</p>
	<ul>
		<li><a>'Nhà đầu tư chứng khoán dài hạn có thể bắt đầu giải ngân' <label>(24/10)</label></a></li>
		<li><a>Chứng khoán kéo dài những phiên giao dịch ảm đạm <label>(23/10</label></a></li>
		<li><a>Vn-Index bất ngờ bật xanh cuối phiên <label>(22/10)</label></a></li>
		<li><a>Chứng khoán gượng dậy sau phiên giảm sâu <label>(21/10</label></a></li>
		<li><a>ACB: Trả cổ tức năm 2010 bằng tiền <label>(21/10</label></a></li>
	</ul>
	<div class="continue">
		<a>Xem tiếp...</a>
	</div>
</section>  