	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header"><h4>Danh sách các quyền</h4></div>
			
			<div class="portlet-content">
												
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
						<tr class="tool">
							<th></th>
							<th colspan="2">
								<input type="button" id="delete_all" value="Xóa" />
								<input type="button" id="edit_all" value="Chỉnh" />
							</th>
							<th colspan="2" class="right">
							   <a>Thêm quyền</a>
							</th>
						</tr>
						<tr>
							<th width="2">#</th>
							<th width="5"><input type="checkbox"/></th>
							<th>Tên quyền</th>																																	
							<th width="200"  class="edit-th">Edit</th>																						
							<th width="2">ID</th>					
						</tr>					
					</thead>
					<tbody>
						<tr class="odd gradeX">							
							<td class="center">1</td>
							<td><input type="checkbox"/></td>
							<td class="center">Quản lý menu</td>																											
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /><img src="<?php echo $this->dirImg; ?>/NoiBat_1.jpg" title="Nổi bật" /></td>																				
							<td class="center">1</td>
						</tr>
						
						<tr class="even gradeC">							
							<td class="center">2</td>
							<td><input type="checkbox"/></td>
							<td class="center">Quản lý chứng khoán</td>																											
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /><img src="<?php echo $this->dirImg; ?>/NoiBat_1.jpg" title="Nổi bật" /></td>																				
							<td class="center">2</td>
						</tr>
						
						<tr class="odd gradeX">							
							<td class="center">3</td>
							<td><input type="checkbox"/></td>
							<td class="center">Quản lý tin tức</td>																											
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /><img src="<?php echo $this->dirImg; ?>/NoiBat_1.jpg" title="Nổi bật" /></td>																				
							<td class="center">3</td>
						</tr>
						
						<tr class="even gradeC">							
							<td class="center">4</td>
							<td><input type="checkbox"/></td>
							<td class="center">Quản lý thành viên</td>																											
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /><img src="<?php echo $this->dirImg; ?>/NoiBat_1.jpg" title="Nổi bật" /></td>																				
							<td class="center">4</td>
						</tr>												
					</tbody>
				</table>																																	
			</div>
		</div>
	</div><!--  end #content -->