	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header"><h4>Danh sách thành viên</h4></div>
			
			<div class="portlet-content">
												
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
						<tr class="tool">
							<th></th>
							<th colspan="2">
								<input type="button" id="delete_all" value="Xóa" />
								<input type="button" id="edit_all" value="Chỉnh" />
							</th>
							<th colspan="7" class="right">
							   <a>Thêm thành viên</a>
							</th>
						</tr>
						<tr>
							<th>#</th>
							<th width="5"><input type="checkbox"/></th>
							<th>Họ tên</th>
							<th>Tên đăng nhập</th>
							<th>Logged In</th>
							<th>Email</th>
							<th>Nhóm</th>
							<th>Edit</th>
							<th>Last Visit</th>																
							<th>ID</th>					
						</tr>					
					</thead>
					<tbody>
						<tr class="odd gradeX">							
							<td class="center">1</td>
							<td><input type="checkbox"/></td>
							<td class="center">Nguyễn Ngọc Linh</td>
							<td class="center">linhnn</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Logged" /></td>
							<td class="center">linhvt22@gmail.com</td>
							<td class="center">Quản trị</td>
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<a>Xem</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /><img src="<?php echo $this->dirImg; ?>/NoiBat_1.jpg" title="Nổi bật" /></td>
							<td class="center">08/11/2010</td>														
							<td class="center">1</td>
						</tr>
						
						<tr class="even gradeC">							
							<td class="center">2</td>
							<td><input type="checkbox"/></td>
							<td class="center">Nguyễn Thanh Hải</td>
							<td class="center">haint</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Logged" /></td>
							<td class="center">haivt@gmail.com</td>
							<td class="center">Quản trị</td>
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<a>Xem</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /><img src="<?php echo $this->dirImg; ?>/NoiBat_1.jpg" title="Nổi bật" /></td>
							<td class="center">08/11/2010</td>														
							<td class="center">2</td>
						</tr>												
					</tbody>
				</table>																																	
			</div>
		</div>
	</div><!--  end #content -->