<section id="hot-news" class="info1">
	<ul class="tabs">
		<li><a href="#tab1-news">Tin nóng</a></li>
		<li><a href="#tab2-news">Tin đọc nhiều nhất</a></li>                      
	</ul>
						
	<hgroup class="tab_container">
		<article id="tab1-news" class="tab_content">
			<ul class="block">                    				              		
				<li>
					<ul>                    			
						<?php 
							foreach ($hotNews as $new):
								$alias = $this->categoryMapper->getAliasByArticle($new->id);
								$link = 'aliasP/' . $alias['parent_alias'] . '/aliasS/' . $alias['sub_alias'] . '/alias/' . $new->alias;
						?>
							
							<li>
								<a href="news/index/detail/<?php echo $link;?>">
									<?php echo $new->title;?>
								</a>
							</li>
						<?php endforeach ?>						
					</ul>
				</li>
			</ul>	                                	
		</article>
		<article id="tab2-news" class="tab_content">
			<ul class="block">                    				                    			
				<li>
					<ul>                    			
						 <?php 
						 	foreach ($topNews as $new):
						 		$alias = $this->categoryMapper->getAliasByArticle($new->id);
								$link = 'aliasP/' . $alias['parent_alias'] . '/aliasS/' . $alias['sub_alias'] . '/alias/' . $new->alias;
						 ?>
							<li>
								<a href="news/index/detail/<?php echo $link;?>">
									<?php echo $new->title;?>
								</a>
							</li>
						<?php endforeach ?>                   				
					</ul>
				</li>
			</ul>                                	
		</article>                           
	</hgroup>                                    
</section>

<div class="clear"></div>  