<section id="hot-news" class="info1">
	<ul class="tabs">
		<li><a href="#tab1-news">Tin nóng</a></li>
		<li><a href="#tab2-news">Tin đọc nhiều nhất</a></li>                      
	</ul>
						
	<hgroup class="tab_container">
		<article id="tab1-news" class="tab_content">
			<ul class="block">                    				              		
				<li>
					<ul>                    			
						<li><a>RAL: đà tăng liệu có được duy trì?</a></li>
						<li><a>Top 10 IPO lớn nhất trong năm 2010 </a></li>                    						                    			                   		
						<li><a>29/10: Bản tin cuối giờ giao dịch</a></li>
						<li><a>29/10: khối ngoại giảm mua ròng ở HoSE, bán ròng ở HNX</a></li>
						<li><a>ASM: Quyết định tăng vốn lên 401,4 tỷ đồng? </a></li>    
						<li><a>Chứng khoán châu Á mất điểm tuần thứ hai liên tục</a></li>
						<li><a>HBC: đầu tư dự án tại Nhà Bè và triển khai ép cọc khu chung cư Bình An</a></li>                				
					</ul>
				</li>
			</ul>	                                	
		</article>
		<article id="tab2-news" class="tab_content">
			<ul class="block">                    				                    			
				<li>
					<ul>                    			
						<li><a>Lãi suất liên ngân hàng tăng mạnh - BVSC  ( 27/10/2010).</a></li>
						<li><a>Chỉ số CPI theo năm đang có xu hướng tăng nhanh trong khi tốc độ tăng theo tháng tiếp tục vượt 1% - HSC  ( 27/10/2010).</a></li>
						<li><a>CPI Tháng 10 và Lạm phát lõi - LVS  ( 27/10/2010).</a></li>
						<li><a>Báo cáo phân tích CTCP Kỹ thuật điện Toàn Cầu - AVSC  ( 27/10/2010).</a></li>                    				
					</ul>
				</li>
			</ul>                                	
		</article>                           
	</hgroup>                                    
</section>

<div class="clear"></div>  