<script type="text/javascript" language="JavaScript" src="http://vnexpress.net/Service/Forex_Content.js"></script>
<section id="money-info">
		<p id="money">Tỷ giá</p>  
		<hgroup id="money-table">                      
			<table width="92%" border="0px" cellspacing="0" cellpadding="0">                           
				<tbody>
					<script type="text/javascript" language="JavaScript">
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[0] + " </td><td align=right>" + vCosts[0] + " </td></tr>");
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[1] + " </td><td align=right>" + vCosts[1] + " </td></tr>");
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[2] + " </td><td align=right>" + vCosts[2] + "</td></tr>");
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[3] + " </td><td align=right> " + vCosts[3] + "</td></tr>");
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[4] + "</td><td align=right> " + vCosts[4] + "</td></tr>");
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[5] + "</td><td align=right> " + vCosts[5] + "</td></tr>");
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[6] + "</td><td align=right> " + vCosts[6] + "</td></tr>");
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[7] + " </td><td align=right> " + vCosts[7] + "</td></tr>");
                    	document.write("<tr><td align='Left'>&nbsp;" + vForexs[8] + "</td><td align=right>" + vCosts[8] + "</td></tr>");
                	</script>						
				</tbody>
			</table>
		</hgroup>										
</section>

 <section id="theme-select">
 		<h2 class="sidebar-header">Theme</h2>		
		<div class="theme-icon">
			<img val="3" src="<?php echo $this->dirImg ?>/icon/theme-default.png" title="Theme mặc định" />
			<img val="10" src="<?php echo $this->dirImg ?>/icon/theme-noel.png" title="Theme Noel" />
		</div>
</section>