<article class="statics-box">
	<h2>Bảng xếp hạng thành viên</h2>
	<p>Tháng :10/2010</p>
	<table width="100%" cellpadding="0" cellspacing="0">
		<thead>
			<tr>
				<td align="left">Hạng</td>
				<td align="center">Nhà đầu tư</td>
				<td align="center">Tổng tiền</td>
				<td align="center">Số dư đầu kỳ</td>
				<td align="right">Tỷ suất sinh lợi</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td align="left">1</td>
				<td align="center">linhnn</td>
				<td align="center">1,159,001,701</td>
				<td align="center">1,000,000,000</td>
				<td align="right">15.90%</td>
			</tr>



		</tbody>
	</table>
</article>     