<article class="statics-box">
	<h2>Bảng xếp hạng thành viên</h2>
	<p>Tháng :10/2010</p>
	<table width="100%">
		<thead>
			<tr>
				<td>Hạng</td>
				<td>Nhà đầu tư</td>
				<td>Tổng tiền</td>
				<td>Số dư đầu kỳ</td>
				<td>Tỷ suất sinh lợi</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td align="center">1</td>
				<td align="left">linhnn</td>
				<td align="right">1,159,001,701</td>
				<td align="right">1,000,000,000</td>
				<td align="right">15.90%</td>
			</tr>
			<tr>
				<td align="center">2</td>
				<td align="left">phucdd</td>
				<td align="right">1,151,570,615</td>
				<td align="right">1,000,000,000</td>
				<td align="right">15.16%</td>
			</tr>
			<tr>
				<td align="center">3</td>
				<td align="left">phuongtp</td>
				<td align="right">1,644,453,121</td>
				<td align="right">1,440,853,121</td>
				<td align="right">14.13%</td>
			</tr>
			<tr>
				<td align="center">4</td>
				<td align="left">nghiepth</td>
				<td align="right">1,466,915,455</td>
				<td align="right">1,285,315,455</td>
				<td align="right">14.13%</td>
			</tr>
			<tr>
				<td align="center">1</td>
				<td align="left">linhnn</td>
				<td align="right">1,159,001,701</td>
				<td align="right">1,000,000,000</td>
				<td align="right">15.90%</td>
			</tr>
			<tr>
				<td align="center">2</td>
				<td align="left">phucdd</td>
				<td align="right">1,151,570,615</td>
				<td align="right">1,000,000,000</td>
				<td align="right">15.16%</td>
			</tr>
			<tr>
				<td align="center">3</td>
				<td align="left">phuongtp</td>
				<td align="right">1,644,453,121</td>
				<td align="right">1,440,853,121</td>
				<td align="right">14.13%</td>
			</tr>
			<tr>
				<td align="center">4</td>
				<td align="left">nghiepth</td>
				<td align="right">1,466,915,455</td>
				<td align="right">1,285,315,455</td>
				<td align="right">14.13%</td>
			</tr>
			<tr>
				<td align="center">1</td>
				<td align="left">linhnn</td>
				<td align="right">1,159,001,701</td>
				<td align="right">1,000,000,000</td>
				<td align="right">15.90%</td>
			</tr>
			<tr>
				<td align="center">2</td>
				<td align="left">phucdd</td>
				<td align="right">1,151,570,615</td>
				<td align="right">1,000,000,000</td>
				<td align="right">15.16%</td>
			</tr>
			<tr>
				<td align="center">3</td>
				<td align="left">phuongtp</td>
				<td align="right">1,644,453,121</td>
				<td align="right">1,440,853,121</td>
				<td align="right">14.13%</td>
			</tr>
			<tr>
				<td align="center">4</td>
				<td align="left">nghiepth</td>
				<td align="right">1,466,915,455</td>
				<td align="right">1,285,315,455</td>
				<td align="right">14.13%</td>
			</tr>
			<tr>
				<td align="center">1</td>
				<td align="left">linhnn</td>
				<td align="right">1,159,001,701</td>
				<td align="right">1,000,000,000</td>
				<td align="right">15.90%</td>
			</tr>
			<tr>
				<td align="center">2</td>
				<td align="left">phucdd</td>
				<td align="right">1,151,570,615</td>
				<td align="right">1,000,000,000</td>
				<td align="right">15.16%</td>
			</tr>
			<tr>
				<td align="center">3</td>
				<td align="left">phuongtp</td>
				<td align="right">1,644,453,121</td>
				<td align="right">1,440,853,121</td>
				<td align="right">14.13%</td>
			</tr>
			<tr>
				<td align="center">4</td>
				<td align="left">nghiepth</td>
				<td align="right">1,466,915,455</td>
				<td align="right">1,285,315,455</td>
				<td align="right">14.13%</td>
			</tr>
		</tbody>
	</table>
</article>     