<article class="statics-box box-first">
	<h2>Thống kê khối lượng giao dịch trong ngày</h2>
	<p>Tháng :10/2010</p>
	<table width="100%" cellpadding="0" cellspacing="0">
		<thead>
			<tr>
				<td align="left">Mã CK</td>
				<td align="center">Giá Trần</td>
				<td align="center">Giá Sàn</td>
				<td align="center">Giá TC</td>
				<td align="center">SL Khớp</td>
				<td align="right">Giá Trị</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td align="left">ASM</td>
				<td align="center">59,500</td>
				<td align="center">54,500</td>
				<td align="center">57,000</td>
				<td align="center">10,000</td>
				<td align="right">569,900,000</td>
			</tr>
			<tr>
				<td align="left">ASM</td>
				<td align="center">59,500</td>
				<td align="center">54,500</td>
				<td align="center">57,000</td>
				<td align="center">10,000</td>
				<td align="right">569,900,000</td>
			</tr>
			<tr>
				<td align="left">ASM</td>
				<td align="center">59,500</td>
				<td align="center">54,500</td>
				<td align="center">57,000</td>
				<td align="center">10,000</td>
				<td align="right">569,900,000</td>
			</tr>
			<tr>
				<td align="left">ASM</td>
				<td align="center">59,500</td>
				<td align="center">54,500</td>
				<td align="center">57,000</td>
				<td align="center">10,000</td>
				<td align="right">569,900,000</td>
			</tr>									
		</tbody>
	</table>
</article>