<p class="stick">Giao dịch</p>
<table class="menu_style">
	<tr>
		<?php 
			foreach ($this->items as $item) {
				$class = ($item->alias == 'danh-muc-dau-tu') ? "black" : "";	
		?>
		<td>
			<a class="<?php echo $class ?>" href="<?php echo $item->link ?>">
				<?php echo $item->name ?>
			</a></td>
		<td>&nbsp;|&nbsp;</td>
		<?php } ?>	
	</tr>	
</table><br/>

<?php if (isset($this->message)) {?>
	<div class="warning2">
		<?php echo $this->message; ?>
	</div>					
<?php } ?>

<form method="post" action="">
	<table class="trading_table" cellpadding="5">	
		<tr><td class="trade_header"><span>Danh mục đầu tư</span></td></tr>
		<tr>
			<td>
				<span class="title">Tài khoản:</span>
				<span class="pink"><?php echo $_SESSION['player_name'] ?></span>
			</td>		
		</tr>
		<tr>
			<td class="trade_content">
				<table cellpadding="0" cellspacing="0">
					<tr valign="middle" class="header_td_20">
			            <td align="center" rowspan="2" class="cell_item" style="width: 8%;">Mã CK</td>
			            <td align="center" rowspan="2" class="cell_item" style="width: 10%;">Giá bình quân</td>
			            <td align="center" rowspan="2" class="cell_item" style="width: 10%;">Giá hiện tại</td>
			            <td align="center" class="cell_item" style="width: 17%;">Thay đổi</td>
			            <td align="center" rowspan="2" class="cell_item" style="width: 9%;">SL chờ về</td>
			            <td align="center" rowspan="2" class="cell_item" style="width: 8%;">Số lượng</td>
			            <td align="center" class="cell_item" style="width: 23%;">Chênh lệch vốn</td>
			            <td align="center" rowspan="2" class="cell_item" style="width: 15%;">Giá trị thị trường</td>
		            </tr>
		            <tr valign="middle" class="header_td_bottom_20">
			            <td align="center" class="cell_item">
				            <table width="100%" cellspacing="0" cellpadding="0" border="0">
					            <tr>
						            <td align="center" style="width: 50%;">$</td>
						            <td align="center" style="width: 50%;">%</td>
					            </tr>
				            </table>
			            </td>
			            <td align="center" class="cell_item">
				            <table width="100%" cellspacing="0" cellpadding="0" border="0">
					            <tr>
						            <td align="center" style="width: 50%;">$</td>
						            <td align="center" style="width: 50%;">%</td>
					            </tr>
				            </table>
			            </td>
		            </tr>  
	       		    <tr class="text_grid_item_2" style="height: 20px;">
		                <td class="cell_item"><a>AGR</a></td>
		                <td align="right" class="cell_item">
			                <span>11,500</span></td>   
		                <td align="right" class="cell_item"><span>13,700</span></td>
		                <td align="center" class="cell_item">
			                <table width="100%" cellspacing="0" cellpadding="0" border="0">
				                <tbody><tr>
					                <td align="right" style="width: 50%;">
						                <span><font color="green">+2,200</font></span></td>
					                <td align="right" style="width: 50%;">
						                <span><font color="green">+19.13%</font></span></td>
				                </tr>
			                </tbody></table>
		                </td>
		                <td align="right" class="cell_item">
			                <span>0</span>
			            </td>
		                <td align="right" class="cell_item">
			                <span>100</span></td>
		                <td align="center" class="cell_item">
			                <table width="100%" cellspacing="0" cellpadding="0" border="0">
				                <tbody><tr>
					                <td align="right" style="width: 60%;">
						                <span><font color="green">+220,000</font></span></td>
					                <td align="right" style="width: 40%;">
						                <span><font color="green">+19.13%</font></span></td>
				                </tr>
			                </tbody></table>
		                </td>
		                <td align="right" class="cell_item">
			                <span id="ctl00_cphMainContent_scrDanhMuc_rptShowdata_ctl01_lblgiathitruong">1,370,000</span>
			            </td>
                	</tr>   
	       		    <tr class="text_grid_Alternate_item" style="height: 20px;">
		                <td class="cell_item"><a>AGR</a></td>
		                <td align="right" class="cell_item">
			                <span>11,500</span></td>   
		                <td align="right" class="cell_item"><span>13,700</span></td>
		                <td align="center" class="cell_item">
			                <table width="100%" cellspacing="0" cellpadding="0" border="0">
				                <tbody><tr>
					                <td align="right" style="width: 50%;">
						                <span><font color="green">+2,200</font></span></td>
					                <td align="right" style="width: 50%;">
						                <span><font color="green">+19.13%</font></span></td>
				                </tr>
			                </tbody></table>
		                </td>
		                <td align="right" class="cell_item">
			                <span>0</span>
			            </td>
		                <td align="right" class="cell_item">
			                <span>100</span></td>
		                <td align="center" class="cell_item">
			                <table width="100%" cellspacing="0" cellpadding="0" border="0">
				                <tbody><tr>
					                <td align="right" style="width: 60%;">
						                <span><font color="green">+220,000</font></span></td>
					                <td align="right" style="width: 40%;">
						                <span><font color="green">+19.13%</font></span></td>
				                </tr>
			                </tbody></table>
		                </td>
		                <td align="right" class="cell_item">
			                <span id="ctl00_cphMainContent_scrDanhMuc_rptShowdata_ctl01_lblgiathitruong">1,370,000</span>
			            </td>
                	</tr>  
	       		    <tr class="text_grid_item_2" style="height: 20px;">
		                <td class="cell_item"><a>AGR</a></td>
		                <td align="right" class="cell_item">
			                <span>11,500</span></td>   
		                <td align="right" class="cell_item"><span>13,700</span></td>
		                <td align="center" class="cell_item">
			                <table width="100%" cellspacing="0" cellpadding="0" border="0">
				                <tbody><tr>
					                <td align="right" style="width: 50%;">
						                <span><font color="green">+2,200</font></span></td>
					                <td align="right" style="width: 50%;">
						                <span><font color="green">+19.13%</font></span></td>
				                </tr>
			                </tbody></table>
		                </td>
		                <td align="right" class="cell_item">
			                <span>0</span>
			            </td>
		                <td align="right" class="cell_item">
			                <span>100</span></td>
		                <td align="center" class="cell_item">
			                <table width="100%" cellspacing="0" cellpadding="0" border="0">
				                <tbody><tr>
					                <td align="right" style="width: 60%;">
						                <span><font color="green">+220,000</font></span></td>
					                <td align="right" style="width: 40%;">
						                <span><font color="green">+19.13%</font></span></td>
				                </tr>
			                </tbody></table>
		                </td>
		                <td align="right" class="cell_item">
			                <span id="ctl00_cphMainContent_scrDanhMuc_rptShowdata_ctl01_lblgiathitruong">1,370,000</span>
			            </td>
                	</tr>   
	       		    <tr class="text_grid_Alternate_item" style="height: 20px;">
		                <td class="cell_item"><a>AGR</a></td>
		                <td align="right" class="cell_item">
			                <span>11,500</span></td>   
		                <td align="right" class="cell_item"><span>13,700</span></td>
		                <td align="center" class="cell_item">
			                <table width="100%" cellspacing="0" cellpadding="0" border="0">
				                <tbody><tr>
					                <td align="right" style="width: 50%;">
						                <span><font color="green">+2,200</font></span></td>
					                <td align="right" style="width: 50%;">
						                <span><font color="green">+19.13%</font></span></td>
				                </tr>
			                </tbody></table>
		                </td>
		                <td align="right" class="cell_item">
			                <span>0</span>
			            </td>
		                <td align="right" class="cell_item">
			                <span>100</span></td>
		                <td align="center" class="cell_item">
			                <table width="100%" cellspacing="0" cellpadding="0" border="0">
				                <tbody><tr>
					                <td align="right" style="width: 60%;">
						                <span><font color="green">+220,000</font></span></td>
					                <td align="right" style="width: 40%;">
						                <span><font color="green">+19.13%</font></span></td>
				                </tr>
			                </tbody></table>
		                </td>
		                <td align="right" class="cell_item">
			                <span id="ctl00_cphMainContent_scrDanhMuc_rptShowdata_ctl01_lblgiathitruong">1,370,000</span>
			            </td>
                	</tr>  	                   	                	                	              	     	            			    
			    </table>
			</td>						
		</tr>
		<tr>
			<td align="center" class="trade_content">
    			<table style="width: 70%;">
       				<tr>
            			<td align="left" colspan="3">
                			<span class="title">Vốn đầu tư:</span>&nbsp;
                			<span class="pink">0 VNĐ</span>
            			</td>
            			<td align="left" colspan="3">
			                <span class="title">Giá trị thực:</span>&nbsp;
                			<span class="pink">0 VNĐ</span>
            			</td>
        			</tr>
    			</table>
			</td>
		</tr>	
		<tr>
			<td height="10px"></td>
		</tr>
		<tr>
			<td align="right" style="padding-right: 30px;" class="trade_content">
			    <table cellspacing="0" cellpadding="0" border="0">
	            <tr>
			        <td class="adv_top_left"></td>
			        <td class="adv_top_center"></td>
			        <td class="adv_top_right"></td>
		        </tr>
	            <tr>
	                <td class="adv_left">&nbsp;</td>
	                <td align="center" style="background-color: rgb(255, 255, 255);">
	                    <table width="100%" cellspacing="0" cellpadding="0" style="vertical-align: top;">
	                        <tr style="height: 3px;"><td></td></tr>
	                        <tr style="height: 25px;">
	                            <td align="left">
	                                <span class="title">Số dư tiền mặt: </span>
	                            </td>
	                            <td style="width: 5px;"></td>
	                            <td align="right">
	                                <span class="money">1,000,000,000 VNĐ</span>
	                            </td>
	                        </tr>
	                        <tr style="height: 25px;">
	                            <td align="left">
	                                <span class="title">Tiền bán chứng khoán chưa về: </span>
	                            </td>
	                            <td style="width: 5px;"></td>
	                            <td align="right">
	                                <span class="money">0 VNĐ</span>
	                            </td>
	                        </tr>
	                        <tr style="height: 25px;">
	                            <td align="left">
	                                <span class="title">Tổng giá trị cổ phiếu: </span>
	                            </td>
	                            <td style="width: 5px;"></td>
	                            <td align="right">
	                                <span class="money">0 VNĐ</span>
	                            </td>
	                        </tr>
	                        <tr>
	                            <td colspan="5"><hr style="color: Gray;"></td>
	                        </tr>
	                        <tr style="height: 25px;">
	                            <td align="right">
	                                <span class="title">Tổng giá trị tài sản: </span>
	                            </td>
	                            <td style="width: 5px;"></td>
	                            <td align="right">
	                                <span class="sum">1,000,000,000 VNĐ</span>
	                            </td>
	                        </tr>
	                    </table>
	                </td>
	                <td class="adv_right">&nbsp;</td>
		        </tr>
		        <tr>
			        <td class="adv_bottom_left"></td>
			        <td class="adv_bottom_center"></td>
			        <td class="adv_bottom_right"></td>
		        </tr>
		        <tr style="height: 3px;"><td colspan="3"></td></tr>
	        </tbody></table>
			</td>
	</tr>
	<tr>
		<td height="10px"></td>
	</tr>			
	</table>
</form>