<p class="stick">Giao dịch</p>
<table class="menu_style">
	<tr>
		<?php 
			foreach ($this->items as $item) {
				$class = ($item->alias == 'lenh-da-khop') ? "black" : "";	
		?>
		<td>
			<a class="<?php echo $class ?>" href="<?php echo $item->link ?>">
				<?php echo $item->name ?>
			</a></td>
		<td>&nbsp;|&nbsp;</td>
		<?php } ?>		
	</tr>	
</table><br/>

<?php if (isset($this->message)) {?>
	<div class="warning2">
		<?php echo $this->message; ?>
	</div>					
<?php } ?>

<form method="post" action="">
	<table class="trading_table" cellpadding="5">	
		<tr><td class="trade_header" colspan="4"><span>Danh sách lệnh đã khớp</span></td></tr>
		<tr>
			<td colspan="3">
				<span class="title">Tài khoản:</span>
				<span class="pink"><?php echo $_SESSION['player_name'] ?></span>
			</td>		
		</tr>
		<tr>
			<td>
				<span class="title">Lệnh</span>
				<select class="select">
					<option>...</option>
					<option>ATO</option>
					<option>ATC</option>
					<option>LIMIT</option>
				</select>
			</td>	
			<td>
				<span class="title">Mã CK</span>
				<select class="select">
					<option>AAM</option>
					<option>ABT</option>
				</select>			
			</td>	
			<td></td>		
		</tr>
		<tr>
			<td style="width: 181px; height: 24px;">
				<span class="title">Từ ngày</span>
				<input type="text" class="datepicker input_trading" size="7" maxlength="14" />				
			</td>	
			<td style="width: 181px; height: 24px;">
				<span class="title">Đến	 ngày</span>
				<input type="text" class="datepicker input_trading" size="7" maxlength="14" />				
			</td>		
			<td style="height: 24px;">
				<input type="submit" name="btnSubmit" class="Btn" value="Tìm kiếm" />
			</td>			
		</tr>
		<tr>
			<td height="10px"></td>
		</tr>	
		<tr>
			<td class="statics-box3" colspan="3">
				<table id="report" width="100%" cellpadding="0" cellspacing="0">
					<thead class="first">
						<tr>
							<td align="left">STT</td>
							<td align="left">Ngày GD</td>
							<td align="center">Mã Lệnh</td>
							<td align="center">Chứng khoán</td>
							<td align="center">Mua/Bán</td>
							<td align="right">Giá đặt</td>
							<td align="right">Khối lượng</td>
						</tr>
					</thead>
					<tbody>
						<tr class="odd first">
							<td align="left" class="arrow">1</td>
							<td align="left">12/11/2010 10:50</td>
							<td align="center">101018</td>
							<td align="center">AGR</td>
							<td align="center">Mua</td>
							<td align="right">0</td>
							<td align="right">0</td>
						</tr>
						<tr class="even">
							<td colspan="7">
								<table width="100%" cellpadding="0" cellspacing="0">
									<thead>
										<tr>
											<td class="sub-txt">Chi tiết lệnh đặt 101018</td>
										</tr>
										<tr class="sub-head">
											<td>Chi tiết lệnh đặt</td>
											<td>Loại lệnh</td>
											<td>Ngày giờ</td>
											<td>Số lượng khớp</td>
											<td>Giá khớp</td>
											<td>Phí môi giới</td>
										</tr>	
									</thead>	
									<tbody>
										<tr class="sub-data">
											<td>Mua 100 AGR</td>
											<td>ATO</td>
											<td>12/11/10 10:50:48</td>
											<td>100</td>
											<td>11,500</td>
											<td>0.3</td>
										</tr>
									</tbody>							
								</table>
							</td>
						</tr>
						<tr class="odd first">
							<td align="left" class="arrow">1</td>
							<td align="left">12/11/2010 10:50</td>
							<td align="center">101018</td>
							<td align="center">AGR</td>
							<td align="center">Mua</td>
							<td align="right">0</td>
							<td align="right">0</td>
						</tr>
						<tr class="even">
							<td colspan="7">
								<table width="100%" cellpadding="0" cellspacing="0">
									<thead>
										<tr>
											<td class="sub-txt">Chi tiết lệnh đặt 101018</td>
										</tr>
										<tr class="sub-head">
											<td>Chi tiết lệnh đặt</td>
											<td>Loại lệnh</td>
											<td>Ngày giờ</td>
											<td>Số lượng khớp</td>
											<td>Giá khớp</td>
											<td>Phí môi giới</td>
										</tr>	
									</thead>	
									<tbody>
										<tr class="sub-data">
											<td>Mua 100 AGR</td>
											<td>ATO</td>
											<td>12/11/10 10:50:48</td>
											<td>100</td>
											<td>11,500</td>
											<td>0.3</td>
										</tr>
									</tbody>							
								</table>
							</td>
						</tr>						
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td align="right" colspan="3">
				Trang
				<select>
					<option>1</option>
					<option>2</option>
					<option>3</option>
				</select>	
				/3		
			</td>
		</tr>
	</table>
</form>