	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item component">
				<h4>Thêm component</h4>
				<div class="float-right">
					<a href="<?php echo $_SESSION['temp']; ?>"><input type="button" id="close" value="Đóng" /></a>							
				</div>				
			</div>
			
			<div class="portlet-content">
				<?php if (isset($this->message)) {?>
					<div class="message">
						<?php echo $this->message; ?>
					</div>					
				<?php } ?>
				<?php echo $this->form;  ?>																																			
			</div><!--  end .portlet-content -->
		</div>
	</div><!--  end #content -->