<div id="content" class="xfluid">

		<div class="portlet x12">
				
				<div class="portlet-content">
					<div id="big_stats" class="clearfix">
					<div class="stat">
						
						<h4>Pending Sales Today</h4>
						<span class="value">12</span>
						<span class="view_all"><a href="javascript:;">View All Pending Sales</a></span>

						
					</div>
					
					<div class="stat">
						
						<h4>Completed Sales Today</h4>
						<span class="value">23</span>
						<span class="view_all"><a href="javascript:;">View All Completed Sales</a></span>
						
					</div>
					
					<div class="stat">

						
						<h4>Returned Items Today</h4>
						<span class="value">2</span>
						<span class="view_all"><a href="javascript:;">View Returned Items</a></span>
						
					</div>
				</div>
			</div> <!-- .portlet-content -->
			</div> <!-- .portlet -->
		
		<div class="portlet x6">
			
			<div class="portlet-header">
				<h4>Sales Report</h4>
				
				<ul class="portlet-tab-nav">
					<li class="portlet-tab-nav-active"><a href="#tab1" class="tooltip" title="Week To Date.">WTD</a></li>	
				</ul>
			</div> <!-- .portlet-header -->

			
			
			<div class="portlet-content">				
				<div id="tab1" class="portlet-tab-content portlet-tab-content-active">
					<table class="stats" title="bar" width="100%" cellpadding="0" cellspacing="0">
						<caption>2009/2010 Sales by industry (Million)</caption>
						<thead>
							<tr>
								<td class="no_input">&nbsp;</td>
								<th>Banking</th>
								<th>Beauty</th>

								<th>Insurance</th>
								<th>Internet</th>
								<th>Media</th>
							</tr>

						</thead>
						
						<tbody>
							<tr>
								<th>2009</th>
								<td>5</td>
								<td>6</td>
								<td>4</td>
								<td>7</td>
								<td>9</td>
							</tr>
							
							<tr>
								<th>2010</th>
								<td>12</td>
								<td>15</td>
								<td>13</td>
								<td>11</td>
								<td>13</td>
							</tr>	
						</tbody>
					</table>

				</div> <!-- .portlet-tab-content -->
				
			</div> <!-- .portlet-content -->			
		</div> <!-- .portlet -->
		
		
		
		
		<div class="portlet x6">
			
			<div class="portlet-header">
				<h4>Sales Report</h4>
				
				<ul class="portlet-tab-nav">
					<li class="portlet-tab-nav-active"><a href="#tab4" class="tooltip" title="Week To Date.">WTD</a></li>
				</ul>
			</div> <!-- .portlet-header -->
			
			<div class="portlet-content">				
				<div id="tab4" class="portlet-tab-content portlet-tab-content-active">
					<table class="stats" title="area" width="100%" cellpadding="0" cellspacing="0">
						<caption>2009/2010 Sales by industry (Million)</caption>
						<thead>
							<tr>
								<td class="no_input">&nbsp;</td>
								<th>Banking</th>
								<th>Beauty</th>

								<th>Insurance</th>
								<th>Internet</th>
								<th>Media</th>
							</tr>

						</thead>
						
						<tbody>
							<tr>
								<th>2009</th>
								<td>12</td>
								<td>15</td>
								<td>13</td>
								<td>11</td>
								<td>13</td>
							</tr>
							
							<tr>
								<th>2010</th>
								
								<td>5</td>
								<td>6</td>
								<td>4</td>
								<td>7</td>
								<td>9</td>
							</tr>	
						</tbody>
					</table>

				</div> <!-- .portlet-tab-content -->
				
			</div> <!-- .portlet-content -->			
		</div> <!-- .portlet -->
		
		<div class="xbreak"></div> <!-- .xbreak -->

		
		<div class="portlet x4">
			<div class="portlet-header"><h4>Referers</h4></div>
			
			<div class="portlet-content">
				<table class="reports_table">
					
					<tr>
						<td class="description"><a href="http://google.com/">http://google.com</a></td>
						<td class="value"><span>1123</span></td>
					</tr>
					<tr>
						<td class="description"><a href="http://yahoo.com/">http://yahoo.com</a></td>
						<td class="value"><span>927</span></td>
					</tr>
					<tr>
						<td class="description"><a href="http://themeforest.net/">http://themeforest.net</a></td>
						<td class="value"><span>834</span></td>
					</tr>
					<tr>
						<td class="description"><a href="http://codecanyon.net/">codecanyon.net</a></td>
						<td class="value"><span>625</span></td>
					</tr>
					<tr>
						<td class="description"><a href="http://madebyamp.com/">http://madebyamp.com</a></td>
						<td class="value"><span>593</span></td>
					</tr>
					
				</table>
			</div>
		</div>
		
		
		<div class="portlet x4">
			<div class="portlet-header"><h4>Most Visited Pages</h4></div>
			
			<div class="portlet-content">
				<table class="reports_table">
					
					<tr>
						<td class="description"><a href="javascript:;">Carbon Admin</a></td>
						<td class="value"><span>1123</span></td>
					</tr>
					<tr>
						<td class="description"><a href="javascript:;">Mega Dropdown</a></td>
						<td class="value"><span>927</span></td>
					</tr>
					<tr>
						<td class="description"><a href="javascript:;">DropUI Buttons</a></td>
						<td class="value"><span>834</span></td>
					</tr>
					<tr>
						<td class="description"><a href="javascript:;">Azure Admin</a></td>
						<td class="value"><span>625</span></td>
					</tr>
					<tr>
						<td class="description"><a href="javascript:;">NoticeUI</a></td>
						<td class="value"><span>593</span></td>
					</tr>
					
				</table>
			</div>
		</div>
		
		
		<div class="portlet x4">
			<div class="portlet-header"><h4>Browser</h4></div>
			
			<div class="portlet-content">
				<table  class="reports_table">
					
					<tr>
						<td class="description">Firefox</td>
						<td class="value"><span>1123</span></td>
					</tr>
					<tr>
						<td class="description">Chrome</td>
						<td class="value"><span>927</span></td>
					</tr>
					<tr>
						<td class="description">Internet Explorer</td>
						<td class="value"><span>834</span></td>
					</tr>
					<tr>
						<td class="description">Safari</td>
						<td class="value"><span>625</span></td>
					</tr>
					<tr>
						<td class="description">Opera</td>
						<td class="value"><span>593</span></td>
					</tr>
					
				</table>
			</div>
		</div>
	


	</div> <!-- #content -->