	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header"><h4>Danh sách chứng khoán</h4></div>
			
			<div class="portlet-content">												
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
						<tr>
							<th>#</th>
							<th width="5"><input type="checkbox"/></th>	
							<th>Title</th>										
						</tr>
					</thead>
					<tbody>
						<tr class="odd gradeX">							
							<td class="center">1</td>
							<td><input type="checkbox" /></td> 
							<td class="center">ABC</td>							
						</tr>
						<tr class="even gradeC">							
							<td class="center">2</td>
							<td><input type="checkbox" /></td>
							<td class="center">FPT</td>							
						</tr>							
						</tr>											
					</tbody>
				</table>																																	
			</div>
		</div>
	</div><!--  end #content -->