<script type="text/javascript" language="JavaScript" src="http://vnexpress.net/Service/Gold_Content.js"></script>
<script type="text/javascript" language="JavaScript" src="http://vnexpress.net/Service/Forex_Content.js"></script>

<section id="gold-info" class="info2">
	<p id="gold" class="statics">Giá vàng 9999</p>
	<p class="right">ĐVT: tr.đ/lượng</p>
	<table width="92%" border="0px" cellspacing="0" cellpadding="0">
		<thead>
			<tr>
				<td>Loại</td>
				<td>Mua</td>
				<td>Bán</td>
			</tr>
		</thead>
		<tbody>
			<script type="text/javascript" language="JavaScript">
                   document.write("<tr><td>SBJ</td><td>" + vGoldSbjBuy + "</td><td>" + vGoldSbjSell + "</td></tr>");
                   document.write("<tr><td>SJC</td><td>" + vGoldSjcBuy + "</td><td>" + vGoldSjcSell + "</td></tr>");
			</script>			
		</tbody>
	</table>
</section>

<section id="money-info" class="info2">
	<p id="money" class="statics">Tỷ giá</p>  
	<hgroup id="money-table">                      
		<table width="92%" border="0px" cellspacing="0" cellpadding="0">                           
			<tbody>
				<script type="text/javascript" language="JavaScript">
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[0] + " </td><td align=right>" + vCosts[0] + " </td></tr>");
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[1] + " </td><td align=right>" + vCosts[1] + " </td></tr>");
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[2] + " </td><td align=right>" + vCosts[2] + "</td></tr>");
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[3] + " </td><td align=right> " + vCosts[3] + "</td></tr>");
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[4] + "</td><td align=right> " + vCosts[4] + "</td></tr>");
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[5] + "</td><td align=right> " + vCosts[5] + "</td></tr>");
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[6] + "</td><td align=right> " + vCosts[6] + "</td></tr>");
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[7] + " </td><td align=right> " + vCosts[7] + "</td></tr>");
                    document.write("<tr><td align='Left'>&nbsp;" + vForexs[8] + "</td><td align=right>" + vCosts[8] + "</td></tr>");
                </script>				
			</tbody>
		</table>
	</hgroup>										
</section>

<div class="clear"></div>