<?php 	
	if (isset($_SESSION['log']))
		header("location:http://" . $_SERVER['SERVER_NAME'] . "/admin/index/home");
	else {
?>
<style>
body { background: #263849; font: 12px/1.7em arial, sans-serif; }
</style>
<div id="login">
	
	<h1 id="title"><a href="#">Slate Admin</a></h1>
	
<div id="login-body" class="clearfix"> 

	         
	<form action="admin/index/home" name="login" id="login_form" method="post">
		
		
	                    <div class="content_front">

	        <div class="pad">
	        	
	        	<div class="field">
					<label>Username:</label>
					
					<div class=""><span class="input"><input name="email" id="login_email" class="text" type="text" value="admin" /></span></div>
				</div> <!-- .field -->
				
				<div class="field">
					<label>Password:</label>

					
					<div class=""><span class="input"><input name="password" id="login_password" class="text" type="password" value="password" /> 
						<a style="" href="javascript:;" id="forgot_my_password">Forgot password?</a></span></div>
				</div> <!-- .field -->
				
				<div class="checkbox">
					<span class="label">&nbsp;</span>
					
					<div class=""><input name="remember" id="remember" class="checkbox" value="yes" type="checkbox" /> &nbsp;&nbsp;<label style="display: inline;" for="remember">Remember me on this computer</label></div>
				</div> <!-- .field -->

				
				<div class="field">
					<span class="label">&nbsp;</span>
					
					<div class=""><button type="submit" class="btn">Login</button></div>
				</div> <!-- .field -->
		

	        </div>
	    </div>

		
	</form>

</div>

</div> <!-- #login -->
<?php } ?>