<section id="news-info">                    
	<ul class="tabs">
		<li><a href="#tab1-news">Điểm tin UITStock</a></li>
		<li><a href="#tab2-news">Báo cáo phân tích</a></li>
		<li><a href="#tab3-news">Lịch sự kiện</a></li>
	</ul>
	
	<hgroup class="tab_container">
		<article id="tab1-news" class="tab_content">
			<ul class="block">                    				              		
				<li>
					<ul>     
						<?php foreach ($stockNews as $new ) { ?>               			
							<li><a><?php echo $new['title'] ?></a></li>
						<?php } ?>		                    				
					</ul>
				</li>
			</ul>				
		</article>
		<article id="tab2-news" class="tab_content">
			<ul class="block">                    				                    			
				<li>
					<ul>          
						<?php foreach ($reports as $report ) { ?>               			
							<li><a href="files/upload/files/report/<?php echo $report['summarize'] ?>"><?php echo $report['title'] ?></a></li>
						<?php } ?>					          			                    				
					</ul>
				</li>
			</ul>			
		</article>
		<article id="tab3-news" class="tab_content">
		   <ul class="block">
		   		<?php foreach ($dates as $date):  ?>
		   			<li class="date"><?php echo $date['date'] ?>:</li>		   		 
			   		<li><ul>  
							<?php					
					   			foreach ($events as $event ):
					   				if ($event['summarize'] == $date['date']) {						   						   					
					   		?>               			
								<li><a><?php echo $event['title'] ?></a></li>
							<?php }  endforeach ?>
					</ul></li>
				<?php endforeach ?>				                  															
			</ul>	                    		
		</article>
	</hgroup>
</section>