	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item template">
				<h4>Quản lý template</h4>
				<div class="float-right">	
				   <div class="global" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>"></div>																								
					<a class="minibutton btn add" path="admin/template/add/">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="template" path="admin/template/edit" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>
					<a class="minibutton btn default" name="template" path="admin/template/set-default-template">
						<span><span class="icon default"></span>Mặc định</span>
					</a>
					<a class="minibutton btn delete" name="template" path="admin/template/delete">
						<span><span class="icon delete"></span>Xóa</span>
					</a>					
				</div>				
			</div>
			
			<div class="portlet-content">				 			
				<div class="cat">	
					<?php $i = 0;foreach ($this->components as $component): $i++;?>
							<?php if ($this->c == $component->id) { ?>	
								<a class="active" href="admin/template/list/component/<?php echo $component->id; ?>/" order="<?php echo $component->ordering; ?>">
									<span><?php echo $this->escape($component->name); ?></span>
								</a>							
							<?php } else { ?>				    	
							<a class="minibutton" href="admin/template/list/component/<?php echo $component->id; ?>/" order="<?php echo $component->ordering; ?>">
								<span><?php echo $this->escape($component->name); ?></span>
							</a>			
							<?php } ?>							
					<?php endforeach ?>
                </div><!-- end .cat -->
                														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/template/auto-suggestion-template" component="<?php echo $this->c; ?>" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" value="Tìm kiếm" name="name" class="btnSearch" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   
							</th>
						</tr>
						
						<tr>
							<th width="10">#</th>
							<th width="10"></th>
							<th width="300" class="left">Tên</th>	
							<th width="200" >Đường dẫn</th>
							<th class="center">Mặc định</th>						
							<th width="60" class="center">ID</th>						
						</tr>
					</thead>
					<tbody class="rows">
							<?php $i = 0; foreach ($this->templates as $template): $i++; if ($i % 2 != 0) {?>
							<tr class="odd gradeX" >							
								<td class="left"><?php echo $i ?></td>
								<td class="center"><input type="radio" name="select" id="<?php echo $this->escape($template->id) ?>" component="<?php echo $this->escape($template->component_id); ?>" /></td> 
								<td class="left"><?php echo $this->escape($template->name) ?></td>
								<td class="left"><?php echo $this->escape($template->path) ?></td>
								<td class="center"><img src="<?php if ($template->is_default == 1) echo $this->dirImg; ?>/default.png" title="Mặc định" /></td>																						
								<td class="center"><?php echo $this->escape($template->id) ?></td>
							</tr>		
							<?php } else { ?>
								<tr class="even gradeC" id="<?php echo $this->escape($template->id) ?>">							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="radio" name="select" id="<?php echo $this->escape($template->id) ?>" component="<?php echo $this->escape($template->component_id); ?>" /></td> 
									<td class="left"><?php echo $this->escape($template->name) ?></td>
									<td class="left"><?php echo $this->escape($template->path) ?></td>
									<td class="center"><img src="<?php if ($template->is_default == 1) echo $this->dirImg; ?>/default.png" title="Mặc định" /></td>																							
									<td class="center"><?php echo $this->escape($template->id) ?></td>
								</tr>
							<?php } ?>							
							<?php endforeach ?>			
					</tbody>
				</table>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->