<section id="money-info">
		<p id="money" class="statics">Tỷ giá</p>  
		<hgroup id="money-table">                      
			<table width="92%" border="0px" cellspacing="0" cellpadding="0">                           
				<tbody>
					<tr>
						<td>USD</td>
						<td>19.500</td>                                
					</tr>
					<tr>
						<td>GBP</td>
						<td>31.566</td>                                
					</tr>
					<tr>
						<td>HKD</td>
						<td>2.590</td>                                
					</tr>
					<tr>
						<td>CHF</td>
						<td>20.761</td>                                
					</tr>
					<tr>
						<td>JPY</td>
						<td>247.02</td>                                
					</tr>
					<tr>
						<td>AUD</td>
						<td>19.610</td>                                
					</tr>
					<tr>
						<td>CAD</td>
						<td>19.491</td>                                
					</tr>
						<td>SGD</td>
						<td>15.368</td>                                
					</tr>
					</tr>
						<td>EUR</td>
						<td>27.713</td>                                
					</tr>
				</tbody>
			</table>
		</hgroup>										
	</section>