<nav>
	 <ul>
		 <li class="<?php if ($_SESSION['nav-main'] == 1) echo 'active'; ?> first"><a href="stock/index" class="first-child">Trang chủ</a></li>
		 <li><a href="" class="s_blue">Thực hiện giao dịch</a></li>    	         
		 <li <?php if ($_SESSION['nav-main'] == 3) echo "class='active'"; ?>><a href="stock/index/statics">Thống kê sàn ảo</a></li>
		 <li><a href="#">Thảo luận sàn ảo</a></li>
		 <li <?php if ($_SESSION['nav-main'] == 2) echo "class='active'"; ?>><a href="stock/index/rule">Thể lệ sàn ảo</a></li>						    			 	    			     			                
		 <li class="last"><a href="news/index" class="last-child">Tin tức</a></li>					 
	 </ul>
</nav>