	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item player">
				<h4>Quản lý người chơi</h4>
				<div class="float-right">	
					<div class="global" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>"></div>																								
					<a class="minibutton btn edit" name="người chơi" path="admin/player/edit" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>
					<a class="minibutton btn publish" name="người chơi" mapper="playerMapper" path="admin/player/enable">
						<span><span class="icon publish"></span>Enable</span>
					</a>
					<a class="minibutton btn unpublish" name="người chơi" mapper="playerMapper" path="admin/player/disable">
						<span><span class="icon unpublish"></span>Disable</span>
					</a>
					<a class="minibutton btn deleteall" name="người chơi" path="admin/player/delete">
						<span><span class="icon delete"></span>Xóa</span>
					</a>									
				</div>				
			</div>
			
			<div class="portlet-content">				 							                             														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/player/auto-suggestion" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" value="Tìm kiếm" name="username" class="btnSearch" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   							
						</tr>
						
						<tr>
							<th width="10">#</th>
							<th width="10"><input type="checkbox" id="select_all"></th>	
							<th width="200">Username</th>
							<th width="300">Họ tên</th>
							<th width="200">Ngày sinh</th>
							<th width="300" class="left">Email</th>							
							<th width="300">Số điện thoại</th>							
							<th width="300">Tiền</th>
							<th width="100" class="center">Enable</th>														
							<th width="10" class="right">ID</th>							
						</tr>
					</thead>
					<tbody class="rows no-link2">
							<?php $i = 0; foreach ($this->players as $player): $i++; if ($i % 2 != 0) {?>
								<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="checkbox" name="select" value="<?php echo $this->escape($player['id']) ?>" id="<?php echo $this->escape($player['id']) ?>" /></td> 
									<td class="left"><a href="admin/player/view/id/<?php echo $this->escape($player['id']) ?>/"><?php echo $this->escape($player['username']) ?></a></td>
									<td class="left"><?php echo $this->escape($player['full_name']) ?></td>
									<td class="left">										
										<?php
											  echo Cloud_Model_Utli_CloudUtli::showDay($player['birthday']); 						
										?>
									</td>
									<td class="left"><?php echo $this->escape($player['email']) ?></td>
									<td class="left"><?php echo $this->escape($player['mobile']) ?></td>
									<?php 
										if ($player['is_enable'] == 1) {
											$title = "Click vào để disable thành viên";
											$img =  $this->dirImg . '/AnHien_1.png'; 
										} else {
											$title = "Click vào để kich hoạt thành viên";	
											$img = $this->dirImg . '/AnHien_0.png';
										}
										

										$money = Zend_Locale_Format::toNumber($player['money'],
                                       						array('locale' => 'en')
                                         );
									?>
									<td class="left money"><?php echo $money ?></td>
									<td class="center">			
										<img name="player" mapper="playerMapper" path="admin/player/set-enable" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($player['id']) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>																															
									<td class="right"><?php echo $this->escape($player['id']) ?></td>
								</tr>		
							<?php } else { ?>
								<tr class="even gradeC">							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="checkbox" name="select" value="<?php echo $this->escape($player['id']) ?>" id="<?php echo $this->escape($player['id']) ?>" /></td> 
									<td class="left"><a href="admin/player/view/id/<?php echo $this->escape($player['id']) ?>/"><?php echo $this->escape($player['username']) ?></a></td>
									<td class="left"><?php echo $this->escape($player['full_name']) ?></td>
									<td class="left">										
										<?php
											  echo Cloud_Model_Utli_CloudUtli::showDay($player['birthday']); 						
										?>
									</td>
									<td class="left"><?php echo $this->escape($player['email']) ?></td>
									<td class="left"><?php echo $this->escape($player['mobile']) ?></td>
									<?php 
										if ($player['is_enable'] == 1) {
											$title = "Click vào để disable thành viên";
											$img =  $this->dirImg . '/AnHien_1.png'; 
										} else {
											$title = "Click vào để kich hoạt thành viên";	
											$img = $this->dirImg . '/AnHien_0.png';
										}
										
										$money = Zend_Locale_Format::toNumber($player['money'],
                                       						array('locale' => 'en')
                                         );
									?>
									<td class="left money"><?php echo $money ?></td>
									<td class="center">			
										<img name="player" mapper="playerMapper" path="admin/player/set-enable" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($player['id']) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>																														
									<td class="right"><?php echo $this->escape($player['id']) ?></td>
								</tr>													
							<?php } endforeach ?>			
					</tbody>
				</table>	
				<?php echo $this->paginationControl($this->players, 'Sliding', 'pagination.phtml'); ?>																																
			</div>					
		</div>			
		
	</div><!--  end #content -->