<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item user">
			<h4>Profile</h4>
			<div class="float-right">											
				<div class="global" id="<?php echo $this->player->id ?>" path1="admin/player/edit/id/<?php echo $this->player->id ?>/" path2="admin/player/delete" password="admin/player/change-password/id/<?php echo $this->player->id ?>/" back="<?php echo $_SESSION['temp']; ?>"></div>																																																																
				<a class="minibutton btn password">
					<span><span class="icon password" ></span>Thay đổi mật khẩu</span>
				</a>
				<a class="minibutton btn edit2">
					<span><span class="icon edit" ></span>Sửa</span>
				</a>	
				<a class="minibutton btn delete2" name="user">
					<span><span class="icon delete"></span>Xóa</span>
				</a>
				<a class="minibutton btn close">
						<span><span class="icon close"></span>Đóng</span>
				</a>
			</div>				
		</div>
		
		<div class="portlet-content">	
			<?php 
				if (null != $this->player) {
						$money = Zend_Locale_Format::toNumber($this->player->money,
                                    						array('locale' => 'en')
                        );					 
			?>								 							                													
			<table cellpadding="0" cellspacing="0" border="0" class="display">
				<tr>
					<td width="100"><b>Username :</b></td>
					<td><?php echo $this->player->username ?></td>
				</tr>	
				<tr>
					<td width="100"><b>Tổng tiền :</b></td>
					<td class="money green"><?php echo $money ?></td>
				</tr>						
				<tr>
					<td width="90"><b>Họ tên :</b></td>
					<td><?php echo $this->player->full_name ?></td>
				</tr>	
				<tr>
					<td><b>Giới tính :</b></td>
					<?php $gender = ($this->player->gender == 1) ? "Nam" : "Nữ" ?>
					<td><?php echo $gender; ?></td>
				</tr>
				<tr>
					<td><b>Ngày sinh :</b></td>
					<td><?php echo Cloud_Model_Utli_CloudUtli::showDay($this->player->birthday) ?></td>
				</tr>
				<tr>
					<td><b>Email :</b></td>
					<td><?php echo $this->player->email ?></td>
				</tr>
				<tr>
					<td><b>Số điện thoại :</b></td>
					<td><?php echo $this->player->mobile ?></td>
				</tr>
				<tr>
					<td><b>Địa chỉ :</b></td>
					<td><?php echo $this->player->address ?></td>
				</tr>
				<tr>
					<td><b>Nghề nghiệp :</b></td>
					<td><?php echo $this->player->job ?></td>
				</tr>
				<tr>
					<td><b>Nơi công tác :</b></td>
					<td><?php echo $this->player->company ?></td>
				</tr>																		
				<tr>
					<td><b>Status :</b></td>
					<?php $enable = ($this->player->is_enable == 1) ? "Enable" : "Disable" ?>
					<td><?php echo $enable ?></td>
				</tr>			
			</table>
			<?php } ?>																																	
		</div>
	</div>			
	
</div><!--  end #content -->