<section class="news-inportant">
	<a href="index.php/news/index/detail" ><img src="files/news/30102010/120.jpg" class="left"/></a>
	<hgroup>
		<a href="index.php/news/index/detail" >'Chợ chiều' trên sàn chứng khoán</a>
		<br /><label class="c-time">01:24</label>  |  <label class="c-date">28/10/2010</label><br />
		<p>
			Giá nhiều cổ phiếu sau chu kỳ giảm đã lùi về mức của 2-3 tháng trước, được giới phân tích đánh giá là cơ hội vàng để mua vào sang năm hưởng lợi. Song, không mấy nhà đầu tư ngó ngàng đến việc giải ngân lúc này.<br />
			&gt; <a>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a>
		</p>
	</hgroup>
	<div class="clear"></div>
</section>