	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item role">
				<h4>Sửa role</h4>
				<div class="float-right">
					<div class="global" back="<?php echo $_SESSION['temp']; ?>"></div>
					<a class="minibutton btn close">
						<span><span class="icon close"></span>Đóng</span>
					</a>							
				</div>				
			</div>
			
			<div class="portlet-content">
				<?php if (isset($this->message)) {?>
					<div class="message">
						<?php echo $this->message; ?>
					</div>					
				<?php } ?>				
				<img src="<?php echo $this->dirImg;?>/loading2.gif" class="hide1" />
				
				<div class="addContentDyn">
					<form class="form label-inline">
								<div class="field">
									<label for="name">Tên role</label> 
									<input class="name" size="60" type="text" class="medium" value="<?php echo $this->role->name;?>"/>
									<div class="message1" style="display: inline;"></div>
								</div>	
								
								<div class="field">
									<label for="description">Mô tả</label> 
									<input class="description" size="60" type="text" class="medium" value="<?php echo $this->role->description;?>"/>								
								</div>			
								
								<input type="hidden" class="id" value="<?php echo $this->role->id;?>" />																																																					
								
								<div class="buttonrow" style="margin-right: 10px;">								
									<button class="btn btn-grey continue" url="admin/role/edit-cont">Next</button>
								</div>															
					</form>	
				</div>			
																																
			</div><!--  end .portlet-content -->
		</div>
	</div><!--  end #content -->