<article class="statics-box box-first">
	<h2>Thống kê khối lượng giao dịch trong ngày</h2>
	<p>Tháng :10/2010</p>
	<table width="100%">
		<thead>
			<tr>
				<td>Mã CK</td>
				<td>Giá Trần</td>
				<td>Giá Sàn</td>
				<td>Giá TC</td>
				<td>SL Khớp</td>
				<td>Giá Trị</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td align="left">ASM</td>
				<td align="right">59,500</td>
				<td align="right">54,500</td>
				<td align="right">57,000</td>
				<td align="right">10,000</td>
				<td align="right">569,900,000</td>
			</tr>
			<tr>
				<td align="left">BVH</td>
				<td align="right">67,000</td>
				<td align="right">61,000</td>
				<td align="right">64,000</td>
				<td align="right">43,290</td>
				<td align="right">2,770,670,000</td>
			</tr>
			<tr>
				<td align="left">ASM</td>
				<td align="right">59,500</td>
				<td align="right">54,500</td>
				<td align="right">57,000</td>
				<td align="right">10,000</td>
				<td align="right">569,900,000</td>
			</tr>
			<tr>
				<td align="left">BVH</td>
				<td align="right">67,000</td>
				<td align="right">61,000</td>
				<td align="right">64,000</td>
				<td align="right">43,290</td>
				<td align="right">2,770,670,000</td>
			</tr>
			<tr>
				<td align="left">ASM</td>
				<td align="right">59,500</td>
				<td align="right">54,500</td>
				<td align="right">57,000</td>
				<td align="right">10,000</td>
				<td align="right">569,900,000</td>
			</tr>
			<tr>
				<td align="left">BVH</td>
				<td align="right">67,000</td>
				<td align="right">61,000</td>
				<td align="right">64,000</td>
				<td align="right">43,290</td>
				<td align="right">2,770,670,000</td>
			</tr>
		</tbody>
	</table>
</article>