<p id="user-statics-header">Thống kê thành viên</p>
<hr  />
<ul>
	<li>UITStock có <span class="blue"><?php echo $userNumber ?></span> thành viên</li>
	<li>Số người đang xem: <span class="blue"><?php echo $userOnlineNumber ?></span></li>
	<li>Trong đó có: <span class="blue"><?php echo $playerOnlineNumber ?></span> thành viên</li>
	<li class="indent"><?php echo $list ?></li>
</ul>             