<section id="news-company">
	<h2>Tin doanh nghiệp</h2>
	<hgroup>
		<ul>
			<li><a href="news/index/detail">SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP  <span>30-10-2010 6:26PM</span></a></li>
			<li><a href="news/index/detail">HT1:Giải trình lợi nhuận quý 3/2010 giảm 137 tỷ đồng so với cùng kỳ  <span>30-10-2010 6:20PM</span></a></li>
			<li><a href="news/index/detail">Chứng khoán tuần qua: Vẫn “nản” với thanh khoản  <span>30-10-2010 6:18PM</span></a></li>
			<li><a href="news/index/detail">Dược Hà Tây kiến nghị truy tiếp DVD “tội làm giá”  <span>30-10-2010 12:58AM</span></a></li>
			<li><a href="news/index/detail">VNT: LNST quý 3/2010 của cty mẹ đạt 2,91 tỷ đồng, EPS đạt 532 đồng (HNX)  <span>30-10-2010 12:08AM</span>    </a></li>
		</ul>
	</hgroup>
</section>