<section id="news-company">
	<h2>Tin doanh nghiệp</h2>
	<hgroup>
		<ul>
			<?php 
				foreach ($news as $new) {
			?>
			<li>
				<a href="news/index/detail">
					<?php 							
						  $date = $this->escape($new['create_date']); 																					  
						  $date = new Zend_Date($date, Cloud_Model_Utli_CloudUtli::DATE);
						  $date = $date->get(Cloud_Model_Utli_CloudUtli::DATE);					  							
						  echo $new['title'];
					?>
				  	<span>
				  		<?php echo $date;?>
				  	</span>
				</a>
			</li>			
			<?php } ?>
		</ul>
	</hgroup>
</section>