<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item password">
			<h4>Thay đổi mật khẩu</h4>
			<div class="float-right">
				<div class="global" back="<?php echo $_SESSION['temp']; ?>"></div>
				<a class="minibutton btn close">
					<span><span class="icon close"></span>Đóng</span>
				</a>							
			</div>				
		</div>
		
		<div class="portlet-content">
			<?php if (isset($this->message)) {?>
				<div class="message">
					<?php echo $this->message; ?>
				</div>					
			<?php } ?>
			
			<?php if (null != $this->user) {?>
				<p><b>Thành viên</b>: <span class="nickname"><?php echo $this->user['full_name'];?></span></p>
				<?php echo $this->form;  ?>		
			<?php } ?>																																	
		</div><!--  end .portlet-content -->
	</div>
</div><!--  end #content -->