<section id="statics-news" class="info1">
	<ul class="tabs">
		<li><a href="#tab1-statics">Chỉ số Việt Nam</a></li>
		<li><a href="#tab2-statics">Chỉ số thế giới</a></li>                      
	</ul>
						
	<hgroup class="tab_container1">
		<article id="tab1-statics" class="tab_content1">
			<div class="s-box">
				<ul class="left">
					<li><b>HoSE</b> (11:22 29/10)</li>
					<li><span class="green">452.63 +2.6 +0.57%</span></li>
					<li>KLGD: <b>33.38</b> triệu CP</li>                                             
					<li>GTGD: <b>1,008</b> tỷ VNĐ</li>
				</ul>
				<img src="files/news/30102010/hose.png" class="right"/>
				<div class="clear"></div>                                                                                        
			</div>       
			
			<div class="s-box">
				<ul class="left">
					<li><b>HNX</b> (11:22 29/10)</li>
					<li><span class="green">112.86 +1.3 +1.21%</span></li>
					<li>KLGD: <b>17.49</b> triệu CP</li>                                             
					<li>GTGD: <b>351</b> tỷ VNĐ</li>
				</ul>
				<img src="files/news/30102010/hnx.png" class="right"/>
				<div class="clear"></div>                                                                                        
			</div>                                            	                                        
		</article>
		<article id="tab2-statics" class="tab_content1">
			   <table width="100%">    
				  <caption>World Market Watch</caption>
				  <thead>
					<tr>
						<th width="100">Exchange</th>
						<th width="100">Last</th>
						<th width="100">Change</th>
					</tr>
				  </thead>    
				  <tbody>
					<tr>
						<td><img src="files/world-market/us.gif" /><a class="link">DJIA® *</a></td>
						<td>0</td>
						<td><span class="green">0</span></td>  
					</tr>
					<tr>
						<td><img src="files/world-market/us.gif" /><a class="link">Nasdaq</a></td>
						<td>2507.41</td>
						<td><span class="green">0.04</span></td>  
					</tr>
					<tr>
						<td><img src="files/world-market/us.gif" /><a class="link">S & P 500</a></td>
						<td>1183.26</td>
						<td><span class="red">-0.52</span></td>  
					</tr>
					<tr>
						<td><img src="files/world-market/ar.gif" /><a class="link">MerVal</a></td>
						<td>3007.41</td>
						<td><span class="green">52.55</span></td>  
					</tr>
					<tr>
						<td><img src="files/world-market/br.gif" /><a class="link">Bovespa</a></td>
						<td>70673.29</td>
						<td><span class="green">353.17</span></td>  
					</tr>
					<tr>
						<td><img src="files/world-market/ca.gif" /><a class="link">TSX</a></td>
						<td>12676.24</td>
						<td><span class="green">112.15</span></td>  
					</tr>                                                                                                       
				  </tbody>                                                                                                                                                                                                                                                                                                                                                                                                                                                   
			  </table>                                                                   	
		</article>                           
	</hgroup>                                    
</section>

<div class="clear"></div>