	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item menuCategory">
				<h4>Quản lý Menu Category</h4>
				<div class="float-right">																									
					<a class="minibutton btn add" path="admin/menu/add-cat">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="menuCategory" path="admin/menu/edit-cat" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>					
					<a class="minibutton btn delete" name="menuCategory" path="admin/menu/deletec-cat" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon delete"></span>Xóa</span>
					</a>					
				</div>				
			</div>
			
			<div class="portlet-content">				 							                														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/menu/auto-suggestion-menuCategory" component="<?php echo $this->c; ?>" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" value="Tìm kiếm" name="name" class="btnSearch" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   
							</th>
						</tr>
						
						<tr>
							<th width="10">#</th>
							<th width="10"></th>
							<th width="500" class="left">Name</th>
							<th width="50">Menu Item(s)</th>												
							<th width="60" class="center">ID</th>						
						</tr>
					</thead>
					<tbody class="rows">							
							<tr class="odd gradeX" >							
								<td class="left">1</td>
								<td class="center"><input type="radio" name="select" /></td> 
								<td class="left">Menu</td>	
								<td class="center"><a href="admin/menu/list-item"><img src="<?php echo $this->dirImg; ?>/view.png" />																																					
								<td class="center">1</td>
							</tr>										
					</tbody>
				</table>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->