<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item avatar">
			<h4>Thay đổi avatar</h4>
			<div class="float-right">
				<div class="global" back="<?php echo $_SESSION['temp']; ?>"></div>
				<a class="minibutton btn close">
					<span><span class="icon close"></span>Đóng</span>
				</a>							
			</div>				
		</div>
		
		<div class="portlet-content">
			<?php 
				if (null != $this->user) {
					$dirname = "files/avatar/user/" . $this->user['email'] . "/";
					$ignore = Array(".", "..", "Thumbs.db", '.svn');
					$images = scandir($dirname);
					$count = 0;
					$avatar = $this->user['avatar'];
					$curavatar = substr($avatar, strripos($avatar, '/') + 1);
			?>
					<p>Thành viên: <span class="nickname"><?php echo $this->user['full_name'];?></span></p>
					<p>Tổng số avatar: 
						<?php 
							foreach($images as $curimg) {					
								if(!in_array($curimg, $ignore)) {
									$count++;
								}}; 					
						?><span class="orange"><?php echo $count?></span>
					</p>	
					
					<form method="post" action="">		
						<?php 								
							foreach($images as $curimg) {
								if(!in_array($curimg, $ignore)) {				
						?>
							<input type="radio" name="avatar" <?php if ($curimg == $curavatar) echo "checked"; ?> value="<?php echo $curimg;?>" /><img src="<?php echo $dirname . $curimg; ?>" width="100" height="100" />
						<?php }}; ?><br/><br/>
						<div class="buttonrow">								
						    <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>" />				    
						    <input type="hidden" name="email" value="<?php echo $this->user['email']; ?>" />
							<button class="btn btn-orange" name="btnSubmit">Đổi avatar</button>						
						</div>
					</form>	
			<?php } ?>
																																	
		</div><!--  end .portlet-content -->
	</div>
</div><!--  end #content -->