	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item user">
				<h4>Quản lý thành viên</h4>
				<div class="float-right">	
					<div class="global" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>"></div>																								
					<?php 								
		 				foreach ($this->button1 as $button) {
		 					echo stripslashes($button['button1']);
		 				}	 									 				
					?>					
				</div>				
			</div>
			
			<?php 
				$flag = false;		
 				foreach ($this->privileges as $privilege) {
					if ($privilege['id'] == 36) $flag = true; 
 				}
  				if ($flag) {					 				
			?>
			<div class="portlet-content">				 							                             														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/user/auto-suggestion" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" value="Tìm kiếm" name="title" class="btnSearch" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   							
						</tr>
						
						<tr>
							<th width="10">#</th>
							<th width="10"><input type="checkbox" id="select_all"></th>	
							<th width="500">Tên</th>
							<th width="200">Ngày sinh</th>
							<th width="300" class="left">Email</th>							
							<th width="300">Số điện thoại</th>
							<th width="200" class="center">Quyền hạn</th>
							<th width="100" class="center">Enable</th>														
							<th width="10" class="right">ID</th>							
						</tr>
					</thead>
					<tbody class="rows no-link2">
							<?php $i = 0; foreach ($this->users as $user): $i++; if ($i % 2 != 0) {?>
								<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="checkbox" name="select" value="<?php echo $this->escape($user['id']) ?>" id="<?php echo $this->escape($user['id']) ?>" /></td> 
									<td class="left"><a href="admin/user/view/id/<?php echo $this->escape($user['id']) ?>/"><?php echo $this->escape($user['full_name']) ?></a></td>
									<td class="left">										
										<?php
											  echo Cloud_Model_Utli_CloudUtli::showDay($user['birthday']); 						
										?>
									</td>
									<td class="left"><?php echo $this->escape($user['email']) ?></td>
									<td class="left"><?php echo $this->escape($user['mobile']) ?></td>
									<td class="center"><?php echo $this->escape($user['role_name']) ?></td>																	
									<td class="center">
										<?php if ($user['is_enable'] == 1) {
											$title = "Click vào để disable thành viên";
											$img =  $this->dirImg . '/AnHien_1.png'; 
											} else {
											$title = "Click vào để kich hoạt thành viên";	
											$img = $this->dirImg . '/AnHien_0.png';
											}
										?>
										<img name="user" mapper="userMapper" path="admin/user/set-enable" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($user['id']) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>																															
									<td class="right"><?php echo $this->escape($user['id']) ?></td>
								</tr>		
							<?php } else { ?>
								<tr class="even gradeC">							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="checkbox" name="select" value="<?php echo $this->escape($user['id']) ?>" id="<?php echo $this->escape($user['id']) ?>" /></td> 
									<td class="left"><a href="admin/user/view/id/<?php echo $this->escape($user['id']) ?>"><?php echo $this->escape($user['full_name']) ?></a></td>
									<td class="left">										
										<?php
											  echo Cloud_Model_Utli_CloudUtli::showDay($user['birthday']); 						
										?>
									</td>
									<td class="left"><?php echo $this->escape($user['email']) ?></td>
									<td class="left"><?php echo $this->escape($user['mobile']) ?></td>
									<td class="center"><?php echo $this->escape($user['role_name']) ?></td>																	
									<td class="center">
										<?php if ($user['is_enable'] == 1) {
											$title = "Click vào để disable thành viên";
											$img =  $this->dirImg . '/AnHien_1.png'; 
											} else {
											$title = "Click vào để kich hoạt thành viên";	
											$img = $this->dirImg . '/AnHien_0.png';
											}
										?>
										<img name="user" mapper="userMapper" path="admin/user/set-enable" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($user['id']) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>																															
									<td class="right"><?php echo $this->escape($user['id']) ?></td>
								</tr>													
							<?php } endforeach ?>			
					</tbody>
				</table>	
				<?php echo $this->paginationControl($this->users, 'Sliding', 'pagination.phtml'); ?>																																
			</div>
			<?php } ?>		
		</div>			
		
	</div><!--  end #content -->