<nav>
	<div class="MenuWrapper02">
		<div class="MenuWrapper">
			<ul id="menu">
				<li class="First"><a href="" ><span class="LeftBg"><span class="RightBg">Trang chủ</span></span></a>
					<ul>
						<li class="FirstItem"><a href="" >Sàn chứng khoán ảo</a></li>
						<li><a href="#">Đặt làm trang chủ</a></li>
					</ul>
				</li>
				<li><a href="news/index/category/aliasP/tin-tuc/" title="Trang chính"  class="Active Hover"><span class="LeftBg"><span class="RightBg">Tin tức</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category/aliasP/tin-tuc/aliasS/tin-van-chung-khoan/" >Tin vắn chứng khoán</a></li>
						<li><a href="news/index/category/aliasP/tin-tuc/aliasS/tin-hose/" >Tin HOSE</a></li>
						<li><a href="news/index/category/aliasP/tin-tuc/aliasS/tin-tu-cong-ty-niem-yet/" >Tin từ công ty niêm yết</a></li>                     
					</ul>
				</li>
				<li><a href="news/index/category/aliasP/nhan-dinh-thi-truong/" ><span class="LeftBg"><span class="RightBg">Nhận định thị trường</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category/aliasP/nhan-dinh-thi-truong/aliasS/cong-ty-ck-nhan-dinh/" title="Giới tính">Công ty CK nhận định</a></li>
						<li><a href="news/index/category/aliasP/nhan-dinh-thi-truong/aliasS/thi-truong/" >Thị trường</a></li>
						<li><a href="news/index/category/aliasP/nhan-dinh-thi-truong/aliasS/cong-ty/" >Công ty</a></li>                     
					</ul>
				</li>
				<li><a href="news/index/category/aliasP/kinh-te-viet-nam/" ><span class="LeftBg"><span class="RightBg">Kinh tế Việt Nam</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category/aliasP/kinh-te-viet-nam/aliasS/thi-truong-vn/" >Thị trường</a></li>
						<li><a href="news/index/category/aliasP/kinh-te-viet-nam/aliasS/tai-chinh---ngan-hang/" >Tài chính - Ngân hàng</a></li>
						<li><a href="news/index/category/aliasP/kinh-te-viet-nam/aliasS/bat-dong-san/" >Bất động sản</a></li>                     
					</ul>
				</li>
				<li><a href="news/index/category/aliasP/kinh-te-the-gioi/" ><span class="LeftBg"><span class="RightBg">Kinh tế thế giới</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category/aliasP/kinh-te-the-gioi/aliasS/chung-khoan/" >Chứng khoán</a></li>
						<li><a href="news/index/category/aliasP/kinh-te-the-gioi/aliasS/thi-truong-tg/">Thị trường</a></li>                                      
					</ul>
				</li>
				<li><a href="news/index/category/aliasP/kien-thuc-dau-tu/" ><span class="LeftBg"><span class="RightBg">Kiến thức đầu tư</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category/aliasP/kien-thuc-dau-tu/aliasS/kien-thuc-co-ban/">Kiến thức cơ bản</a></li>
						<li><a href="news/index/category/aliasP/kien-thuc-dau-tu/aliasS/kinh-nghiem-dau-tu/">Kinh nghiệm đầu tư</a></li>                                      
					</ul>
				</li>

			</ul>		          
		</div>            
	</div>        
</nav>

<p id="sub_nav"></p>