<nav>
	<div class="MenuWrapper02">
		<div class="MenuWrapper">
			<ul id="menu">
				<li class="First"><a href="" ><span class="LeftBg"><span class="RightBg">Trang chủ</span></span></a>
					<ul>
						<li class="FirstItem"><a href="" >Sàn chứng khoán ảo</a></li>
						<li><a href="#">Đặt làm trang chủ</a></li>
					</ul>
				</li>
				<li><a href="news/index/category" title="Trang chính"  class="Active Hover"><span class="LeftBg"><span class="RightBg">Tin tức</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category" >Tin vắn chứng khoán</a></li>
						<li><a href="news/index/category" >Tin HOSE</a></li>
						<li><a href="news/index/category" >Tin từ công ty niêm yết</a></li>                     
					</ul>
				</li>
				<li><a href="news/index/category" ><span class="LeftBg"><span class="RightBg">Nhận định thị trường</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category" title="Giới tính">Công ty CK nhận định</a></li>
						<li><a href="news/index/category" >Thị trường</a></li>
						<li><a href="news/index/category" >Công ty</a></li>                     
					</ul>
				</li>
				<li><a href="news/index/category" ><span class="LeftBg"><span class="RightBg">Kinh tế Việt Nam</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category" >Thị trường</a></li>
						<li><a href="news/index/category" >Tài chính - Ngân hàng</a></li>
						<li><a href="news/index/category" >Bất động sản</a></li>                     
					</ul>
				</li>
				<li><a href="news/index/category" ><span class="LeftBg"><span class="RightBg">Kinh tế thế giới</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category" >Chứng khoán</a></li>
						<li><a href="news/index/category">Thị trường</a></li>                                      
					</ul>
				</li>
				<li><a href="news/index/category" ><span class="LeftBg"><span class="RightBg">Kiến thức đầu tư</span></span></a>
					<ul>
						<li class="FirstItem"><a href="news/index/category#">Kiến thức cơ bản</a></li>
						<li><a href="news/index/category">Kiến thức đầu tư</a></li>                                      
					</ul>
				</li>

			</ul>		          
		</div>            
	</div>        
</nav>

<p id="sub_nav"></p>