<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<title><?php echo $this->message ?></title>
	<link rel="stylesheet" href="files/error/error.css" type="text/css" />
</head>
<body>
	<div align="center">
		<div id="outline">
		<div id="errorboxoutline">
			<div id="errorboxheader"><?php echo $this->message ?></div>
			<div id="errorboxbody">
			<p><strong>You may not be able to visit this page because of</strong></p>
				<ol>
					<li>An out-of-date bookmark/favourite</li>
					<li>A search engine that has an out-of-date listing for this site</li>
					<li>A mis-typed address</li>
					<li>You have no access to this page</li>
					<li>The requested resource was not found</li>
					<li>An error has occurred while processing your request</li>
				</ol>
			<p><strong>Please try one of the following pages</strong></p>
						
			<ul><li><a href="http://uitstock" title="Go to the home page">Home Page</a></li></ul>			
			
			<p>If difficulties persist, please contact the system administrator of this site.</p>
			<div id="techinfo">
			<p><?php echo $this->message ?></p>
			<p>
				
			</p>
			</div>
			</div>
		</div>
		</div>
	</div>
</body>
</html>