 <section id="gold-info">
		<p id="gold" class="statics">Giá vàng 9999</p>
		<p class="right">ĐVT: tr.đ/lượng</p>
		<table width="92%" border="0px" cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<td>Loại</td>
					<td>Mua</td>
					<td>Bán</td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>SBJ</td>
					<td>32.950</td>
					<td>32,970</td>
				</tr>
				<tr>
					<td>SJC</td>
					<td>32.910</td>
					<td>32,9870</td>
				</tr>
			</tbody>
		</table>
	</section>