 <section class="detail">
	<h2><?php echo $new['title']; ?></h2>                
	<div class="detail-summarize">
		<p><?php echo $new['summarize'];?></p>
		<p> 
		<?php 
			if ($relatives != '') {	 echo "&gt;";								
				foreach ($relatives as $relative) {
					$alias = $relative['alias']; 
					$link = (null == $this->aliasS) ?
						"tintuc/$this->aliasP/$alias/" :
						"tintuc/$this->aliasP/$this->aliasS/$alias/";	
		?>
				<a href="tintuc/<?php echo $link;?>"><?php echo $relative->title;?></a> /
		<?php }} ?>
		</p>
	</div><!-- end .detail-summarize -->
	<div class="detail-main-content">
		<?php echo $new['content']; ?>
	</div><!-- end .detail-main-content -->                
</section>

<section class="news-other">
	<p>
		<span>Các tin khác</span>
	</p>
	<ul>
		<?php 
			foreach($otherNews as $otherNew):
				$alias = $otherNew['alias']; 
				$link = (null == $this->aliasS) ?
					"tintuc/$this->aliasP/$alias/" :
					"tintuc/$this->aliasP/$this->aliasS/$alias/";		
		?>
			<li>
				
				<a href="<?php echo $link;?>">
					<?php echo $otherNew['title']; ?> 
					<label><?php echo Cloud_Model_Utli_CloudUtli::showDate($otherNew['create_date']); ?></label>
				</a>
			</li>
		<?php endforeach ?>		
	</ul>	
</section>  