 <section class="detail">
	<h2>'Thông tư quản lý vàng tác động tốt đến chứng khoán'</h2>                
	<div class="detail-summarize">
		<p>Một số công ty chứng khoán cho rằng giao dịch trên thị trường trong tuần tới sẽ được cộng hưởng tốt từ sự ra đời của Thông tư 22 về quản lý huy động và cho vay vàng của các tổ chức tín dụng.</p>
		<p>&gt; <a>Thị trường vàng vào 'vòng pháp luật'</a> / <a>Thị trường vàng sẽ nhiều 'sóng' trước hạn tất toán</a></p>
	</div><!-- end .detail-summarize -->
	<div class="detail-main-content">
		<p><strong><font color="#4f4f4f">Công ty chứng khoán Rồng Việt (VDSC)</font></strong></p>
		<p>Thông tin vĩ mô được xem là tốt nhất ủng hộ cho sự phục hồi của thị trường phiên cuối tuần là Thông tư quản lý hoạt động cho vay huy động vàng vừa. Với quy định mới này, Ngân hàng Nhà nước kỳ vọng sẽ có một khối lớn vàng đầu tư và đầu cơ được chuyển hóa thành tiền phục vụ cho các hoạt động sản xuất kinh doanh. Thị trường chứng khoán cũng có chung hy vọng sẽ có một phần vốn từ thị trường vàng được chuyển vào giúp cải thiện thanh khoản.</p>
		<p>Tuy nhiên, một quyết định liên quan chính sách vĩ mô chỉ vừa mới được ban hành không đủ giúp nhà đầu tư ngay lập tức lấy lại niềm tin, đặc biệt sau một thời gian dài chứng khoán trầm lắng. Lực bán có xu hướng mạnh dần khi Vn-Index tăng điểm, trong khi lực cầu chủ yếu xoay quanh các vùng giá thấp.</p>
		<p>Mặc dù hai chỉ số tăng điểm phiên cuối tuần nhưng thanh khoản vẫn rất yếu. Và kiểm chứng cho thấy, sự èo uột của thanh khoản sẽ không hỗ trợ cho chu kỳ tăng điểm bền vững. Mua vào ở vùng giá hiện tại có thể sẽ không mang lại tỷ suất lợi nhuận cao cho nhà đầu tư, trong khi hạ giá bán ra có thể khiến nhiều người bị thiệt. Nhà đầu tư có thể đứng ngoài quan sát thêm vài phiên nữa.</p>
		<p><strong><font color="#4f4f4f">Công ty chứng khoán Quốc Tế Việt Nam (VIS)</font></strong></p>
		<p>Nhiều doanh nghiệp công bố kết quả kinh doanh quý III. Tuy nhiên, doanh nghiệp không bắt buộc phải chuyển toàn bộ lợi nhuận vào, nên kết quả công bố không đủ kích thích dòng tiền vào thị trường mạnh lên. Bên cạnh đó, sự leo thang của giá USD trên thị trường chợ đen cùng với nỗi lo về áp lực cung hàng liên tục tăng lên trong các tháng cuối năm đã làm cho nhiều nhà đầu tư chọn giải pháp đứng bên ngoài thị trường nhiều hơn. Động thái này càng làm cho dòng tiền tham gia có xu hướng co hẹp lại.</p>
		<p>Mặc khác, tỷ giá liên tục biến động, lãi suất vẫn ở mức cao, áp lực lạm phát và thâm hụt thương mại khiến không ít nhà đầu tư quan ngại về khả năng tăng trưởng kinh tế đã tác động đến hành vi mua bán của nhà đầu tư. <br /><br/>Thị trường hiện thiếu nhiều thông tin hỗ trợ. Nhiều khả năng các chỉ số chứng khoán tiếp tục dao động trong biên độ hẹp ở tuần giao dịch kế tiếp.</p>
		
		<p><strong><font color="#4f4f4f">Công ty chứng khoán Âu Việt (AVSC)</font></strong></p>
		<p>Điểm sáng tuần này là khối ngoại vẫn tiếp tục mua ròng. Ngoài ra, nhiều tổ chức nước ngoài đang tích cực tìm hiểu thị trường chứng khoán Việt Nam vì duy nhất thị trường Việt Nam đi ngược lại với chu kỳ hồi phục của chứng khoán khu vực và thế giới. P/E được đánh giá là khá rẻ trong khu vực. Cho dù các tổ chức này chưa có động thái giải ngân và đang chờ tín hiệu ổn định từ kinh tế vĩ mô, nhưng đây thực sự là lực cầu lớn tiềm năng, có thể giúp thị trường hồi phục trở lại trong trung và dài hạn.</p>
		<p>Mặc dù thị trường vẫn tiềm ẩn những khó khăn của kinh tế vĩ mô cũng như những vấn đề gây mất công bằng giữa các nhà đầu tư thì vẫn tồn tại nhiều cơ hội đối với nhà đầu tư giá trị. Đối với nhà đầu tư lướt sóng, có thể hạn chế giao dịch cho đến khi có những tín hiệu khởi sắc từ các chính sách vĩ mô.</p>
		<p><strong><font color="#4f4f4f">Công ty chứng khoán VnDirect</font></strong></p>
		<p>Vn-Index đã vượt qua đường trung bình động tám ngày trong phiên cuối tuần cửa rồi. Với trạng thái hiện tại, chỉ số này vẫn có thể quay trở lại mức 460 điểm nhưng điểm mấu chốt vẫn là khối lượng giao dịch. Nếu tình trạng giao dịch ảm đạm này tiếp tục kéo dài, thị trường sẽ tiếp tục chán nản và đi xuống.</p>
		<p>Về quan điểm đầu tư, chiến thuật dài hạn vẫn chiếm ưu thế với việc giảm ngân dần vào các cổ phiếu tiêu biểu như SJS, DPM, VND, PHR, MPC, TCM… Về quan điểm ngắn hạn khi thị trường đi ngang nhà đầu tư nên sử dụng chiến thuật mua tại vùng hỗ trợ (440) và bán khi tăng gần mức kháng cự (460).</p>
		<p><strong><font color="#4f4f4f">Công ty chứng khoán FPT (FPTS)</font></strong></p>
		<p>Phiên giao dịch ngày thứ 6 khép lại một tuần giao dịch thành công xét về mặt điểm số. Cả hai chỉ số đều tăng nhẹ khi đóng cửa với phần đông các cổ phiếu tham gia giao dịch tăng điểm. Hoạt động giao dịch của nhà đầu tư nước ngoài trở thành tiêu điểm của phiên với sự gia tăng đột biến của cả mua lẫn bán. Tổng giá trị mua trong phiên lên đến 525,11 tỷ đồng, tổng giá trị bán cũng lên đến 461,58 tỷ đồng. Do hoạt động giao dịch của họ chủ yếu thông qua phương thức thỏa thuận nên không ảnh hưởng nhiều đến thị trường.</p>                    
		<p>Thị trường cho thấy lực cầu ở vùng giá thấp đang gia tăng và nhiều khả năng sẽ không sụt giảm trong thời gian tới. Tuy nhiên, áp lực nguồn cung lớn có thể tiếp tục tạo gánh nặng cho thị trường.</p>
		
		<span class="author"><b>Nhật Hường</b> <label class="italic">tổng hợp</label></span>
		<span class="note">* Bản tin do các công ty chứng khoán cung cấp và chỉ mang tính tham khảo.</span>
	</div><!-- end .detail-main-content -->                
</section>