	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item theme">
				<h4>Quản lý theme</h4>
				<div class="float-right">		
					<div class="global" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>"></div>																						
					<a class="minibutton btn add" path="admin/theme/add/">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="theme" path="admin/theme/edit" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>
					<a class="minibutton btn default" name="theme" path="admin/theme/set-default-theme">
						<span><span class="icon default"></span>Mặc định</span>
					</a>
					<a class="minibutton btn delete" name="theme" path="admin/theme/delete">
						<span><span class="icon delete"></span>Xóa</span>
					</a>					
				</div>				
			</div>
			
			<div class="portlet-content">				 			
				<div class="cat">	
					<?php $i = 0;foreach ($this->components as $component): $i++;?>
							<?php if ($this->c == $component->id) { ?>		
								<a class="active" href="admin/theme/list/component/<?php echo $component->id; ?>/" order="<?php echo $component->ordering; ?>">
									<span><?php echo $this->escape($component->name); ?></span>
								</a>							
							<?php } else { ?>				    	
							<a class="minibutton" href="admin/theme/list/component/<?php echo $component->id; ?>/" order="<?php echo $component->ordering; ?>">
								<span><?php echo $this->escape($component->name); ?></span>
							</a>			
							<?php } ?>							
					<?php endforeach ?>
                </div><!-- end .cat -->
                														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/theme/auto-suggestion-theme" component="<?php echo $this->c; ?>" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" name="name" value="Tìm kiếm" class="btnSearch" path="admin/theme/list" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   
							</th>
						</tr>
						
						<tr>
							<th width="10">#</th>
							<th width="10"></th>
							<th class="left">Tên</th>	
							<th>Đường dẫn</th>
							<th class="center">Mặc định</th>						
							<th width="60" class="center">ID</th>						
						</tr>
					</thead>
					<tbody class="rows">
							<?php $i = 0; foreach ($this->themes as $theme): $i++; if ($i % 2 != 0) {?>
							<tr class="odd gradeX" >							
								<td class="left"><?php echo $i ?></td>
								<td class="center"><input type="radio" name="select" id="<?php echo $this->escape($theme->id) ?>" component="<?php echo $this->escape($theme->component_id); ?>" /></td> 
								<td class="left"><?php echo $this->escape($theme->name) ?></td>
								<td class="left"><?php echo $this->escape($theme->path) ?></td>
								<td class="center"><img src="<?php if ($theme->is_default == 1) echo $this->dirImg; ?>/default.png" title="Mặc định" /></td>																						
								<td class="center"><?php echo $this->escape($theme->id) ?></td>
							</tr>		
							<?php } else { ?>
								<tr class="even gradeC">							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="radio" name="select" id="<?php echo $this->escape($theme->id) ?>" component="<?php echo $this->escape($theme->component_id); ?>" /></td> 
									<td class="left"><?php echo $this->escape($theme->name) ?></td>
									<td class="left"><?php echo $this->escape($theme->path) ?></td>
									<td class="center"><img src="<?php if ($theme->is_default == 1) echo $this->dirImg; ?>/default.png" title="Mặc định" /></td>																							
									<td class="center"><?php echo $this->escape($theme->id) ?></td>
								</tr>
							<?php } ?>							
							<?php endforeach ?>			
					</tbody>
				</table>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->