	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header"><h4>Menu Manager</h4></div>
			
			<div class="portlet-content">												
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
						<tr>
							<th>#</th>
							<th></th>	
							<th>Title</th>
							<th>Menu Item(s)</th>
							<th>Published</th>
							<th>Unpublished</th>
							<th>ID</th>						
						</tr>
					</thead>
					<tbody>
						<tr class="odd gradeX">							
							<td class="center">1</td>
							<td class="center"><input type="radio" name="mnu" /></td> 
							<td class="center">Main menu default</td>
							<td class="center"><a href=""><img src="<?php echo $this->dirImg; ?>/view.png" /></a></td>						
							<td class="center">6</td>
							<td class="center">-</td>
							<td class="center">1</td>
						</tr>
						<tr class="even gradeC">							
							<td class="center">2</td>
							<td class="center"><input type="radio" name="mnu" /></td> 
							<td class="center">Side menu default</td>
							<td class="center"><a href=""><img src="<?php echo $this->dirImg; ?>/view.png" /></a></td>						
							<td class="center">9</td>
							<td class="center">-</td>
							<td class="center">2</td>
						</tr>	
						<tr class="odd gradeX">							
							<td class="center">3</td>
							<td class="center"><input type="radio" name="mnu" /></td> 
							<td class="center">Main menu news</td>
							<td class="center"><a href=""><img src="<?php echo $this->dirImg; ?>/view.png" /></a></td>						
							<td class="center">21</td>
							<td class="center">-</td>
							<td class="center">3</td>
						</tr>
						<tr class="even gradeC">							
							<td class="center">4</td>
							<td class="center"><input type="radio" name="mnu" /></td> 
							<td class="center">Main menu admin</td>
							<td class="center"><a href=""><img src="<?php echo $this->dirImg; ?>/view.png" /></a></td>						
							<td class="center">10</td>
							<td class="center">-</td>
							<td class="center">4</td>
						</tr>											
					</tbody>
				</table>																																	
			</div>
		</div>
	</div><!--  end #content -->