	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header"><h4>Main menu default</h4></div>
			
			<div class="portlet-content">
												
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
						<tr>
							<th>#</th>
							<th width="5"><input type="checkbox"/></th>
							<th>Menu Item</th>
							<th>Published</th>		
							<th>Order</th>
							<th>Parent</th>
							<th>ItemID</th>					
						</tr>
					</thead>
					<tbody>
						<tr class="odd gradeX">							
							<td class="center">1</td>
							<td><input type="checkbox"/></td>
							<td class="center">Trang chủ</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/check.png" /></td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/up.png" /><img src="<?php echo $this->dirImg; ?>/down.png" /><input type="text" size="2"/></td>
							<td class="center">-</td>
							<td class="center">1</td>
						</tr>
						<tr class="even gradeC">							
							<td class="center">2</td>
							<td><input type="checkbox" /></td>
							<td class="center">Thực hiện giao dịch</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/check.png" /></td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/up.png" /><img src="<?php echo $this->dirImg; ?>/down.png" /><input type="text" size="2"/></td>
							<td class="center">-</td>
							<td class="center">1</td>
						</tr>
						<tr class="odd gradeX">							
							<td class="center">3</td>
							<td><input type="checkbox" /></td>
							<td class="center">Thống kê sàn ảo</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/check.png" /></td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/up.png" /><img src="<?php echo $this->dirImg; ?>/down.png" /><input type="text" size="2"/></td>
							<td class="center">-</td>
							<td class="center">3</td>
						</tr>
						<tr class="even gradeC">							
							<td class="center">4</td>
							<td><input type="checkbox" /></td>
							<td class="center">Thảo luận sàn ảo</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/check.png" /></td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/up.png" /><img src="<?php echo $this->dirImg; ?>/down.png" /><input type="text" size="2"/></td>
							<td class="center">-</td>
							<td class="center">4</td>
						</tr>
						<tr class="odd gradeX">							
							<td class="center">5</td>
							<td><input type="checkbox" /></td>
							<td class="center">Thể lệ sàn ảo</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/check.png" /></td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/up.png" /><img src="<?php echo $this->dirImg; ?>/down.png" /><input type="text" size="2"/></td>
							<td class="center">-</td>
							<td class="center">5</td>
						</tr>				
						<tr class="even gradeC">							
							<td class="center">6</td>
							<td><input type="checkbox" /></td>
							<td class="center">Tin tức</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/check.png" /></td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/up.png" /><img src="<?php echo $this->dirImg; ?>/down.png" /><input type="text" size="2"/></td>
							<td class="center">-</td>
							<td class="center">6</td>
						</tr>
						<tr class="odd gradeX">							
							<td class="center">7</td>
							<td><input type="checkbox" /></td>
							<td class="center">Bảng giá trưc tuyến</td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/check.png" /></td>
							<td class="center"><img src="<?php echo $this->dirImg; ?>/up.png" /><img src="<?php echo $this->dirImg; ?>/down.png" /><input type="text" size="2"/></td>
							<td class="center">-</td>
							<td class="center">7</td>
						</tr>									
					</tbody>
				</table>																																	
			</div>
		</div>
	</div><!--  end #content -->