<section id="gold-info" class="info2">
	<p id="gold" class="statics">Giá vàng 9999</p>
	<p class="right">ĐVT: tr.đ/lượng</p>
	<table width="92%" border="0px" cellspacing="0" cellpadding="0">
		<thead>
			<tr>
				<td>Loại</td>
				<td>Mua</td>
				<td>Bán</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>SBJ</td>
				<td>32.950</td>
				<td>32,970</td>
			</tr>
			<tr>
				<td>SJC</td>
				<td>32.910</td>
				<td>32,9870</td>
			</tr>
		</tbody>
	</table>
</section>

<section id="money-info" class="info2">
	<p id="money" class="statics">Tỷ giá</p>  
	<hgroup id="money-table">                      
		<table width="92%" border="0px" cellspacing="0" cellpadding="0">                           
			<tbody>
				<tr>
					<td>USD</td>
					<td>19.500</td>                                
				</tr>
				<tr>
					<td>GBP</td>
					<td>31.566</td>                                
				</tr>
				<tr>
					<td>HKD</td>
					<td>2.590</td>                                
				</tr>
				<tr>
					<td>CHF</td>
					<td>20.761</td>                                
				</tr>
				<tr>
					<td>JPY</td>
					<td>247.02</td>                                
				</tr>
				<tr>
					<td>AUD</td>
					<td>19.610</td>                                
				</tr>
				<tr>
					<td>CAD</td>
					<td>19.491</td>                                
				</tr>
					<td>SGD</td>
					<td>15.368</td>                                
				</tr>
				</tr>
					<td>EUR</td>
					<td>27.713</td>                                
				</tr>
			</tbody>
		</table>
	</hgroup>										
</section>

<div class="clear"></div>