<section id="rule-info" class="box-first">                    
	<ul class="tabs">
		<li><a href="#tab1-news">Luật chơi</a></li>
		<li><a href="#tab2-news">Hướng dẫn đặt lệnh</a></li>
		<li><a href="#tab3-news">Lịch sử giao dịch</a></li>
	</ul>
	
	<hgroup class="tab_container1">
		<article id="tab1-news" class="tab_content1">  
			<div>                      
				Khi là thành viên tham gia sàn giao dịch chứng khoán ảo, bạn sẽ phải tuân thủ luật chơi như sau:
			<ul>
				<li>Tuân theo các nguyên tắc giao dịch đã được lập trình.</li><li>Bảng xếp hạng được xếp theo thứ tự giảm dần của tỷ suất lợi nhuận trên vốn đầu tư,
					được tính theo công thức sau :
					<br /><center><b style="color:#02991D;">Tỷ suất sinh lợi trên vốn đầu tư = Lợi nhuận / Tổng vốn đầu tư đầu kỳ</b></center></li>
					<li>Mỗi tháng sẽ tiến hành reset 1 lần vào ngày cuối cùng của tháng để cơ cấu lại số dư đầu kỳ và đưa tỷ lệ tăng trưởng về 0, 
					đảm bảo sân chơi được công bằng với các thành viên vào chơi sau. Công thức tính như sau: 
					<br />
					<center><b style="color:#02991D;">Số dư đầu kỳ mới = Tiền được phép giao dịch + Tiền đang bị phong tỏa +
						Tiền quy đổi từ chứng khoán sở hữu</b>(tính theo giá đóng cửa phiên gần nhất)</center></li>

					</ul>
			</div>
			<h3 style="color:#1C1CFF;">II. NGUYÊN TẮC GIAO DỊCH</h3>
			<ol>
				<li><b style="color:#001F7F;">Nguyên tắc chung:</b><br />
					<ul>
						<li>Giao dịch mua và bán chứng khoán: chứng khoán mua (giao dịch mua) và tiền bán (giao
							dịch bán) sẽ về tài khoản lúc 16h00 ngày T+3.</li><li>Thứ tự ưu tiên đối với các loại lệnh là giá, thời gian, khối lượng.</li><li>Biểu phí giao dịch khớp lệnh là 0.3%</li><li>Số tiền bị khóa: là tổng số tiền đang bị khóa do bạn đã dùng để thực hiện giao dịch (số tiền này sẽ được trừ vào tổng giá trị tài sản sau khi khớp lệnh).</li><li>Khối lượng giao dịch phụ thuộc vào sàn giao dịch thật.</li><li>Lệnh đặt chỉ được huỷ vào phiên 2 và 3.</li><li>Mỗi Account chỉ có thể reset tài khoản 1 lần trong vòng 1 tháng.</li><li>Sàn ảo chỉ thực hiện giao dịch với tất cả chứng khoán trên sàn HOSE.</li></ul>

				</li>                               
				<li><b style="color:#001F7F;">Nguyên tắc Giao dịch khớp lệnh:</b>
					<ul>                                      
						<li><b><i>Thời gian:</i></b>
							<ul>
								<li>Thời gian đặt lệnh <b>đợt 1</b> (Khớp lệnh định kỳ xác định giá Mở cửa): <b style="color:#FF0000;">

									10h45</b> sáng hôm trước
									đến <b style="color:#FF0000;">8h45</b> sáng ngày hiện tại.
								</li>
								<li>Thời gian khớp lệnh <b>đợt 1</b>: <b style="color:#FF0000;">8h50</b> sáng.</li><li>Thời gian đặt lệnh <b>đợt 2</b> (Khớp lệnh liên tục): Từ <b style="color:#FF0000;">

									8h40</b> sáng đến <b style="color:#FF0000;">10h30</b> sáng ngày hiện tại.</li><li>Thời gian khớp lệnh <b>đợt 2</b>: Các lệnh nhập vào hệ thống trong thời gian này sẽ được khớp liên tục khi có mức giá phù hợp.</li><li>Thời gian đặt lệnh <b>đợt 3</b>: Từ <b style="color:#FF0000;">10h30</b> sáng đến <b style="color:#FF0000;">

									10h45</b> sáng ngày hiện tại.</li><li>Thời gian khớp lệnh <b>đợt 3</b>: <b style="color:#FF0000;">10h50</b> sáng.</li></ul>                                        
						</li>
						<li><b><i>Nguyên tắc khớp:</i></b>                
							<ul>
								<li>Lấy giá khớp lệnh online trên thị trường thật làm cơ sở khớp lệnh cho sàn giao dịch chứng khoán ảo.</li><li>Lệnh LIMIT của các thành viên nhập vào hệ thống sẽ được bảo lưu trong cả phiên giao dịch. 
									Trong trường hợp không khớp sẽ tự động hủy sau đợt 3.</li><li>Những lệnh không có giá xác định (ATO, MP, ATC) sẽ được hủy sau phiên khớp lệnh.</li><li>Nguyên tắc khớp lệnh "Mua": giá đặt "Mua" >= giá khớp lệnh trên thị trường thật.</li><li>Nguyên tắc khớp lệnh "Bán": giá đặt "Bán" <= giá khớp lệnh trên thị trường thật.</li></ul>
						</li>
					</ul>
				</li>

			</ol>
			<h3 style="color:#1C1CFF;">III. HƯỚNG DẪN VẮN TẮT CÁCH CHƠI CHỨNG KHOÁN ẢO</h3>
			<div> 
				- Khi đã đăng ký thành viên xong, các bạn có trong tay 1 tỉ đồng tiền ảo. Các bạn dùng 1 tỉ này để mua CK, tại phần "THỰC HIỆN GIAO
				DỊCH" ở thanh menu ngang.
			</div>
			<ol>
				<li><b style="color:#001F7F;">Mua chứng khoán:</b><br />
					<ul>

						<li>Giá limit: bạn xác nhận 1 mức giá thỏa điều kiện: giá sàn < giá đặt mua < giá trần (trần và sàn thông báo trên màn hình đặt lệnh). Nếu sàn HoSE có khớp lệnh tương xứng với giá bạn đặt, nghĩa là bạn mua được CP.</li><li>Giá ATO, ATC: bạn chấp nhận mua "bằng mọi giá" - sẽ là giá hết phiên 1 và 3 của sàn HoSE (giá mua ATO/ATC thể hiện với mức giá nào bạn cũng sẵn lòng trả để có cổ phiếu đó).</li><li>Sau khi mua, vào 16h chiều ngày giao dịch thứ 3 sau ngày mua, CK về TK bạn, Lúc đó mới có thể bán CK.</li></ul>                             
				</li>
				<li><b style="color:#001F7F;">Bán chứng khoán:</b>
					<ul>
						<li>Với những CK đã về TK (Thí dụ: mua T2, T6 bán; mua T6, T5 tuần sau bán), vào phần Đặt lệnh để bán. 
						Giá bán là giá limit do bạn chọn, hoặc ATO, ATC ... là giá thị trường (bán ATO/ATC nghĩa là giá nào bạn cũng bán CP để thu tiền về). 
						16 gờ chiều ngày giao dịch thứ 3 sau khi lệnh bán khớp, tiền về TK.</li></ul>                                           
				</li>
				<li><b style="color:#001F7F;">Giá ATO/ATC,limit:</b><br />
					<ul>
						<li>Tất cả đều lớn hơn hoặc bằng giá sàn, nhỏ hơn hoặc bằng giá trần.</li></ul>
				</li>
			</ol>          		
		</article>
		<article id="tab2-news" class="tab_content1">
			
		</article>
		<article id="tab3-news" class="tab_content1">
							
		</article>
	</hgroup>
</section>