<section class="news-box">
	<ul class="tab">
		<li class="first"><a>Kiến thức cơ bản</a></li>
		<li><a>Kiến thức đầu tư</a></li>            
	</ul>           
	<div class="newcontent">
		<article class="main left">
			<img src="files/news/30102010/chungkhoan_xvongcrp911468777small.jpg" class="left" width="130" height="100"/>
			<hgroup>
				<h2>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</h2>
				<p>Sở Giao dịch Chứng khoán Hà Nội (HNX) thông báo 8/11 là ngày giao dịch không hưởng quyền, ngày 10/11 là thời hạn đăng ký cuối cùng để tạm ứng cổ tức năm 2010 bằng tiền Ngân hàng Thương mại Cổ phần Á châu (mã ACB-HNX).</p>
			</hgroup>
			<div class="clear"></div>
		</article>
		<article class="right">
		   <ul class="list">
				<li><a>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a></li>
				<li><a>Dược Hà Tây kiến nghị truy tiếp DVD “tội làm giá” </a></li>
				<li><a>HBC: đầu tư dự án tại Nhà Bè và triển khai ép cọc khu chung cư Bình An</a></li>
		   </ul> 
		</article>
		<div class="clear"></div>
	</div>
</section>