	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item widget">
				<h4>Thêm widget</h4>
				<div class="float-right">
					<a href="<?php echo $_SESSION['temp']; ?>"><input type="button" id="close" value="Đóng" /></a>							
				</div>				
			</div>
			
			<div class="portlet-content">
				<?php if (isset($this->message)) {?>
					<div class="message">
						<?php echo $this->message; ?>
					</div>					
				<?php } ?>				
				<img src="<?php echo $this->dirImg;?>/loading2.gif" class="hide1" />
				
				<div class="addContentDyn">
					<form class="form label-inline">
								<div class="field"><label for="wname">Widget name </label> <input class="wname" size="60" type="text" class="medium" /><div class="message1" style="display: inline;"></div></div>				
								<div class="field"><label for="walias">Alias </label> <input class="walias" size="60" type="text" class="medium" /><div class="message2" style="display: inline;"></div></div>
								<div class="field"><label for="wpath">Path</label> <input class="wpath" size="60" type="text" class="medium" /></div>
								
								<div class="field">
									<label for="type">Publish</label>
	
									<select id="type" class="medium wpublished">														
										<option value="0">Không</option>								
										<option selected="selected" value="1">Có</option>																				
									</select>
								</div>
								
								<div class="field">
									<label for="type">Component</label>
	
									<select id="type" class="medium ListDynChange wcomponent" path="/admin/page/get-page-by-component" dest="wpage">									
											<option value="0">Select component</option>
											<?php foreach($this->components as $component): ?>
												<option value="<?php echo $component->id; ?>"><?php echo $component->name;?></option>
											<?php endforeach?>													
									</select>									
								</div>																
								
								<div class="controlset field">
									<span class="label">Page</span>	
									<div class="controlset-pad">																			
										<div class="wpage"></div>																				
									</div>								
										
								</div>																																		
								
								<div class="buttonrow" style="margin-right: 10px;">								
									<button class="btn btn-grey next" url="admin/widget/add-cont">Next</button>
								</div>

															
					</form>	
				</div>			
																																
			</div><!--  end .portlet-content -->
		</div>
	</div><!--  end #content -->