	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item widget">
				<h4>Sửa widget</h4>
				<div class="float-right">
					<a class="minibutton btn close" name="loại tin" back="<?php echo $_SESSION['temp']; ?>">
						<span><span class="icon close"></span>Đóng</span>
					</a>							
				</div>				
			</div>
			
			<div class="portlet-content">
				<?php if (isset($this->message)) {?>
					<div class="message">
						<?php echo $this->message; ?>
					</div>					
				<?php } ?>				
				<img src="<?php echo $this->dirImg;?>/loading.gif" class="hide" />
				<img src="<?php echo $this->dirImg;?>/loading2.gif" class="hide1" />
				
				<div class="addContentDyn">
					<form class="form label-inline">
								<div class="field"><label for="wname">Widget name </label> <input class="wname" size="24" type="text" class="medium" value="<?php echo $this->widget['name']; ?>"/><div class="message1" style="display: inline;"></div></div>				
								<div class="field"><label for="wpath">Path</label> <input class="wpath" size="24" type="text" class="medium" value="<?php echo $this->widget['path']; ?>"/><div class="message2" style="display: inline;"></div></div>
								<div class="field"><label for="wpath">Alias</label> <input class="walias" size="60" type="text" class="medium" value="<?php echo $this->widget['alias']; ?>"  /></div>															
								
								<div class="field">
									<label for="type">Publish</label>
	
									<select id="type" class="medium wpublished">																																	
										<option value="0" <?php if ($this->widget['published'] == 0) echo 'selected="selected"';?> >Không</option>								
										<option value="1" <?php if ($this->widget['published'] == 1) echo 'selected="selected"';?> >Có</option>																				
									</select>
								</div>
								
								<div class="field">
									<label for="type">Page</label>
	
									<select id="type" class="medium wpage">				
										<?php foreach ($this->pages as $page): 
											if ($this->widget['page_id'] == $page->id) $select = 'select="selected"';
										?>
											<option  <?php echo $select; ?> value="<?php echo $page->id;?>"><?php echo $page->name;?></option>
										<?php endforeach ?>																																													
									</select>
								</div>
																																							
								<div class="buttonrow" style="margin-right: 10px;">								
									<button class="btn btn-grey next2" url="admin/widget/edit-cont" wid="<?php echo $this->widget['widget_id']; ?>" pwid="<?php echo $this->pageWidgetId; ?>" componentId="<?php echo $this->componentId; ?>" position="<?php echo $this->widget['position']; ?>" ordering="<?php echo $this->widget['ordering'];?>" >Next</button>
								</div>								
															
					</form>	
				</div>			
																																
			</div><!--  end .portlet-content -->
		</div>
	</div><!--  end #content -->