<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item module">
			<h4>Xem module</h4>
			<div class="float-right">											
				<div class="global" id="<?php echo $this->module->id; ?>" path1="admin/module/edit-module/id/<?php echo $this->module->id ?>/" path2="admin/module/delete-module" back="<?php echo $_SESSION['temp']; ?>"></div>																																																																
	            <?php 								
	 				foreach ($this->button2 as $button) {
	 					echo stripslashes($button['button2']);
	 				}	 									 				
				?>	
				<a class="minibutton btn close">
						<span><span class="icon close"></span>Đóng</span>
				</a>							
			</div>				
		</div>
		
		<div class="portlet-content">	
			<?php if (null != $this->module) {?>								 							                													
			<table cellpadding="0" cellspacing="0" border="0" class="display">
				<tr>
					<td width="90"><b>Module name:</b></td>
					<td><?php echo $this->module->name; ?></td>
				</tr>
				<tr>
					<td><b>Description:</b></td>
					<td><?php echo $this->module->description; ?></td>
				</tr>	
				<tr>
					<td><b>Priviles:</b></td>					
					<td><?php foreach ($this->privilegeTypes as $privilegeType) echo $privilegeType['name'] . '<br/>'; ?></td>
				</tr>							
				<tr>
					<td><b>Published:</b></td>
					<?php $published = ($this->module->published == 1) ? "Yes" : "No"; ?>
					<td><?php echo $published; ?></td>
				</tr>
			</table>
			<?php } ?>																																	
		</div>
	</div>			
	
</div><!--  end #content -->