<div >	
	<form action="" method="post" class="form label-inline">																								
		<div class="field">
			<label for="type">Position</label>

			<select name="position" id="type" class="medium wposition selectChangeDouble" dest="wordering" path="admin/widget/get-order-by-position" data="<?php echo $this->listPageId; ?>">				
				<option selected="selected" value="Header">Header</option>																												
				<option value="Left">Left</option>
				<option value="Right">Right</option>
				<option value="Statics">Statics</option>
				<option value="Footer">Footer</option>
			</select>
		</div>
		
		<?php if ($this->orders != '') {?>
		<div class="field">
			<label for="type">Ordering</label>

			<select name="ordering" id="type" class="medium wordering">				
				<?php 
					for ($i = 1; $i <= count($this->orders); $i++) {		
						echo '<option value="'.$this->orders[$i] . '">' .$this->orders[$i] . '</option>';
					}
					$max = count($this->orders);
					$j = $this->orders[$max] + 1;
					echo '<option selected="selected" value="'.$j . '">' .$j . '</option>';						
				?>			 																																
			</select>			
		</div>
		<?php } ?>
		
		<div class="buttonrow">								
			<button class="btn btn-orange" name="ok">OK</button>
		</div>				
		<input type="hidden" name="name" value="<?php echo $this->name;?>" />											
		<input type="hidden" name="path" value="<?php echo $this->path;?>" />		
		<input type="hidden" name="listPageId" value="<?php echo $this->listPageId;?>" />
		<input type="hidden" name="published" value="<?php echo $this->published;?>" />
		<input type="hidden" name="alias" value="<?php echo $this->alias;?>" />
	</form>	
</div>	