<div >	
	<form action="" method="post" class="form label-inline">																								
		<div class="field">
			<label for="type">Position</label>

			<select name="position" id="type" class="medium wposition selectChangeDouble" dest="wordering" path="admin/widget/get-order-by-position" data="<?php echo $this->pageId; ?>" positionCurrent="<?php echo $this->position; ?>" >				
				<option value="Header" <?php if ($this->position == "Header") echo 'selected="selecteds"';?>>Header</option>																												
				<option value="Left" <?php if ($this->position == "Left") echo 'selected="selecteds"';?>>Left</option>
				<option value="Right" <?php if ($this->position == "Right") echo 'selected="selecteds"';?>>Right</option>
				<option value="Statics" <?php if ($this->position == "Statics") echo 'selected="selecteds"';?>>Statics</option>
				<option value="Footer" <?php if ($this->position == "Footer") echo 'selected="selecteds"';?>>Footer</option>
			</select>
		</div>
		
		<div class="field">
			<label for="type">Ordering</label>

			<select name="ordering" id="type" class="medium wordering">				
				<?php 																					
					for ($i = 1; $i <= count($this->orders); $i++) {																								
				?>
					<option value="<?php echo $this->orders[$i]; ?>" <?php if ($this->ordering == $this->orders[$i]) echo 'selected="selected"';	 ?> ><?php echo $this->orders[$i]; ?></option>
				<?php }?>																			 																																
			</select>			
		</div>
									
		<input type="hidden" name="name" value="<?php echo $this->name;?>" />											
		<input type="hidden" name="alias" value="<?php echo $this->alias;?>" />
		<input type="hidden" name="path" value="<?php echo $this->path;?>" />				
		<input type="hidden" name="pageId" value="<?php echo $this->pageId;?>" />
		<input type="hidden" name="widgetId" value="<?php echo $this->widgetId;?>" />		
		<input type="hidden" name="pageWidgetId" value="<?php echo $this->pageWidgetId;?>" />
		<input type="hidden" name="published" value="<?php echo $this->published;?>" />
		<input type="hidden" name="positionCurrent" value="<?php echo $this->position; ?>">
		<input type="hidden" name="orderingCurrent" value="<?php echo $this->ordering; ?>">
		
		<div class="buttonrow">								
			<button class="btn btn-orange" name="ok">OK</button>
		</div>	
	</form>	
</div>		