	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item page">
				<h4>Quản lý page</h4>
				<div class="float-right">	
					<div class="global" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>"></div>																								
					<a class="minibutton btn add" path="admin/page/add">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="page" path="admin/page/edit" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>
					<a class="minibutton btn publish" name="page" mapper="pageMapper" path="admin/page/publish">
						<span><span class="icon publish"></span>Published</span>
					</a>
					<a class="minibutton btn unpublish" name="page" mapper="pageMapper" path="admin/page/unpublish">
						<span><span class="icon unpublish"></span>Unpublished</span>
					</a>
					<a class="minibutton btn deleteall" name="page" path="admin/page/delete">
						<span><span class="icon delete"></span>Xóa</span>
					</a>					
				</div>				
			</div>
			
			<div class="portlet-content">				 			
				<div class="cat">	
					<?php $i = 0;foreach ($this->components as $component): $i++;?>
							<?php if ($this->c == $component->id) { ?>	
								<a class="active" href="admin/page/list/component/<?php echo $component->id; ?>/"  order="<?php echo $component->ordering; ?>">
									<span><?php echo $this->escape($component->name); ?></span>
								</a>							
							<?php } else { ?>				    	
							<a class="minibutton" href="admin/page/list/component/<?php echo $component->id; ?>/" order="<?php echo $component->ordering; ?>">
								<span><?php echo $this->escape($component->name); ?></span>
							</a>			
							<?php } ?>							
					<?php endforeach ?>
                </div><!-- end .cat -->
                														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/page/auto-suggestion-page" component="<?php echo $this->c; ?>" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" value="Tìm kiếm" name="title" class="btnSearch" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   							
						</tr>
						
						<tr>
							<th width="10">#</th>
							<th width="10"><input type="checkbox" id="select_all"></th>	
							<th width="500">Title</th>
							<th width="300">Name</th>							
							<th width="100" class="center">Published</th>							
							<th width="300" class="center">Home Page</th>
							<th width="100" class="right">ID</th>							
						</tr>
					</thead>
					<tbody class="rows">
							<?php $i = 0; foreach ($this->pages as $page): $i++; if ($i % 2 != 0) {?>
								<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="checkbox" name="select" value="<?php echo $this->escape($page->id) ?>" component="<?php echo $this->escape($page->component_id); ?>" id="<?php echo $this->escape($page->id) ?>" /></td> 
									<td class="left"><?php echo $this->escape($page->title) ?></td>
									<td class="left"><?php echo $this->escape($page->name) ?></td>								
									<td class="center">
										<?php if ($page->published == 1) {
											$title = "Click vào để ẩn page";
											$img =  $this->dirImg . '/AnHien_1.png'; 
											} else {
											$title = "Click vào để hiện page";	
											$img = $this->dirImg . '/AnHien_0.png';
											}
										?>
										<img name="page" mapper="pageMapper" path="admin/page/set-publish" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($page->id) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>
									<td class="center"><img src="<?php if ($page->is_home == 1) echo $this->dirImg; ?>/default.png" /></td>																						
									<td class="right"><?php echo $this->escape($page->id) ?></td>
								</tr>		
							<?php } else { ?>
								<tr class="even gradeC">							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="checkbox" name="select" value="<?php echo $this->escape($page->id) ?>" component="<?php echo $this->escape($page->component_id); ?>" id="<?php echo $this->escape($page->id) ?>"/></td> 
									<td class="left"><?php echo $this->escape($page->title) ?></td>
									<td class="left"><?php echo $this->escape($page->name) ?></td>								
									<td class="center">
										<?php if ($page->published == 1) {
											$title = "Click vào để ẩn page";
											$img =  $this->dirImg . '/AnHien_1.png'; 
											} else {
											$title = "Click vào để hiện page";	
											$img = $this->dirImg . '/AnHien_0.png';
											}
										?>
										<img name="page" mapper="pageMapper" path="admin/page/set-publish" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($page->id) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>
									<td class="center"><img src="<?php if ($page->is_home == 1) echo $this->dirImg; ?>/default.png" /></td>																						
									<td class="right"><?php echo $this->escape($page->id) ?></td>
								</tr>													
							<?php } endforeach ?>			
					</tbody>
				</table>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->