<section class="breadcum" style="margin-bottom:20px">
	<a class="left cat">Tìm kiếm</a>
	<hgroup class="right" style="width:200px !important;">		
		<span class="Timer right"></span>                    
	</hgroup>
	<div class="clear"></div>
</section>
<?php 
	foreach($this->news as $new) {  
		$alias = $this->categoryMapper->getAliasByArticle($new['id']);
	  	$link = 'aliasP/' . $alias['parent_alias'] . '/aliasS/' . $alias['sub_alias'] . '/alias/' . $new['alias'];                
?>
<section class="news-box-cat">
	<?php if (null != $new['image']) { ?>
	<a href="index.php/news/index/detail/<?php echo $link;?>"><img src="<?php echo $new['image'];?>" class="left"/></a>
	<?php } ?>
	<hgroup>
		<a href="index.php/news/index/detail/<?php echo $link;?>"><?php echo $new['title']; ?></a>
		<br />
		<label class="c-time">
			<?php echo Cloud_Model_Utli_CloudUtli::showTime($new['create_date']);?>
		</label>  |  
		<label class="c-date">
			<?php echo Cloud_Model_Utli_CloudUtli::showDay($new['create_date']);?>
		</label>
		<br />
		<p>
			<?php echo $new['summarize'];?><br />			
			<?php 										
				if ($relatives != '') {	 echo "&gt;";								
					foreach ($relatives as $relative) {
			?>
						<a href=""><?php echo $relative->title;?></a> /
			<?php }} ?>
		</p>
	</hgroup>
	<div class="clear"></div>
</section> 
<?php } ?>
 <p id="paging">
	<?php echo $this->newsMapper->showPaging($this->page, $this->key, $this->number);?>
</p>
