<section id="expert">
	<div class="header-panel">
		<h2>Nhận định chuyên gia</h2>
	</div>
	
	<article>
		<h2><a href="news/index/detail"><?php echo $new[0]['title'];?></a></h2>
		<a href="news/index/detail"><img src="<?php echo $new[0]['image'];?>" class="left" width="120" height="95"/></a>
		<p class="right"><?php echo $new[0]['summarize'];?></p>
		<div class="clear"></div>
	</article>
</section>