<section id="expert">
	<div class="header-panel">
		<h2>Nhận định chuyên gia</h2>
	</div>
	
	<article>
		<h2><a href="news/index/detail">"Chuyện làm giá" sẽ làm nóng nghị trường </a></h2>
		<a href="news/index/detail"><img src="files/news/30102010/chungkhoan_eocqoaes242632009small.jpg" class="left" width="120" height="95"/></a>
		<p class="right">Luật sửa đổi, bổ sung một số điều của Luật Chứng khoán sắp được kỳ họp thứ 8 Quốc hội khóa 12 đưa ra thảo luận. Các thành viên...</p>
		<div class="clear"></div>
	</article>
</section>