<section class="news-box-cat">
	<a><img src="files/news/30102010/130.jpg" class="left"/></a>
	<hgroup>
		<a>Công ty của ông Đặng Thành Tâm bị phạt 80 triệu đồng</a>
		<br /><label class="c-time">01:24</label>  |  <label class="c-date">28/10/2010</label><br />
		<p>
			Ủy ban Chứng khoán vừa công bố quyết xử định phạt Công ty Khoáng sản Sài Gòn - Quy Nhơn do vi phạm quy chế công bố thông tin..<br />
			&gt; <a>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a>
		</p>
	</hgroup>
	<div class="clear"></div>
</section>  

<section class="news-box-cat">
	<a><img src="files/news/30102010/2.jpg" class="left"/></a>
	<hgroup>
		<a>Đại gia chứng khoán 'trốn' cổ phiếu </a>
		<br /><label class="c-time">01:24</label>  |  <label class="c-date">28/10/2010</label><br />
		<p>
			Không tìm thấy cơ hội lướt sóng ngắn hạn, nhiều nhà đầu tư lớn bỏ sàn chứng khoán đi du lịch nước ngoài. Có người chọn việc ở nhà làm osin toàn thời gian để tránh việc “táy máy” mua vào, bán ra các loại cổ phiếu.
		</p>
	</hgroup>
	<div class="clear"></div>
</section>

<section class="news-other">
	<p>
		<span>Các tin khác</span>
	</p>
	<ul>
		<li><a>'Nhà đầu tư chứng khoán dài hạn có thể bắt đầu giải ngân' <label>(24/10)</label></a></li>
		<li><a>Chứng khoán kéo dài những phiên giao dịch ảm đạm <label>(23/10</label></a></li>
		<li><a>Vn-Index bất ngờ bật xanh cuối phiên <label>(22/10)</label></a></li>
		<li><a>Chứng khoán gượng dậy sau phiên giảm sâu <label>(21/10</label></a></li>
		<li><a>ACB: Trả cổ tức năm 2010 bằng tiền <label>(21/10</label></a></li>
	</ul>
	<div class="continue">
		<a>Xem tiếp...</a>
	</div>
</section>  