<script type="text/javascript" language="JavaScript" src="http://vnexpress.net/Service/Gold_Content.js"></script>
 <section id="gold-info">
		<p id="gold" class="statics">Giá vàng 9999</p>
		<p class="right">ĐVT: tr.đ/lượng</p>
		<table width="92%" border="0px" cellspacing="0" cellpadding="0">
			<thead>
				<tr>
					<td>Loại</td>
					<td>Mua</td>
					<td>Bán</td>
				</tr>
			</thead>
			<tbody>
				<script type="text/javascript" language="JavaScript">
                   document.write("<tr><td>SBJ</td><td>" + vGoldSbjBuy + "</td><td>" + vGoldSbjSell + "</td></tr>");
                   document.write("<tr><td>SJC</td><td>" + vGoldSjcBuy + "</td><td>" + vGoldSjcSell + "</td></tr>");
				</script>	
			</tbody>
		</table>
	</section>