<style type="text/css">
		body, html, iframe, #ckfinder {
			height: 400px;
		}
	</style>
<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item file-manager">
			<h4>File Manager</h4>						
		</div>
		
		<div class="portlet-content">
			<div id="ckfinder"></div>
			<script type="text/javascript">
				(function()
				{
						var config = {
						};
						var get = CKFinder.tools.getUrlParam;
						var getBool = function( v )
						{
							var t = get( v );
				
							if ( t === null )
								return null;
				
							return t == '0' ? false : true;
						};
				
						var tmp;
						if ( tmp = get( 'basePath' ) )
							CKFINDER.basePath = tmp;
				
						if ( tmp = get( 'startupPath' ) )
							config.startupPath = decodeURIComponent( tmp );
				
						config.id = get( 'id' ) || '';
				
						if ( ( tmp = getBool( 'rlf' ) ) !== null )
							config.rememberLastFolder = tmp;
				
						if ( ( tmp = getBool( 'dts' ) ) !== null )
							config.disableThumbnailSelection = tmp;
				
						if ( tmp = get( 'data' ) )
							config.selectActionData = tmp;
				
						if ( tmp = get( 'tdata' ) )
							config.selectThumbnailActionData = tmp;
				
						if ( tmp = get( 'type' ) )
							config.resourceType = tmp;
				
						if ( tmp = get( 'skin' ) )
							config.skin = tmp;
				
						if ( tmp = get( 'langCode' ) )
							config.language = tmp;
				
						// Try to get desired "File Select" action from the URL.
						var action;
						if ( tmp = get( 'CKEditor' ) )
						{
							if ( tmp.length )
								action = 'ckeditor';
						}
						if ( !action )
							action = get( 'action' );
				
						var parentWindow = ( window.parent == window )
							? window.opener : window.parent;
				
						switch ( action )
						{
							case 'js':
								var actionFunction = get( 'func' );
								if ( actionFunction && actionFunction.length > 0 )
									config.selectActionFunction = parentWindow[ actionFunction ];
				
								actionFunction = get( 'thumbFunc' );
								if ( actionFunction && actionFunction.length > 0 )
									config.selectThumbnailActionFunction = parentWindow[ actionFunction ];
								break ;
				
							case 'ckeditor':
								var funcNum = get( 'CKEditorFuncNum' );
								if ( parentWindow['CKEDITOR'] )
								{
									config.selectActionFunction = function( fileUrl, data )
									{
										parentWindow['CKEDITOR'].tools.callFunction( funcNum, fileUrl, data );
									};
				
									config.selectThumbnailActionFunction = config.selectActionFunction;
								}
								break;
				
							default:
								if ( parentWindow && parentWindow['FCK'] && parentWindow['SetUrl'] )
								{
									action = 'fckeditor' ;
									config.selectActionFunction = parentWindow['SetUrl'];
				
									if ( !config.disableThumbnailSelection )
										config.selectThumbnailActionFunction = parentWindow['SetUrl'];
								}
								else
									action = null ;
						}
				
						config.action = action;
				
						// Always use 100% width and height when nested using this middle page.
						config.width = config.height = '100%';
				
						var ckfinder = new CKFinder( config );
						ckfinder.replace( 'ckfinder', config );
				})();
				</script>																																				
		</div><!--  end .portlet-content -->
	</div>									
</div><!--  end #content -->