<section id="stock-info">                    
	<ul class="tabs">
		<li><a href="#tab1-stock">Bảng xếp hạng</a></li>
		<li><a href="#tab2-stock">Thống kê chứng khoán</a></li>
	</ul>
	
	<hgroup class="tab_container2">
		<article id="tab1-stock" class="tab_content2">
			<p>Tháng :10/2010</p>
			<table width="100%">
				<thead>
					<tr>
						<td>Hạng</td>
						<td>Nhà đầu tư</td>
						<td>Tổng tiền</td>
						<td>Số dư đầu kỳ</td>
						<td>Tỷ suất sinh lợi</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td align="center">1</td>
						<td align="left">linhnn</td>
						<td align="right">1,159,001,701</td>
						<td align="right">1,000,000,000</td>
						<td align="right">15.90%</td>
					</tr>
					<tr>
						<td align="center">2</td>
						<td align="left">phucdd</td>
						<td align="right">1,151,570,615</td>
						<td align="right">1,000,000,000</td>
						<td align="right">15.16%</td>
					</tr>
					<tr>
						<td align="center">3</td>
						<td align="left">phuongtp</td>
						<td align="right">1,644,453,121</td>
						<td align="right">1,440,853,121</td>
						<td align="right">14.13%</td>
					</tr>
					<tr>
						<td align="center">4</td>
						<td align="left">nghiepth</td>
						<td align="right">1,466,915,455</td>
						<td align="right">1,285,315,455</td>
						<td align="right">14.13%</td>
					</tr>
					<tr>
						<td align="center">1</td>
						<td align="left">linhnn</td>
						<td align="right">1,159,001,701</td>
						<td align="right">1,000,000,000</td>
						<td align="right">15.90%</td>
					</tr>
					<tr>
						<td align="center">2</td>
						<td align="left">phucdd</td>
						<td align="right">1,151,570,615</td>
						<td align="right">1,000,000,000</td>
						<td align="right">15.16%</td>
					</tr>
					<tr>
						<td align="center">3</td>
						<td align="left">phuongtp</td>
						<td align="right">1,644,453,121</td>
						<td align="right">1,440,853,121</td>
						<td align="right">14.13%</td>
					</tr>
					<tr>
						<td align="center">4</td>
						<td align="left">nghiepth</td>
						<td align="right">1,466,915,455</td>
						<td align="right">1,285,315,455</td>
						<td align="right">14.13%</td>
					</tr>
				</tbody>
			</table>
		</article>
		<article id="tab2-stock" class="tab_content2">
			<p>Tháng :10/2010</p>
			<table width="100%">
				<thead>
					<tr>
						<td>Mã CK</td>
						<td>Giá trần</td>
						<td>Giá sàn</td>
						<td>Giá TC</td>
						<td>SL Khớp</td>
						<td>Giá trị</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td align="center">AGR</td>
						<td align="right">13,800</td>
						<td align="right">12,600</td>
						<td align="right">13,200</td>
						<td align="right">61,580</td>
						<td align="right">783,072,000</td>
					</tr>
					<tr>
						<td align="center">ANV</td>
						<td align="right">17,000</td>
						<td align="right">15,400</td>
						<td align="right">16,200</td>
						<td align="right">31,000</td>
						<td align="right">496,397,000</td>
					</tr>
					<tr>
						<td align="center">ASM</td>
						<td align="right">64,500</td>
						<td align="right">58,500</td>
						<td align="right">61,500</td>
						<td align="right">22,400</td>
						<td align="right">1,345,960,000</td>
					</tr>
					<tr>
						<td align="center">DPM</td>
						<td align="right">37,200</td>
						<td align="right">33,800</td>
						<td align="right">35,500</td>
						<td align="right">30,800</td>
						<td align="right">1,086,412,000</td>
					</tr>
				</tbody>
			</table>
		</article>
	</hgroup>             
</section>