<section id="stock-info">                    
	<ul class="tabs">
		<li><a href="#tab1-stock">Bảng xếp hạng</a></li>
		<li><a href="#tab2-stock">Thống kê chứng khoán</a></li>
	</ul>
	
	<hgroup class="tab_container2">
		<article id="tab1-stock" class="tab_content2">
			<p>Tháng :10/2010</p>
			<table width="100%" cellpadding="0" cellspacing="0">
				<thead>
					<tr>
						<td align="left">Hạng</td>
						<td align="center">Nhà đầu tư</td>
						<td align="center">Tổng tiền</td>
						<td align="center">Số dư đầu kỳ</td>
						<td align="right">Tỷ suất sinh lợi</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td align="left">1</td>
						<td align="center">linhnn</td>
						<td align="center">1,159,001,701</td>
						<td align="center">1,000,000,000</td>
						<td align="right">15.90%</td>
					</tr>
					<tr>
						<td align="left">1</td>
						<td align="center">linhnn</td>
						<td align="center">1,159,001,701</td>
						<td align="center">1,000,000,000</td>
						<td align="right">15.90%</td>
					</tr>
					<tr>
						<td align="left">1</td>
						<td align="center">linhnn</td>
						<td align="center">1,159,001,701</td>
						<td align="center">1,000,000,000</td>
						<td align="right">15.90%</td>
					</tr>
					<tr>
						<td align="left">1</td>
						<td align="center">linhnn</td>
						<td align="center">1,159,001,701</td>
						<td align="center">1,000,000,000</td>
						<td align="right">15.90%</td>
					</tr>															
				</tbody>
			</table>
		</article>
		<article id="tab2-stock" class="tab_content2">
			<p>Tháng :10/2010</p>
			<table width="100%" cellpadding="0" cellspacing="0">
				<thead>
					<tr>
						<td align="left">Mã CK</td>
						<td align="center">Giá trần</td>
						<td align="center">Giá sàn</td>
						<td align="center">Giá TC</td>
						<td align="center">SL Khớp</td>
						<td align="right">Giá trị</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td align="left">AGR</td>
						<td align="center">13,800</td>
						<td align="center">12,600</td>
						<td align="center">13,200</td>
						<td align="center">61,580</td>
						<td align="right">783,072,000</td>
					</tr>	
					<tr>
						<td align="left">AGR</td>
						<td align="center">13,800</td>
						<td align="center">12,600</td>
						<td align="center">13,200</td>
						<td align="center">61,580</td>
						<td align="right">783,072,000</td>
					</tr>
					<tr>
						<td align="left">AGR</td>
						<td align="center">13,800</td>
						<td align="center">12,600</td>
						<td align="center">13,200</td>
						<td align="center">61,580</td>
						<td align="right">783,072,000</td>
					</tr>
					<tr>
						<td align="left">AGR</td>
						<td align="center">13,800</td>
						<td align="center">12,600</td>
						<td align="center">13,200</td>
						<td align="center">61,580</td>
						<td align="right">783,072,000</td>
					</tr>																			
				</tbody>
			</table>
		</article>
	</hgroup>             
</section>