<p class="mess_ajax">Cổ phiếu nóng hôm nay</p>
<table id="hotStock" class="hot_stock_table click" width="100%" border="1"  cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<td>Mã CK</td>
			<td>KLGD</td>
			<td>GTGD</td>
		</tr>		
	</thead>
	<tbody>
		<tr>
			<td class="stock_with_popup"><a>CI</a></td>
			<td>23,680</td>
			<td>796,978,000</td>
		</tr>
		<tr>
			<td class="stock_with_popup"><a>AAA</a></td>
			<td>21,450</td>
			<td>725,875,000</td>		
		</tr>
		<tr>
			<td class="stock_with_popup"><a>DPM</a></td>
			<td>18,930</td>
			<td>767,781,000</td>
		</tr>
		<tr>
			<td class="stock_with_popup"><a>ACB</a></td>
			<td>18,700</td>
			<td>504,750,000</td>
		</tr>
		<tr>
			<td class="stock_with_popup"><a>ANV</a></td>
			<td>16,000</td>
			<td>209,600,000</td>
		</tr>					
	</tbody>
</table>