<script type="text/javascript"
 src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
   		$(".hot_stock_table tbody tr:even").css({"background" : "#F4FFF4 repeat", "color" : "#008000", "font-weight" : "bold", "font-style" : "italic", "font-size" : "14px"}); 
	   
		$(".hot_stock_table tbody tr:odd").css({"color" : "#C46200", "font-weight" : "bold", "font-style" : "italic", "font-size" : "14px"});
  });
</script>

<p class="mess_ajax">Cổ phiếu nóng hôm nay</p>
<table id="hotStock" class="hot_stock_table" width="100%" border="1"  cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<td> Mã CK</td>
			<td>KLGD</td>
			<td>GTGD</td>
		</tr>		
	</thead>
	<tbody>
		<tr>
			<td>CI</td>
			<td>23,680</td>
			<td>796,978,000</td>
		</tr>
		<tr>
			<td>AAA</td>
			<td>21,450</td>
			<td>725,875,000</td>		
		</tr>
		<tr>
			<td>DPM</td>
			<td>18,930</td>
			<td>767,781,000</td>
		</tr>
		<tr>
			<td>ACB</td>
			<td>18,700</td>
			<td>504,750,000</td>
		</tr>
		<tr>
			<td>ANV</td>
			<td>16,000</td>
			<td>209,600,000</td>
		</tr>					
	</tbody>
</table>