<p class="mess_ajax">Thống kê giao dịch sàn ảo</p>
<table id="marketStatics" border="1" width="100%" cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<td rowspan="2">Ngày</td>
			<td colspan="3">Lệnh đặt</td>
			<td colspan="3">Lệnh khớp</td>
			<td colspan="3">User đặt lệnh</td>
			<td colspan="2">Giá trị khớp lệnh</td>
		</tr>
		<tr>
			<td>Mua</td>
			<td>Bán</td>
			<td>Tổng số</td>
			<td>Được khớp</td>
			<td>Không khớp</td>
			<td>Tỷ lệ khớp</td>
			<td>Tổng số</td>
			<td>Được khớp</td>
			<td>Tỷ lệ khớp</td>
			<td>Khối lượng</td>
			<td>Giá trị</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>17-12-2010</td>
			<td>381</td>
			<td>169</td>
			<td>550</td>
			<td>442</td>
			<td>108</td>
			<td>80.36%</td>
			<td>202</td>
			<td>180</td>
			<td>89.11%</td>
			<td>436,830</td>
			<td>11,986,397,000.00</td>
		</tr>
		<tr>
			<td>17-12-2010</td>
			<td>381</td>
			<td>169</td>
			<td>550</td>
			<td>442</td>
			<td>108</td>
			<td>80.36%</td>
			<td>202</td>
			<td>180</td>
			<td>89.11%</td>
			<td>436,830</td>
			<td>11,986,397,000.00</td>
		</tr>
		<tr>
			<td>17-12-2010</td>
			<td>381</td>
			<td>169</td>
			<td>550</td>
			<td>442</td>
			<td>108</td>
			<td>80.36%</td>
			<td>202</td>
			<td>180</td>
			<td>89.11%</td>
			<td>436,830</td>
			<td>11,986,397,000.00</td>
		</tr>
		<tr>
			<td>17-12-2010</td>
			<td>381</td>
			<td>169</td>
			<td>550</td>
			<td>442</td>
			<td>108</td>
			<td>80.36%</td>
			<td>202</td>
			<td>180</td>
			<td>89.11%</td>
			<td>436,830</td>
			<td>11,986,397,000.00</td>
		</tr>
		<tr>
			<td>17-12-2010</td>
			<td>381</td>
			<td>169</td>
			<td>550</td>
			<td>442</td>
			<td>108</td>
			<td>80.36%</td>
			<td>202</td>
			<td>180</td>
			<td>89.11%</td>
			<td>436,830</td>
			<td>11,986,397,000.00</td>
		</tr>
		<tr>
			<td>17-12-2010</td>
			<td>381</td>
			<td>169</td>
			<td>550</td>
			<td>442</td>
			<td>108</td>
			<td>80.36%</td>
			<td>202</td>
			<td>180</td>
			<td>89.11%</td>
			<td>436,830</td>
			<td>11,986,397,000.00</td>
		</tr>
		<tr>
			<td>17-12-2010</td>
			<td>381</td>
			<td>169</td>
			<td>550</td>
			<td>442</td>
			<td>108</td>
			<td>80.36%</td>
			<td>202</td>
			<td>180</td>
			<td>89.11%</td>
			<td>436,830</td>
			<td>11,986,397,000.00</td>
		</tr>												
	</tbody>
</table>

<p class="mess_ajax">Biểu đồ khối lượng giao dịch trong 10 ngày</p>
	<div class="center2">
	<img src="<?php echo $this->dirImg; ?>/sample/chart1.png" />
</div>

<p class="mess_ajax" style="line-height: normal;">Biểu đồ 10 cổ phiếu giao dịch nhiều nhất trong ngày 17-12-2010</p>
	<div class="center2">
	<img src="<?php echo $this->dirImg; ?>/sample/chart2.png" />
</div>
