<div class="center hide2">
     <img src="<?php echo $this->dirImg;?>/loader.gif"/>
</div>

<div id="search_price_ajax" >
	<fieldset class="g-green center2">
		<legend>Tìm cổ phiếu theo giá</legend>
		<p>Vui lòng nhập khoản giá cần tìm</p>
		<p style="margin: 10px auto;">
			Giá từ <input type="text" class="focus center2" /> Đến <input type="text" class="center2" />(nghìn đồng) 
		</p>
		<p>
			<input type="button" value="Tìm kiếm" id="searchPrice" />
		</p>
	</fieldset>
</div> 