<div class="popup">
<p>PGS - CTCP Kinh doanh Khí hoá lỏng miền Nam</p>
<div>
	<table width="100%" cellpadding="0" cellspacing="0" border="1" class="popup-data">
		<tr>
			<td align="right" width="60">Ngày</td>
			<td width="70">21/12/2010</td>			
		</tr>
		<tr>
			<td align="right">Mở của</td>
			<td>11.3</td>			
		</tr>
		<tr>
			<td align="right">Cao nhất</td>
			<td>11.3</td>			
		</tr>		
		<tr>
			<td align="right">Thấp nhất</td>
			<td>11.3</td>			
		</tr>		
		<tr>
			<td align="right">Đóng cửa</td>
			<td class="green">0</td>			
		</tr>	
		<tr>
			<td align="right">Thay đổi</td>
			<td class="green">0 0%</td>			
		</tr>
		<tr>
			<td align="right">Khối lượng</td>
			<td>186,270</td>			
		</tr>							
	</table>
	
	<table width="100%" cellpadding="0" cellspacing="0" border="0" class="popup_btn">
		<tr>
			<td><img src="<?php echo $this->dirImg?>/icon/IconNews.gif"/></td>
			<td><a>Tin tức</a></td>
		</tr>
		<tr>
			<td><img src="<?php echo $this->dirImg?>/icon/IconChart.gif"/></td>
			<td><a>Biểu đồ giá</a></td>
		</tr>
		<tr>
			<td><img src="<?php echo $this->dirImg?>/icon/IconCompany.gif"/></td>
			<td><a>Thông tin công ty</a></td>
		</tr>
		<tr>
			<td><img src="<?php echo $this->dirImg?>/icon/IconReport.gif"/></td>
			<td><a>Báo cáo tài chính</a></td>
		</tr>
	</table>
</div>	
</div>