<script type="text/javascript"
 src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
	     		 	   		
  });
</script>

<p class="mess_ajax">HoSE - Top giao dịch trong ngày</p>

<table class="top_stock_table" border="1" cellpadding="1" cellspacing="0">
	<thead>
		<tr class="top">
			<td colspan="6" style="text-align: center">
				<select>
					<option>Top 5</option>
					<option>Top 10</option>
					<option>Top 15</option>
					<option>Top 20</option>
					<option>Top 25</option>
				</select>
				Cổ phiếu tăng giá
			</td>						
		</tr>	
		<tr>		
			<td>Mã CK</td>
			<td>Giá mở cửa</td>
			<td>Giá khớp</td>
			<td>K.Lượng</td>
			<td bgcolor="#f6f6f6">+/-</td>
			<td>%</td>
		</tr>	
	</thead>
	<tbody>
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>
		<tr>
			<td>BT6</td>
			<td>68</td>
			<td>71</td>
			<td>50</td>
			<td class="green" bgcolor="#f6f6f6">+3</td>
			<td class="green">4.41%</td>
		</tr>
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>
		<tr>
			<td>BT6</td>
			<td>68</td>
			<td>71</td>
			<td>50</td>
			<td class="green" bgcolor="#f6f6f6">+3</td>
			<td class="green">4.41%</td>
		</tr>	
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>			
	</tbody>
</table>

<table class="top_stock_table" border="1" cellpadding="1" cellspacing="0">
	<thead>
		<tr class="top">
			<td colspan="6" style="text-align: center">
				<select>
					<option>Top 5</option>
					<option>Top 10</option>
					<option>Top 15</option>
					<option>Top 20</option>
					<option>Top 25</option>
				</select>
				Cổ phiếu giảm giá
			</td>						
		</tr>	
		<tr>		
			<td>Mã CK</td>
			<td>Giá mở cửa</td>
			<td>Giá khớp</td>
			<td>K.Lượng</td>
			<td bgcolor="#f6f6f6">+/-</td>
			<td>%</td>
		</tr>	
	</thead>
	<tbody>
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>
		<tr>
			<td>BT6</td>
			<td>68</td>
			<td>71</td>
			<td>50</td>
			<td class="green" bgcolor="#f6f6f6">+3</td>
			<td class="green">4.41%</td>
		</tr>
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>
		<tr>
			<td>BT6</td>
			<td>68</td>
			<td>71</td>
			<td>50</td>
			<td class="green" bgcolor="#f6f6f6">+3</td>
			<td class="green">4.41%</td>
		</tr>	
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>			
	</tbody>
</table>

<table class="top_stock_table" border="1" cellpadding="1" cellspacing="0">
	<thead>
		<tr class="top">
			<td colspan="6" style="text-align: center">
				<select>
					<option>Top 5</option>
					<option>Top 10</option>
					<option>Top 15</option>
					<option>Top 20</option>
					<option>Top 25</option>
				</select>
				Khối lượng khớp lệnh
			</td>						
		</tr>	
		<tr>		
			<td>Mã CK</td>
			<td>Giá mở cửa</td>
			<td>Giá khớp</td>
			<td>K.Lượng</td>
			<td bgcolor="#f6f6f6">+/-</td>
			<td>%</td>
		</tr>	
	</thead>
	<tbody>
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>
		<tr>
			<td>BT6</td>
			<td>68</td>
			<td>71</td>
			<td>50</td>
			<td class="green" bgcolor="#f6f6f6">+3</td>
			<td class="green">4.41%</td>
		</tr>
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>
		<tr>
			<td>BT6</td>
			<td>68</td>
			<td>71</td>
			<td>50</td>
			<td class="green" bgcolor="#f6f6f6">+3</td>
			<td class="green">4.41%</td>
		</tr>	
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>			
	</tbody>
</table>

<table class="top_stock_table" border="1" cellpadding="1" cellspacing="0">
	<thead>
		<tr class="top">
			<td colspan="6" style="text-align: center">
				<select>
					<option>Top 5</option>
					<option>Top 10</option>
					<option>Top 15</option>
					<option>Top 20</option>
					<option>Top 25</option>
				</select>
				Giá trị giao dịch
			</td>						
		</tr>	
		<tr>		
			<td>Mã CK</td>
			<td>Giá mở cửa</td>
			<td>Giá khớp</td>
			<td>K.Lượng</td>
			<td bgcolor="#f6f6f6">+/-</td>
			<td>%</td>
		</tr>	
	</thead>
	<tbody>
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>
		<tr>
			<td>BT6</td>
			<td>68</td>
			<td>71</td>
			<td>50</td>
			<td class="green" bgcolor="#f6f6f6">+3</td>
			<td class="green">4.41%</td>
		</tr>
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>
		<tr>
			<td>BT6</td>
			<td>68</td>
			<td>71</td>
			<td>50</td>
			<td class="green" bgcolor="#f6f6f6">+3</td>
			<td class="green">4.41%</td>
		</tr>	
		<tr>
			<td>EVE</td>
			<td>0</td>
			<td>45</td>
			<td>1,090</td>
			<td class="green" bgcolor="#f6f6f6">+45</td>
			<td class="green">0%</td>
		</tr>			
	</tbody>
</table>