	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item component">
				<h4>Quản lý component</h4>
				<div class="float-right">																									
					<a class="minibutton btn add" path="admin/component/add/">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="component" path="admin/component/edit" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>														
				</div>				
			</div>
			
			<div class="portlet-content">				 			
				<?php echo $this->form; ?>											
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>					    						
						<tr>
							<th width="10">#</th>
							<th width="10"></th>
							<th class="left">Tên</th>	
							<th>Template</th>
							<th>Theme</th>							
							<th width="60" class="center">ID</th>						
						</tr>
					</thead>
					<tbody class="no-link">
							<?php $i = 0; foreach ($this->components as $component): $i++; if ($i % 2 != 0) {?>							
								<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="radio" name="select" id="<?php echo $this->escape($component['id']) ?>"/></td> 
									<td class="left"><?php echo $this->escape($component['component_name']) ?></td>
									<td class="left"><a href="http://uitstock/admin/template/list/component/<?php echo $this->escape($component['id']) ?>/name/<?php echo $this->escape($component['template_name']) ?>"><?php echo $this->escape($component['template_name']) ?></a></td>
									<td class="left"><a href="http://uitstock/admin/theme/list/component/<?php echo $this->escape($component['id']) ?>/name/<?php echo $this->escape($component['theme_name']) ?>"><?php echo $this->escape($component['theme_name']) ?></a></td>																						
									<td class="center"><?php echo $this->escape($component['id']) ?></td>
								</tr>		
							<?php } else { ?>
								<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="radio" name="select" id="<?php echo $this->escape($component['id']) ?>"/></td> 
									<td class="left"><?php echo $this->escape($component['component_name']) ?></td>
									<td class="left"><a href="http://uitstock/admin/template/list/component/<?php echo $this->escape($component['id']) ?>/name/<?php echo $this->escape($component['template_name']) ?>"><?php echo $this->escape($component['template_name']) ?></a></td>
									<td class="left"><a href="http://uitstock/admin/theme/list/component/<?php echo $this->escape($component['id']) ?>/name/<?php echo $this->escape($component['theme_name']) ?>"><?php echo $this->escape($component['theme_name']) ?></a></td>																						
									<td class="center"><?php echo $this->escape($component['id']) ?></td>
								</tr>
							<?php } ?>							
							<?php endforeach ?>			
					</tbody>
				</table>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->