	<div id="content" class="xfluid">
		<div class="portlet x12 news">
			<div class="portlet-header"><h4>Danh sách thể loại</h4></div>
			
			<div class="portlet-content">
												
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
						<tr class="news-tool">
							<th></th>
							<th colspan="2">
								<input type="button" id="delete_all" value="Xóa" />
								<input type="button" id="edit_all" value="Chỉnh" />
							</th>
							<th colspan="6" class="right">
							   <a>Thêm thể loại</a>
							</th>
						</tr>
						<tr>
							<th width="2">#</th>
							<th width="5"><input type="checkbox"/></th>
							<th>Tiêu đề</th>																											
							<th width="100" class="edit-th">Edit</th>																
							<th width="2">ID</th>					
						</tr>					
					</thead>
					<tbody>
						<tr class="odd gradeX">							
							<td class="center">1</td>
							<td><input type="checkbox"/></td>
							<td class="center"><a>Tin tức</a></td>														
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /></td>														
							<td class="center">1</td>
						</tr>
						<tr class="even gradeC">							
							<td class="center">2</td>
							<td><input type="checkbox"/></td>
							<td class="center"><a>Nhận định thị trường</a></td>														
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /></td>														
							<td class="center">2</td>
						</tr>												
					</tbody>
				</table>																																	
			</div>
		</div>
	</div><!--  end #content -->