	<div id="content" class="xfluid">
		<div class="portlet x12 news">
			<div class="portlet-header"><h4>Danh sách tin</h4></div>
			
			<div class="portlet-content">
												
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
						<tr class="tool">
							<th></th>
							<th colspan="2">
								<input type="button" id="delete_all" value="Xóa" />
								<input type="button" id="edit_all" value="Chỉnh" />
							</th>
							<th colspan="5" class="right">
								<input type="txt" id="txtsearch" value="" />
							   <input type="button" id="btnsearch" value="Tìm kiếm" />
							</th>
							<th class="right">							   
							   <a>Thêm tin</a>
							</th>
						</tr>
						<tr>
							<th>#</th>
							<th width="5"><input type="checkbox"/></th>
							<th>Tiêu đề</th>
							<th>Ngày</th>
							<th>Số lần xem</th>
							<th>Loại tin</th>
							<th>Thể loại</th>
							<th class="edit-th">Edit</th>																
							<th>ID</th>					
						</tr>					
					</thead>
					<tbody>
						<tr class="odd gradeX">							
							<td class="center">1</td>
							<td><input type="checkbox"/></td>
							<td class="center"><a>Huy động và cho vay vốn bằng vàng: Vì sao phải siết?</a></td>
							<td class="center">28/10/2010</td>
							<td class="center">100</td>
							<td class="center">Tin vắn chứng khoán</td>
							<td class="center">Tin tức</td>
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<a>Xem</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" title="Ẩn hiện" /><img src="<?php echo $this->dirImg; ?>/NoiBat_1.jpg" title="Nổi bật" /></td>														
							<td class="center">1</td>
						</tr>
						<tr class="even gradeC">							
							<td class="center">2</td>
							<td><input type="checkbox"/></td>
							<td class="center"><a>SDH: chủ tịch HĐQT đăng ký mua 1 triệu CP</a></td>
							<td class="center">28/10/2010</td>
							<td class="center">100</td>
							<td class="center">Tin vắn chứng khoán</td>
							<td class="center">Tin tức</td>
							<td class="center edit"><a>Chỉnh</a>|<a>Xóa</a>|<a>Xem</a>|<img src="<?php echo $this->dirImg; ?>/AnHien_1.jpg" /><img src="<?php echo $this->dirImg; ?>/NoiBat_0.jpg" /></td>														
							<td class="center">2</td>
						</tr>												
					</tbody>
				</table>																																	
			</div>
		</div>
	</div><!--  end #content -->