<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item article">
			<h4>Thêm tin</h4>
			<div class="float-right">
				<div class="global" back="<?php echo $_SESSION['temp']; ?>"></div>
				<a class="minibutton btn close">
						<span><span class="icon close"></span>Đóng</span>
				</a>							
			</div>				
		</div>
		
		<div class="portlet-content">
			<?php if (isset($this->message)) {?>
				<div class="message">
					<?php echo $this->message; ?>
				</div>					
			<?php } ?>
			<?php echo $this->form;  ?>	
			<script>
			var editor = CKEDITOR.replace( 'Content',{
				uiColor : '#9AB8F3',
				language:'vi',
				skin:'v2',
				filebrowserImageBrowseUrl : 'admin/themes/default/js/ckfinder/ckfinder.html?Type=Images',
				filebrowserFlashBrowseUrl : 'admin/themes/default/js/ckfinder/ckfinder.html?Type=Flash',
				filebrowserImageUploadUrl : 'admin/themes/default/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
				filebrowserFlashUploadUrl : 'admin/themes/default/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
				toolbar:[
				['Source','-','Save','NewPage','Preview','-','Templates'],
				['Cut','Copy','Paste','PasteText','PasteFromWord','-','Print'],
				['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
				['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
				['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
				['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
				['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
				['Link','Unlink','Anchor'],
				['Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak'],
				['Styles','Format','Font','FontSize'],
				['TextColor','BGColor'],
				['Maximize', 'ShowBlocks','-','About']
				]
			});	
			</script>																																				
		</div><!--  end .portlet-content -->
	</div>
</div><!--  end #content -->