	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item contentCategory">
				<h4>Quản lý loại tin</h4>
				<div class="float-right">	
				    <div class="global" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>"></div>																								
					<?php 								
		 				foreach ($this->button1 as $button) {
		 					echo stripslashes($button['button1']);
		 				}	 									 				
					?>					
				</div>				
			</div>
			
			<?php 
				$flag = false;		
 				foreach ($this->privileges as $privilege) {
					if ($privilege['id'] == 31) $flag = true; 
 				}
  				if ($flag) {					 				
			?>
			<div class="portlet-content">							 							                													
				<table width="100%" cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/article/auto-suggestion-cat" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" value="Tìm kiếm" name="name" class="btnSearch" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   						
						</tr>
						
						<tr>
							<th width="10">#</th>
							<th width="10"></th>	
							<th>Name</th>
							<th>Alias</th>							
							<th class="center">Published</th>														
							<th width="10" class="right">ID</th>							
						</tr>
					</thead>
					<tbody class="rows no-link2">
							<?php $i = 0; foreach ($this->parents as $parent): $i++; $parentId = $parent->id; ?>
								<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="radio" name="select" id="<?php echo $this->escape($parent['id']) ?>" value="<?php echo $this->escape($parent['id']) ?>"  /></td> 
									<td class="left"><a href="admin/article/view-cat/id/<?php echo $this->escape($parent['id']) ?>"><?php echo $this->escape($parent['name']) ?></a></td>
									<td class="left"><?php echo $this->escape($parent['alias']) ?></td>								
									<td class="center">
										<?php if ($parent['published'] == 1) {
											$title = "Click vào để ẩn loại tin";
											$img =  $this->dirImg . '/AnHien_1.png'; 
											} else {
											$title = "Click vào để hiện loại tin";	
											$img = $this->dirImg . '/AnHien_0.png';
											}
										?>
										<img name="contentCategory" mapper="contentCategoryMapper" path="admin/article/set-publish" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($parent['id']) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>																															
									<td class="right"><?php echo $this->escape($parent['id']) ?></td>
								</tr>		
								<?php 
									if (null != $this->subs) {
										foreach ($this->subs as $sub): $i++; if ($sub->parent_id == $parentId) {									
								?>
									<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="radio" name="select" id="<?php echo $this->escape($sub->id) ?>" value="<?php echo $this->escape($sub->id) ?>"  /></td> 
									<td class="left inside"><a href="admin/article/view-cat/id/<?php echo $this->escape($sub->id) ?>"><?php echo $this->escape($sub->name) ?></a></td>
									<td class="left"><?php echo $this->escape($sub->alias) ?></td>								
									<td class="center">
										<?php if ($sub->published == 1) {
											$title = "Click vào để ẩn loại tin";
											$img =  $this->dirImg . '/AnHien_1.png'; 
											} else {
											$title = "Click vào để hiện loại tin";	
											$img = $this->dirImg . '/AnHien_0.png';
											}
										?>
										<img name="contentCategory" mapper="contentCategoryMapper" path="admin/article/set-publish" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($sub->id) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>																															
									<td class="right"><?php echo $this->escape($sub->id) ?></td>
								</tr>							
								<?php } endforeach; } ?>									
							<?php endforeach ?>			
					</tbody>
				</table>
				<?php echo $this->paginationControl($this->parents, 'Sliding', 'pagination.phtml'); ?>																																	
			</div>
			<?php } ?>			
		</div>			
		
	</div><!--  end #content -->