	<div id="content" class="xfluid">
		<div class="portlet x12">
			<div class="portlet-header item article">
				<h4>Quản lý tin</h4>
				<div class="float-right">																									
					<a class="minibutton btn add" path="admin/article/add-article">
						<span><span class="icon add"></span>Thêm</span>
					</a>
					<a class="minibutton btn edit" name="tin" path="admin/article/edit-article" >
						<span><span class="icon edit" ></span>Sửa</span>
					</a>
					<a class="minibutton btn important" name="tin" path="admin/article/set-important" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon default"></span>Quan trọng</span>
					</a>
					<a class="minibutton btn normal" name="tin" path="admin/article/set-normal" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon normal"></span>Bình thường</span>
					</a>
					<a class="minibutton btn publish" name="tin" mapper="articleMapper" path="admin/article/publish" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon publish"></span>Published</span>
					</a>
					<a class="minibutton btn unpublish" name="tin" mapper="articleMapper" path="admin/article/unpublish" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon unpublish"></span>Unpublished</span>
					</a>
					<a class="minibutton btn deleteall" name="tin" path="admin/article/delete-article" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>">
						<span><span class="icon delete"></span>Xóa</span>
					</a>					
				</div>				
			</div>
			
			<div class="portlet-content">				 							                														
				<table cellpadding="0" cellspacing="0" border="0" class="display">
					<thead>
					    <tr class="tool">														
							<th colspan="5">
							   <div id="suggest"><br />
							        <input type="text" size="25" value="" class="txtSearch" onkeyup="suggest(this.value);" onblur="fill();" path="admin/article/auto-suggestion-article" />							     
							      	<div class="suggestionsBox" id="suggestions" style="display: none;">
							      		<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
							      </div>
							      <input type="button" value="Tìm kiếm" name="title" class="btnSearch" currentpath="<?php echo $_SERVER['REQUEST_URI']; ?>" />							      
							   </div>
							</th>														  							   						
						</tr>
						
						<tr>
							<th width="10">#</th>
							<th width="10"><input type="checkbox" id="select_all"></th>	
							<th width="500">Tiêu đề</th>
							<th width="200" class="center">Loại tin</th>	
							<th width="10" class="center">Ngày</th>						
							<th width="10" class="center">Published</th>
							<th width="100" class="center">Quan trọng</th>
							<th width="10">Count</th>																												
							<th width="10" class="right">ID</th>							
						</tr>
					</thead>
					<tbody class="rows no-link2">
							<?php $i = 0; foreach ($this->articles as $article): $i++; if ($i % 2 != 0) {?>
								<tr class="odd gradeX" >							
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="checkbox" name="select" id="<?php echo $this->escape($article['id']) ?>" value="<?php echo $this->escape($article['id']) ?>"  /></td> 
									<td class="left"><a href="admin/article/view-article/id/<?php echo $this->escape($article['id']) ?>"><?php echo $this->escape($article['title']) ?></a></td>
									<td class="center"><?php echo $this->escape($article['cat_name']) ?></td>								
									<td class="left">
										<?php
											  $date = $this->escape($article['create_date']); 																					  
											  $date = new Zend_Date($date, Cloud_Model_Utli_CloudUtli::DATE);
											  $date = $date->get(Cloud_Model_Utli_CloudUtli::DATE);
											  echo $date; 						
										?>
									</td>
									<td class="center">
										<?php if ($article['published'] == 1) {
											$title = "Click vào để ẩn Category";
											$img =  $this->dirImg . '/AnHien_1.png'; 
											} else {
											$title = "Click vào để hiện Category";	
											$img = $this->dirImg . '/AnHien_0.png';
											}
										?>
										<img name="article" mapper="articleMapper" path="admin/article/set-publish" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($article['id']) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>	
									<td class="center"><img class="important" src="<?php if ($article['important'] == 1) echo $this->dirImg; ?>/default.png" title="Quan trọng" pathDirImg="<?php echo $this->dirImg; ?>"/></td>
									<td class="center"><?php echo $this->escape($article['count']) ?></td>																														
									<td class="right"><?php echo $this->escape($article['id']) ?></td>
								</tr>		
								<?php } else { ?>
								<tr class="even gradeC">
									<td class="left"><?php echo $i ?></td>
									<td class="center"><input type="checkbox" name="select" id="<?php echo $this->escape($article['id']) ?>" value="<?php echo $this->escape($article['id']) ?>"  /></td> 
									<td class="left"><a href="admin/article/view-article/id/<?php echo $this->escape($article['id']) ?>"><?php echo $this->escape($article['title']) ?></a></td>
									<td class="center"><?php echo $this->escape($article['cat_name']) ?></td>								
									<td class="left">
										<?php
											  $date = $this->escape($article['create_date']); 																					  
											  $date = new Zend_Date($date, Cloud_Model_Utli_CloudUtli::DATE);
											  $date = $date->get(Cloud_Model_Utli_CloudUtli::DATE);
											  echo $date; 						
										?>
									</td>
									<td class="center">
										<?php if ($article['published'] == 1) {
											$title = "Click vào để ẩn Category";
											$img =  $this->dirImg . '/AnHien_1.png'; 
											} else {
											$title = "Click vào để hiện Category";	
											$img = $this->dirImg . '/AnHien_0.png';
											}
										?>
										<img name="article" mapper="articleMapper" path="admin/article/set-publish" src="<?php echo $img; ?>" class="click pub" title="<?php echo $title; ?>" id="<?php echo $this->escape($article['id']) ?>" pathDirImg="<?php echo $this->dirImg; ?>" />
									</td>	
									<td class="center"><img class="important" ssrc="<?php if ($article['important'] == 1) echo $this->dirImg; ?>/default.png" title="Quan trọng" pathDirImg="<?php echo $this->dirImg; ?>"/></td>
									<td class="center"><?php echo $this->escape($article['count']) ?></td>																														
									<td class="right"><?php echo $this->escape($article['id']) ?></td>									
							<?php } endforeach ?>			
					</tbody>
				</table>
				<?php echo $this->paginationControl($this->articles, 'Sliding', 'pagination.phtml'); ?>																																	
			</div>
		</div>			
		
	</div><!--  end #content -->