<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item contentCategory">
			<h4>Xem loại tin</h4>
			<div class="float-right">		
				<?php 
					$id = $this->category->id;
					if ($this->category->parent_id == 0) $link = "pid/$id";
					else $link = "id/$id"; 
				?>						
				<div class="global" id="<?php echo $this->category->id ?>" path1="admin/article/edit-cat/id/<?php echo $this->category->id ?>" path2="admin/article/delete-cat" path3="admin/article/list-article/<?php echo $link; ?>"></div>																				
				<a class="minibutton btn view">
					<span><span class="icon view" ></span>Xem tin</span>
				</a>																																								
				<a class="minibutton btn edit2">
					<span><span class="icon edit" ></span>Sửa</span>
				</a>
				<a class="minibutton btn delete2" name="loại tin">
						<span><span class="icon delete"></span>Xóa</span>
				</a>
				<a class="minibutton btn close" name="loại tin">
						<span><span class="icon close"></span>Đóng</span>
				</a>								
			</div>				
		</div>
		
		<div class="portlet-content">									 							                													
			<table cellpadding="0" cellspacing="0" border="0" class="display">
				<tr>
					<td width="90"><b>Category name:</b></td>
					<td><?php echo $this->category->name; ?></td>
				</tr>
				<tr>
					<td><b>Alias:</b></td>
					<td><?php echo $this->category->alias; ?></td>
				</tr>
				<tr>
					<td><b>Sub:</b></td>
					<td><?php echo $this->sub; ?></td>
				</tr>
				<tr>
					<td><b>Description:</b></td>
					<td><?php echo $this->category->description; ?></td>
				</tr>
				<tr>
					<td><b>Published:</b></td>
					<?php $published = ($this->category->published == 1) ? "Yes" : "No"; ?>
					<td><?php echo $published; ?></td>
				</tr>
			</table>
																																				
		</div>
	</div>			
	
</div><!--  end #content -->