<div id="content" class="xfluid">
	<div class="portlet x12">
		<div class="portlet-header item article">
			<h4>Xem tin</h4>
			<div class="float-right">																																																																								
				<a class="minibutton btn edit2" path="admin/article/edit-article/id/<?php echo $this->article['id'] ?>" >
					<span><span class="icon edit" ></span>Sửa</span>
				</a>
				<a class="minibutton btn delete2" name="tin" path="admin/article/delete-article" id="<?php echo $this->article['id'] ?>" back="<?php echo $_SESSION['temp']; ?>">
						<span><span class="icon delete"></span>Xóa</span>
				</a>
				<a class="minibutton btn close" name="tin" back="<?php echo $_SESSION['temp']; ?>">
						<span><span class="icon close"></span>Đóng</span>
				</a>								
			</div>				
		</div>
		
		<div class="portlet-content">									 							                													
			<table cellpadding="0" cellspacing="0" border="0" class="display">
				<tr>
					<td width="90"><b>Tiêu đề:</b></td>
					<td><?php echo $this->article['title']; ?></td>
				</tr>
				<tr>
					<td><b>Alias:</b></td>
					<td><?php echo $this->article['alias']; ?></td>
				</tr>
				<tr>
					<td><b>Tin liên quan:</b></td>
					<td>
						<?php 
							foreach ($this->entries as $entry) {
								if ($entry->relative_id == $this->article['id'])
									echo $entry->title . '<br/>';								
							}
						?>
					</td>
				</tr>
				<tr>
					<td><b>Ngày đăng tin:</b></td>
					<td>
						<?php 
							  $date = $this->article['create_date'];
							  $date = new Zend_Date($date, Cloud_Model_Utli_CloudUtli::DATE);
							  $date = $date->get(Cloud_Model_Utli_CloudUtli::DATE);
							  echo $date; 
						?>
					</td>
				</tr>
				<tr>
					<td><b>Ngày sửa tin:</b></td>
					<td>
						<?php
							  $date = $this->article['modify_date'];	
							  if (null != $date) {
							  	$date = new Zend_Date($date, Cloud_Model_Utli_CloudUtli::DATE);
							  	$date = $date->get(Cloud_Model_Utli_CloudUtli::DATE);
							  	echo $date; 	
							  }																	  						 
						?>
					</td>
				</tr>
				<tr>
					<td><b>Published:</b></td>
					<?php $published = ($this->article["published"] == 1) ? "Có" : "Không"; ?>
					<td><?php echo $published; ?></td>
				</tr>
				<tr>
					<td><b>Quan trọng:</b></td>
					<?php $published = ($this->article["important"] == 1) ? "Có" : "Không"; ?>
					<td><?php echo $published; ?></td>
				</tr>
				<tr>
					<td><b>Count:</b></td>
					<td><?php echo $this->article['count']; ?></td>
				</tr>
				<tr>
					<td><b>Tóm tắt:</b></td>
					<td><?php echo $this->article['summarize']; ?></td>
				</tr>	
				<tr>
					<td><b>Hình:</b></td>
					<td><img width="200" height="150" src="<?php echo $this->article['image']; ?>"></img></td>
				</tr>	
				<tr>
					<td><b>Nội dung:</b></td>
					<td><?php echo $this->article['content']; ?></td>
				</tr>						
				
			</table>
																																				
		</div>
	</div>			
	
</div><!--  end #content -->