<section id="stock-horzintal">
	   <h2 id="stock-exchange">HOSE</h2>	
																												
	   <p id="stock-rate">                         
		  <marquee onmouseover="this.stop()" onmouseout="this.start()" direction="left" scrollamount="4" loop="-1">
			 <span class="red">TLG 31,4<img src="<?php echo $this->dirImg; ?>/down.gif" /> 1,5 </span><span>VMD 28,5 0 </span><span class="green">VOS 11,7 <img src="<?php echo $this->dirImg; ?>/up.gif" /> 0,3</span>
		  </marquee>                                                 
	   </p>

       <div class="clear"></div><!-- end .clear -->
</section>